// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspjpeg.h

// Package jpeg provides direct TinyGo bindings for pspjpeg.h.
package jpeg

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceJpegInitMJpeg sceJpegInitMJpeg
func SceJpegInitMJpeg() int32

//go:linkname SceJpegFinishMJpeg sceJpegFinishMJpeg
func SceJpegFinishMJpeg() int32

//go:linkname SceJpegCreateMJpeg sceJpegCreateMJpeg
func SceJpegCreateMJpeg(width int32, height int32) int32

//go:linkname SceJpegDeleteMJpeg sceJpegDeleteMJpeg
func SceJpegDeleteMJpeg() int32

//go:linkname SceJpegDecodeMJpeg sceJpegDecodeMJpeg
func SceJpegDecodeMJpeg(jpegbuf unsafe.Pointer, size uint32, rgba unsafe.Pointer, unk uint32) int32

//go:linkname SceJpegGetOutputInfo sceJpegGetOutputInfo
func SceJpegGetOutputInfo(jpegbuf unsafe.Pointer, size uint32, colourInfo unsafe.Pointer, unk int32) int32

//go:linkname SceJpegDecodeMJpegYCbCr sceJpegDecodeMJpegYCbCr
func SceJpegDecodeMJpegYCbCr(jpegbuf unsafe.Pointer, size uint32, yCbCr unsafe.Pointer, yCbCrSize uint32, unk uint32) int32

//go:linkname SceJpegCsc sceJpegCsc
func SceJpegCsc(imageAddr unsafe.Pointer, yCbCrAddr unsafe.Pointer, widthHeight int32, bufferWidth int32, colourInfo int32) int32
