// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: systemctrl_adrenaline.h

// Package systemctrl_adrenaline provides direct TinyGo bindings for systemctrl_adrenaline.h.
package systemctrl_adrenaline

import "unsafe"

var _ unsafe.Pointer

func init() { requireAdrenalinectrl() }

//go:linkname requireAdrenalinectrl pspsdk_go_require_adrenalinectrl
func requireAdrenalinectrl()

const (
	PSP_MODULE_USER                 = 0
	PSP_MODULE_NO_STOP              = 1
	PSP_MODULE_SINGLE_LOAD          = 2
	PSP_MODULE_SINGLE_START         = 4
	PSP_MODULE_KERNEL               = 4096
	SCE_MODULE_ATTR_NONE            = 0
	SCE_MODULE_ATTR_CANT_STOP       = 1
	SCE_MODULE_ATTR_EXCLUSIVE_LOAD  = 2
	SCE_MODULE_ATTR_EXCLUSIVE_START = 4
	SCE_MODULE_USER                 = 0
	SCE_MODULE_MS                   = 512
	SCE_MODULE_USB_WLAN             = 1024
	SCE_MODULE_APP                  = 1536
	SCE_MODULE_VSH                  = 2048
	SCE_MODULE_KERNEL               = 4096
	SCE_MODULE_KIRK_MEMLMD_LIB      = 8192
	SCE_MODULE_KIRK_SEMAPHORE_LIB   = 16384
)

//go:linkname SctrlGetUsbState sctrlGetUsbState
func SctrlGetUsbState() int32

//go:linkname SctrlStartUsb sctrlStartUsb
func SctrlStartUsb() int32

//go:linkname SctrlStopUsb sctrlStopUsb
func SctrlStopUsb() int32

//go:linkname SctrlRebootDevice sctrlRebootDevice
func SctrlRebootDevice() int32

//go:linkname SctrlHENFindImportLib sctrlHENFindImportLib
func SctrlHENFindImportLib(mod unsafe.Pointer, library unsafe.Pointer) unsafe.Pointer
