// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspfpu.h

// Package fpu provides direct TinyGo bindings for pspfpu.h.
package fpu

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_FPU_RN                  = 0
	PSP_FPU_RZ                  = 1
	PSP_FPU_RP                  = 2
	PSP_FPU_RM                  = 3
	PSP_FPU_EXCEPTION_INEXACT   = 1
	PSP_FPU_EXCEPTION_UNDERFLOW = 2
	PSP_FPU_EXCEPTION_OVERFLOW  = 4
	PSP_FPU_EXCEPTION_DIVBYZERO = 8
	PSP_FPU_EXCEPTION_INVALIDOP = 16
	PSP_FPU_EXCEPTION_UNIMPOP   = 32
	PSP_FPU_EXCEPTION_ALL       = 63
)

//go:linkname PspFpuGetFCR31 pspFpuGetFCR31
func PspFpuGetFCR31() int32

//go:linkname PspFpuSetFCR31 pspFpuSetFCR31
func PspFpuSetFCR31(varValue uint32)

//go:linkname PspFpuSetRoundmode pspFpuSetRoundmode
func PspFpuSetRoundmode(mode int32)

//go:linkname PspFpuGetRoundmode pspFpuGetRoundmode
func PspFpuGetRoundmode() int32

//go:linkname PspFpuGetFlags pspFpuGetFlags
func PspFpuGetFlags() int32

//go:linkname PspFpuClearFlags pspFpuClearFlags
func PspFpuClearFlags(clear uint32)

//go:linkname PspFpuGetEnable pspFpuGetEnable
func PspFpuGetEnable() int32

//go:linkname PspFpuSetEnable pspFpuSetEnable
func PspFpuSetEnable(enable uint32)

//go:linkname PspFpuGetCause pspFpuGetCause
func PspFpuGetCause() int32

//go:linkname PspFpuClearCause pspFpuClearCause
func PspFpuClearCause(clear uint32)

//go:linkname PspFpuGetFS pspFpuGetFS
func PspFpuGetFS() int32

//go:linkname PspFpuSetFS pspFpuSetFS
func PspFpuSetFS(fs uint32)

//go:linkname PspFpuGetCondbits pspFpuGetCondbits
func PspFpuGetCondbits() int32

//go:linkname PspFpuClearCondbits pspFpuClearCondbits
func PspFpuClearCondbits(clear uint32)

//go:linkname PspFpuAbs pspFpuAbs
func PspFpuAbs(f float32) float32

//go:linkname PspFpuCeil pspFpuCeil
func PspFpuCeil(f float32) int32

//go:linkname PspFpuFloor pspFpuFloor
func PspFpuFloor(f float32) int32

//go:linkname PspFpuMax pspFpuMax
func PspFpuMax(f1 float32, f2 float32) float32

//go:linkname PspFpuMin pspFpuMin
func PspFpuMin(f1 float32, f2 float32) float32

//go:linkname PspFpuNeg pspFpuNeg
func PspFpuNeg(f float32) float32

//go:linkname PspFpuRound pspFpuRound
func PspFpuRound(f float32) int32

//go:linkname PspFpuRsqrt pspFpuRsqrt
func PspFpuRsqrt(f float32) float32

//go:linkname PspFpuSqrt pspFpuSqrt
func PspFpuSqrt(f float32) float32

//go:linkname PspFpuTrunc pspFpuTrunc
func PspFpuTrunc(f float32) int32

//go:linkname PspFpuFmod pspFpuFmod
func PspFpuFmod(fs float32, fd float32) float32

//go:linkname PspFpuFrac pspFpuFrac
func PspFpuFrac(f float32) float32

//go:linkname PspFpuReinterpretFloat pspFpuReinterpretFloat
func PspFpuReinterpretFloat(ui uint32) float32

//go:linkname PspFpuReinterpretUint pspFpuReinterpretUint
func PspFpuReinterpretUint(f float32) int32

//go:linkname PspFpuIsEqual pspFpuIsEqual
func PspFpuIsEqual(f1 float32, f2 float32) int32

//go:linkname PspFpuSignFloat pspFpuSignFloat
func PspFpuSignFloat(f float32) float32

//go:linkname PspFpuSignInt pspFpuSignInt
func PspFpuSignInt(f float32) int32

//go:linkname PspFpuPositiveZero pspFpuPositiveZero
func PspFpuPositiveZero() float32

//go:linkname PspFpuNegativeZero pspFpuNegativeZero
func PspFpuNegativeZero() float32

//go:linkname PspFpuIsZero pspFpuIsZero
func PspFpuIsZero(f float32) int32

//go:linkname PspFpuIsPositiveZero pspFpuIsPositiveZero
func PspFpuIsPositiveZero(f float32) int32

//go:linkname PspFpuIsNegativeZero pspFpuIsNegativeZero
func PspFpuIsNegativeZero(f float32) int32

//go:linkname PspFpuIsDenormal pspFpuIsDenormal
func PspFpuIsDenormal(f float32) int32

//go:linkname PspFpuIsZeroOrDenormal pspFpuIsZeroOrDenormal
func PspFpuIsZeroOrDenormal(f float32) int32

//go:linkname PspFpuPositiveInf pspFpuPositiveInf
func PspFpuPositiveInf() float32

//go:linkname PspFpuNegativeInf pspFpuNegativeInf
func PspFpuNegativeInf() float32

//go:linkname PspFpuIsInf pspFpuIsInf
func PspFpuIsInf(f float32) int32

//go:linkname PspFpuPositiveNaN pspFpuPositiveNaN
func PspFpuPositiveNaN() float32

//go:linkname PspFpuNegativeNaN pspFpuNegativeNaN
func PspFpuNegativeNaN() float32

//go:linkname PspFpuPositiveQNaN pspFpuPositiveQNaN
func PspFpuPositiveQNaN() float32

//go:linkname PspFpuNegativeQNaN pspFpuNegativeQNaN
func PspFpuNegativeQNaN() float32

//go:linkname PspFpuPositiveSNaN pspFpuPositiveSNaN
func PspFpuPositiveSNaN(uiSignal uint32) float32

//go:linkname PspFpuNegativeSNaN pspFpuNegativeSNaN
func PspFpuNegativeSNaN(uiSignal uint32) float32

//go:linkname PspFpuIsNaN pspFpuIsNaN
func PspFpuIsNaN(f float32) int32

//go:linkname PspFpuIsInfOrNaN pspFpuIsInfOrNaN
func PspFpuIsInfOrNaN(f float32) int32

//go:linkname PspFpuNormalizePhase pspFpuNormalizePhase
func PspFpuNormalizePhase(f float32) float32

//go:linkname PspFpuSin pspFpuSin
func PspFpuSin(x float32) float32

//go:linkname PspFpuCos pspFpuCos
func PspFpuCos(x float32) float32

//go:linkname PspFpuAtan pspFpuAtan
func PspFpuAtan(x float32) float32

//go:linkname PspFpuLog pspFpuLog
func PspFpuLog(x float32) float32

//go:linkname PspFpuExp pspFpuExp
func PspFpuExp(x float32) float32

//go:linkname PspFpuAsin pspFpuAsin
func PspFpuAsin(x float32) float32

//go:linkname PspFpuAcos pspFpuAcos
func PspFpuAcos(x float32) float32

//go:linkname PspFpuFloatToDouble pspFpuFloatToDouble
func PspFpuFloatToDouble(a float32) float64

//go:linkname PspFpuDoubleToFloat pspFpuDoubleToFloat
func PspFpuDoubleToFloat(a float64) float32
