// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psploadexec.h

// Package loadexec provides direct TinyGo bindings for psploadexec.h.
package loadexec

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelRegisterExitCallback sceKernelRegisterExitCallback
func SceKernelRegisterExitCallback(cbid int32) int32

//go:linkname SceKernelExitGame sceKernelExitGame
func SceKernelExitGame()

//go:linkname SceKernelLoadExec sceKernelLoadExec
func SceKernelLoadExec(file unsafe.Pointer, param unsafe.Pointer) int32
