// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: systemctrl.h

// Package systemctrl provides direct TinyGo bindings for systemctrl.h.
package systemctrl

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspsystemctrlKernel() }

//go:linkname requirePspsystemctrlKernel pspsdk_go_require_pspsystemctrl_kernel
func requirePspsystemctrlKernel()

const (
	PSP_MODULE_USER                                 = 0
	PSP_MODULE_NO_STOP                              = 1
	PSP_MODULE_SINGLE_LOAD                          = 2
	PSP_MODULE_SINGLE_START                         = 4
	PSP_MODULE_KERNEL                               = 4096
	PSP_THREAD_ATTR_VFPU                            = 16384
	PSP_THREAD_ATTR_USER                            = 2147483648
	PSP_THREAD_ATTR_USBWLAN                         = 2684354560
	PSP_THREAD_ATTR_VSH                             = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM                    = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK                    = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK                     = 2097152
	PSP_THREAD_RUNNING                              = 1
	PSP_THREAD_READY                                = 2
	PSP_THREAD_WAITING                              = 4
	PSP_THREAD_SUSPEND                              = 8
	PSP_THREAD_STOPPED                              = 16
	PSP_THREAD_KILLED                               = 32
	PSP_LW_MUTEX_ATTR_THFIFO                        = 0
	PSP_LW_MUTEX_ATTR_THPRI                         = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE                     = 512
	PSP_EVENT_WAITSINGLE                            = 0
	PSP_EVENT_WAITMULTIPLE                          = 512
	PSP_EVENT_WAITAND                               = 0
	PSP_EVENT_WAITOR                                = 1
	PSP_EVENT_WAITCLEAR                             = 32
	SCE_KERNEL_TMID_Thread                          = 1
	SCE_KERNEL_TMID_Semaphore                       = 2
	SCE_KERNEL_TMID_EventFlag                       = 3
	SCE_KERNEL_TMID_Mbox                            = 4
	SCE_KERNEL_TMID_Vpl                             = 5
	SCE_KERNEL_TMID_Fpl                             = 6
	SCE_KERNEL_TMID_Mpipe                           = 7
	SCE_KERNEL_TMID_Callback                        = 8
	SCE_KERNEL_TMID_ThreadEventHandler              = 9
	SCE_KERNEL_TMID_Alarm                           = 10
	SCE_KERNEL_TMID_VTimer                          = 11
	SCE_KERNEL_TMID_SleepThread                     = 64
	SCE_KERNEL_TMID_DelayThread                     = 65
	SCE_KERNEL_TMID_SuspendThread                   = 66
	SCE_KERNEL_TMID_DormantThread                   = 67
	THREADEVENT_ALL                                 = 4294967295
	THREADEVENT_KERN                                = 4294967288
	THREADEVENT_USER                                = 4294967280
	THREADEVENT_CURRENT                             = 0
	THREAD_CREATE                                   = 1
	THREAD_START                                    = 2
	THREAD_EXIT                                     = 4
	THREAD_DELETE                                   = 8
	FIO_S_IFMT                                      = 61440
	FIO_S_IFLNK                                     = 16384
	FIO_S_IFDIR                                     = 4096
	FIO_S_IFREG                                     = 8192
	FIO_S_ISUID                                     = 2048
	FIO_S_ISGID                                     = 1024
	FIO_S_ISVTX                                     = 512
	FIO_S_IRWXU                                     = 448
	FIO_S_IRUSR                                     = 256
	FIO_S_IWUSR                                     = 128
	FIO_S_IXUSR                                     = 64
	FIO_S_IRWXG                                     = 56
	FIO_S_IRGRP                                     = 32
	FIO_S_IWGRP                                     = 16
	FIO_S_IXGRP                                     = 8
	FIO_S_IRWXO                                     = 7
	FIO_S_IROTH                                     = 4
	FIO_S_IWOTH                                     = 2
	FIO_S_IXOTH                                     = 1
	FIO_SO_IFMT                                     = 56
	FIO_SO_IFLNK                                    = 8
	FIO_SO_IFDIR                                    = 16
	FIO_SO_IFREG                                    = 32
	FIO_SO_IROTH                                    = 4
	FIO_SO_IWOTH                                    = 2
	FIO_SO_IXOTH                                    = 1
	IOASSIGN_RDWR                                   = 0
	IOASSIGN_RDONLY                                 = 1
	SCE_MODULE_ATTR_NONE                            = 0
	SCE_MODULE_ATTR_CANT_STOP                       = 1
	SCE_MODULE_ATTR_EXCLUSIVE_LOAD                  = 2
	SCE_MODULE_ATTR_EXCLUSIVE_START                 = 4
	SCE_MODULE_USER                                 = 0
	SCE_MODULE_MS                                   = 512
	SCE_MODULE_USB_WLAN                             = 1024
	SCE_MODULE_APP                                  = 1536
	SCE_MODULE_VSH                                  = 2048
	SCE_MODULE_KERNEL                               = 4096
	SCE_MODULE_KIRK_MEMLMD_LIB                      = 8192
	SCE_MODULE_KIRK_SEMAPHORE_LIB                   = 16384
	PSP_SMEM_Low                                    = 0
	SCHED_OTHER                                     = 0
	SCHED_MIN                                       = 0
	SCHED_MAX                                       = 2
	PTHREAD_MUTEX_TIMED_NP                          = 0
	PTHREAD_MUTEX_ADAPTIVE_NP                       = 0
	PTHREAD_MUTEX_NORMAL                            = 0
	PTHREAD_MUTEX_RECURSIVE                         = 1
	PTHREAD_MUTEX_ERRORCHECK                        = 2
	PTHREAD_MUTEX_DEFAULT                           = 0
	SCE_KERNEL_ERROR_OK                             = 0
	SCE_KERNEL_ERROR_ERROR                          = 2147614721
	SCE_KERNEL_ERROR_NOTIMP                         = 2147614722
	SCE_KERNEL_ERROR_ILLEGAL_EXPCODE                = 2147614770
	SCE_KERNEL_ERROR_EXPHANDLER_NOUSE               = 2147614771
	SCE_KERNEL_ERROR_EXPHANDLER_USED                = 2147614772
	SCE_KERNEL_ERROR_SYCALLTABLE_NOUSED             = 2147614773
	SCE_KERNEL_ERROR_SYCALLTABLE_USED               = 2147614774
	SCE_KERNEL_ERROR_ILLEGAL_SYSCALLTABLE           = 2147614775
	SCE_KERNEL_ERROR_ILLEGAL_PRIMARY_SYSCALL_NUMBER = 2147614776
	SCE_KERNEL_ERROR_PRIMARY_SYSCALL_NUMBER_INUSE   = 2147614777
	SCE_KERNEL_ERROR_ILLEGAL_CONTEXT                = 2147614820
	SCE_KERNEL_ERROR_ILLEGAL_INTRCODE               = 2147614821
	SCE_KERNEL_ERROR_CPUDI                          = 2147614822
	SCE_KERNEL_ERROR_FOUND_HANDLER                  = 2147614823
	SCE_KERNEL_ERROR_NOTFOUND_HANDLER               = 2147614824
	SCE_KERNEL_ERROR_ILLEGAL_INTRLEVEL              = 2147614825
	SCE_KERNEL_ERROR_ILLEGAL_ADDRESS                = 2147614826
	SCE_KERNEL_ERROR_ILLEGAL_INTRPARAM              = 2147614827
	SCE_KERNEL_ERROR_ILLEGAL_STACK_ADDRESS          = 2147614828
	SCE_KERNEL_ERROR_ALREADY_STACK_SET              = 2147614829
	SCE_KERNEL_ERROR_NO_TIMER                       = 2147614870
	SCE_KERNEL_ERROR_ILLEGAL_TIMERID                = 2147614871
	SCE_KERNEL_ERROR_ILLEGAL_SOURCE                 = 2147614872
	SCE_KERNEL_ERROR_ILLEGAL_PRESCALE               = 2147614873
	SCE_KERNEL_ERROR_TIMER_BUSY                     = 2147614874
	SCE_KERNEL_ERROR_TIMER_NOT_SETUP                = 2147614875
	SCE_KERNEL_ERROR_TIMER_NOT_INUSE                = 2147614876
	SCE_KERNEL_ERROR_UNIT_USED                      = 2147614880
	SCE_KERNEL_ERROR_UNIT_NOUSE                     = 2147614881
	SCE_KERNEL_ERROR_NO_ROMDIR                      = 2147614882
	SCE_KERNEL_ERROR_IDTYPE_EXIST                   = 2147614920
	SCE_KERNEL_ERROR_IDTYPE_NOT_EXIST               = 2147614921
	SCE_KERNEL_ERROR_IDTYPE_NOT_EMPTY               = 2147614922
	SCE_KERNEL_ERROR_UNKNOWN_UID                    = 2147614923
	SCE_KERNEL_ERROR_UNMATCH_UID_TYPE               = 2147614924
	SCE_KERNEL_ERROR_ID_NOT_EXIST                   = 2147614925
	SCE_KERNEL_ERROR_NOT_FOUND_UIDFUNC              = 2147614926
	SCE_KERNEL_ERROR_UID_ALREADY_HOLDER             = 2147614927
	SCE_KERNEL_ERROR_UID_NOT_HOLDER                 = 2147614928
	SCE_KERNEL_ERROR_ILLEGAL_PERM                   = 2147614929
	SCE_KERNEL_ERROR_ILLEGAL_ARGUMENT               = 2147614930
	SCE_KERNEL_ERROR_ILLEGAL_ADDR                   = 2147614931
	SCE_KERNEL_ERROR_OUT_OF_RANGE                   = 2147614932
	SCE_KERNEL_ERROR_MEM_RANGE_OVERLAP              = 2147614933
	SCE_KERNEL_ERROR_ILLEGAL_PARTITION              = 2147614934
	SCE_KERNEL_ERROR_PARTITION_INUSE                = 2147614935
	SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCKTYPE           = 2147614936
	SCE_KERNEL_ERROR_MEMBLOCK_ALLOC_FAILED          = 2147614937
	SCE_KERNEL_ERROR_MEMBLOCK_RESIZE_LOCKED         = 2147614938
	SCE_KERNEL_ERROR_MEMBLOCK_RESIZE_FAILED         = 2147614939
	SCE_KERNEL_ERROR_HEAPBLOCK_ALLOC_FAILED         = 2147614940
	SCE_KERNEL_ERROR_HEAP_ALLOC_FAILED              = 2147614941
	SCE_KERNEL_ERROR_ILLEGAL_CHUNK_ID               = 2147614942
	SCE_KERNEL_ERROR_NOCHUNK                        = 2147614943
	SCE_KERNEL_ERROR_NO_FREECHUNK                   = 2147614944
	SCE_KERNEL_ERROR_LINKERR                        = 2147615020
	SCE_KERNEL_ERROR_ILLEGAL_OBJECT                 = 2147615021
	SCE_KERNEL_ERROR_UNKNOWN_MODULE                 = 2147615022
	SCE_KERNEL_ERROR_NOFILE                         = 2147615023
	SCE_KERNEL_ERROR_FILEERR                        = 2147615024
	SCE_KERNEL_ERROR_MEMINUSE                       = 2147615025
	SCE_KERNEL_ERROR_PARTITION_MISMATCH             = 2147615026
	SCE_KERNEL_ERROR_ALREADY_STARTED                = 2147615027
	SCE_KERNEL_ERROR_NOT_STARTED                    = 2147615028
	SCE_KERNEL_ERROR_ALREADY_STOPPED                = 2147615029
	SCE_KERNEL_ERROR_CAN_NOT_STOP                   = 2147615030
	SCE_KERNEL_ERROR_NOT_STOPPED                    = 2147615031
	SCE_KERNEL_ERROR_NOT_REMOVABLE                  = 2147615032
	SCE_KERNEL_ERROR_EXCLUSIVE_LOAD                 = 2147615033
	SCE_KERNEL_ERROR_LIBRARY_NOT_YET_LINKED         = 2147615034
	SCE_KERNEL_ERROR_LIBRARY_FOUND                  = 2147615035
	SCE_KERNEL_ERROR_LIBRARY_NOTFOUND               = 2147615036
	SCE_KERNEL_ERROR_ILLEGAL_LIBRARY                = 2147615037
	SCE_KERNEL_ERROR_LIBRARY_INUSE                  = 2147615038
	SCE_KERNEL_ERROR_ALREADY_STOPPING               = 2147615039
	SCE_KERNEL_ERROR_ILLEGAL_OFFSET                 = 2147615040
	SCE_KERNEL_ERROR_ILLEGAL_POSITION               = 2147615041
	SCE_KERNEL_ERROR_ILLEGAL_ACCESS                 = 2147615042
	SCE_KERNEL_ERROR_MODULE_MGR_BUSY                = 2147615043
	SCE_KERNEL_ERROR_ILLEGAL_FLAG                   = 2147615044
	SCE_KERNEL_ERROR_CANNOT_GET_MODULELIST          = 2147615045
	SCE_KERNEL_ERROR_PROHIBIT_LOADMODULE_DEVICE     = 2147615046
	SCE_KERNEL_ERROR_PROHIBIT_LOADEXEC_DEVICE       = 2147615047
	SCE_KERNEL_ERROR_UNSUPPORTED_PRX_TYPE           = 2147615048
	SCE_KERNEL_ERROR_ILLEGAL_PERM_CALL              = 2147615049
	SCE_KERNEL_ERROR_CANNOT_GET_MODULE_INFORMATION  = 2147615050
	SCE_KERNEL_ERROR_ILLEGAL_LOADEXEC_BUFFER        = 2147615051
	SCE_KERNEL_ERROR_ILLEGAL_LOADEXEC_FILENAME      = 2147615052
	SCE_KERNEL_ERROR_NO_EXIT_CALLBACK               = 2147615053
	SCE_KERNEL_ERROR_NO_MEMORY                      = 2147615120
	SCE_KERNEL_ERROR_ILLEGAL_ATTR                   = 2147615121
	SCE_KERNEL_ERROR_ILLEGAL_ENTRY                  = 2147615122
	SCE_KERNEL_ERROR_ILLEGAL_PRIORITY               = 2147615123
	SCE_KERNEL_ERROR_ILLEGAL_STACK_SIZE             = 2147615124
	SCE_KERNEL_ERROR_ILLEGAL_MODE                   = 2147615125
	SCE_KERNEL_ERROR_ILLEGAL_MASK                   = 2147615126
	SCE_KERNEL_ERROR_ILLEGAL_THID                   = 2147615127
	SCE_KERNEL_ERROR_UNKNOWN_THID                   = 2147615128
	SCE_KERNEL_ERROR_UNKNOWN_SEMID                  = 2147615129
	SCE_KERNEL_ERROR_UNKNOWN_EVFID                  = 2147615130
	SCE_KERNEL_ERROR_UNKNOWN_MBXID                  = 2147615131
	SCE_KERNEL_ERROR_UNKNOWN_VPLID                  = 2147615132
	SCE_KERNEL_ERROR_UNKNOWN_FPLID                  = 2147615133
	SCE_KERNEL_ERROR_UNKNOWN_MPPID                  = 2147615134
	SCE_KERNEL_ERROR_UNKNOWN_ALMID                  = 2147615135
	SCE_KERNEL_ERROR_UNKNOWN_TEID                   = 2147615136
	SCE_KERNEL_ERROR_UNKNOWN_CBID                   = 2147615137
	SCE_KERNEL_ERROR_DORMANT                        = 2147615138
	SCE_KERNEL_ERROR_SUSPEND                        = 2147615139
	SCE_KERNEL_ERROR_NOT_DORMANT                    = 2147615140
	SCE_KERNEL_ERROR_NOT_SUSPEND                    = 2147615141
	SCE_KERNEL_ERROR_NOT_WAIT                       = 2147615142
	SCE_KERNEL_ERROR_CAN_NOT_WAIT                   = 2147615143
	SCE_KERNEL_ERROR_WAIT_TIMEOUT                   = 2147615144
	SCE_KERNEL_ERROR_WAIT_CANCEL                    = 2147615145
	SCE_KERNEL_ERROR_RELEASE_WAIT                   = 2147615146
	SCE_KERNEL_ERROR_NOTIFY_CALLBACK                = 2147615147
	SCE_KERNEL_ERROR_THREAD_TERMINATED              = 2147615148
	SCE_KERNEL_ERROR_SEMA_ZERO                      = 2147615149
	SCE_KERNEL_ERROR_SEMA_OVF                       = 2147615150
	SCE_KERNEL_ERROR_EVF_COND                       = 2147615151
	SCE_KERNEL_ERROR_EVF_MULTI                      = 2147615152
	SCE_KERNEL_ERROR_EVF_ILPAT                      = 2147615153
	SCE_KERNEL_ERROR_MBOX_NOMSG                     = 2147615154
	SCE_KERNEL_ERROR_MPP_FULL                       = 2147615155
	SCE_KERNEL_ERROR_MPP_EMPTY                      = 2147615156
	SCE_KERNEL_ERROR_WAIT_DELETE                    = 2147615157
	SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK               = 2147615158
	SCE_KERNEL_ERROR_ILLEGAL_MEMSIZE                = 2147615159
	SCE_KERNEL_ERROR_ILLEGAL_SPADADDR               = 2147615160
	SCE_KERNEL_ERROR_SPAD_INUSE                     = 2147615161
	SCE_KERNEL_ERROR_SPAD_NOT_INUSE                 = 2147615162
	SCE_KERNEL_ERROR_ILLEGAL_TYPE                   = 2147615163
	SCE_KERNEL_ERROR_ILLEGAL_SIZE                   = 2147615164
	SCE_KERNEL_ERROR_ILLEGAL_COUNT                  = 2147615165
	SCE_KERNEL_ERROR_UNKNOWN_VTID                   = 2147615166
	SCE_KERNEL_ERROR_ILLEGAL_VTID                   = 2147615167
	SCE_KERNEL_ERROR_ILLEGAL_KTLSID                 = 2147615168
	SCE_KERNEL_ERROR_KTLS_FULL                      = 2147615169
	SCE_KERNEL_ERROR_KTLS_BUSY                      = 2147615170
	SCE_KERNEL_ERROR_PM_INVALID_PRIORITY            = 2147615320
	SCE_KERNEL_ERROR_PM_INVALID_DEVNAME             = 2147615321
	SCE_KERNEL_ERROR_PM_UNKNOWN_DEVNAME             = 2147615322
	SCE_KERNEL_ERROR_PM_PMINFO_REGISTERED           = 2147615323
	SCE_KERNEL_ERROR_PM_PMINFO_UNREGISTERED         = 2147615324
	SCE_KERNEL_ERROR_PM_INVALID_MAJOR_STATE         = 2147615325
	SCE_KERNEL_ERROR_PM_INVALID_REQUEST             = 2147615326
	SCE_KERNEL_ERROR_PM_UNKNOWN_REQUEST             = 2147615327
	SCE_KERNEL_ERROR_PM_INVALID_UNIT                = 2147615328
	SCE_KERNEL_ERROR_PM_CANNOT_CANCEL               = 2147615329
	SCE_KERNEL_ERROR_PM_INVALID_PMINFO              = 2147615330
	SCE_KERNEL_ERROR_PM_INVALID_ARGUMENT            = 2147615331
	SCE_KERNEL_ERROR_PM_ALREADY_TARGET_PWRSTATE     = 2147615332
	SCE_KERNEL_ERROR_PM_CHANGE_PWRSTATE_FAILED      = 2147615333
	SCE_KERNEL_ERROR_PM_CANNOT_CHANGE_DEVPWR_STATE  = 2147615334
	SCE_KERNEL_ERROR_PM_NO_SUPPORT_DEVPWR_STATE     = 2147615335
	SCE_KERNEL_ERROR_DMAC_REQUEST_FAILED            = 2147615420
	SCE_KERNEL_ERROR_DMAC_REQUEST_DENIED            = 2147615421
	SCE_KERNEL_ERROR_DMAC_OP_QUEUED                 = 2147615422
	SCE_KERNEL_ERROR_DMAC_OP_NOT_QUEUED             = 2147615423
	SCE_KERNEL_ERROR_DMAC_OP_RUNNING                = 2147615424
	SCE_KERNEL_ERROR_DMAC_OP_NOT_ASSIGNED           = 2147615425
	SCE_KERNEL_ERROR_DMAC_OP_TIMEOUT                = 2147615426
	SCE_KERNEL_ERROR_DMAC_OP_FREED                  = 2147615427
	SCE_KERNEL_ERROR_DMAC_OP_USED                   = 2147615428
	SCE_KERNEL_ERROR_DMAC_OP_EMPTY                  = 2147615429
	SCE_KERNEL_ERROR_DMAC_OP_ABORTED                = 2147615430
	SCE_KERNEL_ERROR_DMAC_OP_ERROR                  = 2147615431
	SCE_KERNEL_ERROR_DMAC_CHANNEL_RESERVED          = 2147615432
	SCE_KERNEL_ERROR_DMAC_CHANNEL_EXCLUDED          = 2147615433
	SCE_KERNEL_ERROR_DMAC_PRIVILEGE_ADDRESS         = 2147615434
	SCE_KERNEL_ERROR_DMAC_NO_ENOUGHSPACE            = 2147615435
	SCE_KERNEL_ERROR_DMAC_CHANNEL_NOT_ASSIGNED      = 2147615436
	SCE_KERNEL_ERROR_DMAC_CHILD_OPERATION           = 2147615437
	SCE_KERNEL_ERROR_DMAC_TOO_MUCH_SIZE             = 2147615438
	SCE_KERNEL_ERROR_DMAC_INVALID_ARGUMENT          = 2147615439
	SCE_KERNEL_ERROR_MFILE                          = 2147615520
	SCE_KERNEL_ERROR_NODEV                          = 2147615521
	SCE_KERNEL_ERROR_XDEV                           = 2147615522
	SCE_KERNEL_ERROR_BADF                           = 2147615523
	SCE_KERNEL_ERROR_INVAL                          = 2147615524
	SCE_KERNEL_ERROR_UNSUP                          = 2147615525
	SCE_KERNEL_ERROR_ALIAS_USED                     = 2147615526
	SCE_KERNEL_ERROR_CANNOT_MOUNT                   = 2147615527
	SCE_KERNEL_ERROR_DRIVER_DELETED                 = 2147615528
	SCE_KERNEL_ERROR_ASYNC_BUSY                     = 2147615529
	SCE_KERNEL_ERROR_NOASYNC                        = 2147615530
	SCE_KERNEL_ERROR_REGDEV                         = 2147615531
	SCE_KERNEL_ERROR_NOCWD                          = 2147615532
	SCE_KERNEL_ERROR_NAMETOOLONG                    = 2147615533
	SCE_KERNEL_ERROR_NXIO                           = 2147615720
	SCE_KERNEL_ERROR_IO                             = 2147615721
	SCE_KERNEL_ERROR_NOMEM                          = 2147615722
	SCE_KERNEL_ERROR_STDIO_NOT_OPENED               = 2147615723
	SCE_KERNEL_ERROR_CACHE_ALIGNMENT                = 2147615820
	SCE_KERNEL_ERROR_ERRORMAX                       = 2147615821
	PSP_GPIO_INT                                    = 4
	PSP_ATA_INT                                     = 5
	PSP_UMD_INT                                     = 6
	PSP_MSCM0_INT                                   = 7
	PSP_WLAN_INT                                    = 8
	PSP_AUDIO_INT                                   = 10
	PSP_I2C_INT                                     = 12
	PSP_SIRCS_INT                                   = 14
	PSP_SYSTIMER0_INT                               = 15
	PSP_SYSTIMER1_INT                               = 16
	PSP_SYSTIMER2_INT                               = 17
	PSP_SYSTIMER3_INT                               = 18
	PSP_THREAD0_INT                                 = 19
	PSP_NAND_INT                                    = 20
	PSP_DMACPLUS_INT                                = 21
	PSP_DMA0_INT                                    = 22
	PSP_DMA1_INT                                    = 23
	PSP_MEMLMD_INT                                  = 24
	PSP_GE_INT                                      = 25
	PSP_VBLANK_INT                                  = 30
	PSP_MECODEC_INT                                 = 31
	PSP_HPREMOTE_INT                                = 36
	PSP_MSCM1_INT                                   = 60
	PSP_MSCM2_INT                                   = 61
	PSP_THREAD1_INT                                 = 65
	PSP_INTERRUPT_INT                               = 66
	PSP_GPIO_SUBINT                                 = 4
	PSP_ATA_SUBINT                                  = 5
	PSP_UMD_SUBINT                                  = 6
	PSP_DMACPLUS_SUBINT                             = 21
	PSP_GE_SUBINT                                   = 25
	PSP_DISPLAY_SUBINT                              = 30
	PSP_BOOT_FLASH                                  = 0
	PSP_BOOT_DISC                                   = 32
	PSP_BOOT_USBWLAN                                = 48
	PSP_BOOT_MS                                     = 64
	PSP_BOOT_EF                                     = 80
	PSP_BOOT_FLASH3                                 = 128
	PSP_INIT_APITYPE_KERNEL                         = 0
	PSP_INIT_APITYPE_BUFFER_KERNEL                  = 2
	PSP_INIT_APITYPE_KERNEL_BLOCK                   = 3
	PSP_INIT_APITYPE_USER                           = 16
	PSP_INIT_APITYPE_DNAS                           = 19
	PSP_INIT_APITYPE_NPDRM                          = 20
	PSP_INIT_APITYPE_VSH                            = 32
	PSP_INIT_APITYPE_BUFFER_VSH                     = 33
	PSP_INIT_APITYPE_BUFFER_USBWLAN                 = 48
	PSP_INIT_APITYPE_BUFFER_MS                      = 66
	PSP_INIT_APITYPE_BUFFER_APP                     = 67
	PSP_INIT_APITYPE_BUFFER_BOOT_INIT_BTCNF         = 81
	PSP_INIT_APITYPE_BUFFER_BOOT_INIT_CONFIG        = 82
	PSP_INIT_APITYPE_BUFFER_DECI                    = 112
	PSP_INIT_APITYPE_GAME_EBOOT                     = 272
	PSP_INIT_APITYPE_GAME_BOOT                      = 273
	PSP_INIT_APITYPE_EMU_EBOOT_MS                   = 274
	PSP_INIT_APITYPE_EMU_BOOT_MS                    = 275
	PSP_INIT_APITYPE_EMU_EBOOT_EF                   = 276
	PSP_INIT_APITYPE_EMU_BOOT_EF                    = 277
	PSP_INIT_APITYPE_NPDRM_MS                       = 278
	PSP_INIT_APITYPE_UNK117                         = 279
	PSP_INIT_APITYPE_NPDRM_EF                       = 280
	PSP_INIT_APITYPE_UNK119                         = 281
	PSP_INIT_APITYPE_UMD                            = 288
	PSP_INIT_APITYPE_UMD_UPDATER                    = 289
	PSP_INIT_APITYPE_UMD_DEBUG                      = 290
	PSP_INIT_APITYPE_UMD_EMU_MS1                    = 291
	PSP_INIT_APITYPE_UMD_EMU_MS2                    = 292
	PSP_INIT_APITYPE_UMD_EMU_EF1                    = 293
	PSP_INIT_APITYPE_UMD_EMU_EF2                    = 294
	PSP_INIT_APITYPE_USBWLAN                        = 304
	PSP_INIT_APITYPE_USBWLAN_DEBUG                  = 305
	PSP_INIT_APITYPE_MS1                            = 320
	PSP_INIT_APITYPE_MS2                            = 321
	PSP_INIT_APITYPE_MS3                            = 322
	PSP_INIT_APITYPE_MS4                            = 323
	PSP_INIT_APITYPE_MS5                            = 324
	PSP_INIT_APITYPE_MS6                            = 325
	PSP_INIT_APITYPE_EF1                            = 337
	PSP_INIT_APITYPE_EF2                            = 338
	PSP_INIT_APITYPE_EF3                            = 339
	PSP_INIT_APITYPE_EF4                            = 340
	PSP_INIT_APITYPE_EF5                            = 341
	PSP_INIT_APITYPE_EF6                            = 342
	PSP_INIT_APITYPE_UMD2                           = 352
	PSP_INIT_APITYPE_UNK161                         = 353
	PSP_INIT_APITYPE_MLNAPP_MS                      = 368
	PSP_INIT_APITYPE_MLNAPP_EF                      = 369
	PSP_INIT_APITYPE_VSH_KERNEL                     = 512
	PSP_INIT_APITYPE_VSH1                           = 528
	PSP_INIT_APITYPE_VSH2                           = 544
	PSP_INIT_APITYPE_KERNEL_REBOOT                  = 768
	PSP_INIT_APITYPE_DEBUG                          = 1056
	PSP_INIT_APITYPE_DISC                           = 288
	PSP_INIT_APITYPE_DISC2                          = 352
	PSP_INIT_APITYPE_DISC_UPDATER                   = 289
	PSP_INIT_APITYPE_DISC_DEBUG                     = 290
	PSP_INIT_APITYPE_DISC_EMU_MS1                   = 291
	PSP_INIT_APITYPE_DISC_EMU_MS2                   = 292
	PSP_INIT_APITYPE_DISC_EMU_EF1                   = 293
	PSP_INIT_APITYPE_DISC_EMU_EF2                   = 294
	PSP_INIT_APITYPE_MS_UPDATER                     = 320
	PSP_INIT_APITYPE_MS_GAME                        = 321
	PSP_INIT_APITYPE_MS_APP                         = 323
	PSP_INIT_APITYPE_MS_PS1                         = 324
	PSP_INIT_APITYPE_EF_UPDATER                     = 337
	PSP_INIT_APITYPE_EF_GAME                        = 338
	PSP_INIT_APITYPE_EF_APP                         = 340
	PSP_INIT_APITYPE_EF_PS1                         = 341
	PSP_INIT_APITYPE_VSH_EXITGAME                   = 528
	PSP_INIT_APITYPE_VSH_EXITVSH                    = 544
	PSP_INIT_KEYCONFIG_VSH                          = 256
	PSP_INIT_KEYCONFIG_UPDATER                      = 272
	PSP_INIT_KEYCONFIG_GAME                         = 512
	PSP_INIT_KEYCONFIG_POPS                         = 768
	PSP_INIT_KEYCONFIG_APP                          = 1024
	PSP_1000                                        = 0
	PSP_2000                                        = 1
	PSP_3000                                        = 2
	PSP_4000                                        = 3
	PSP_GO                                          = 4
	PSP_7000                                        = 6
	PSP_9000                                        = 8
	PSP_11000                                       = 10
	BOOTLOAD_VSH                                    = 1
	BOOTLOAD_GAME                                   = 2
	BOOTLOAD_UPDATER                                = 4
	BOOTLOAD_POPS                                   = 8
	BOOTLOAD_UMDEMU                                 = 64
	PSP_TOOLKIT_TYPE_RETAIL                         = 0
	PSP_TOOLKIT_TYPE_TEST                           = 1
	PSP_TOOLKIT_TYPE_DEV                            = 2
)

//go:linkname SctrlHENFindJALGeneric sctrlHENFindJALGeneric
func SctrlHENFindJALGeneric(addr uint32, reversed int32, skip int32) int32

//go:linkname SctrlHENFindFirstBEQ sctrlHENFindFirstBEQ
func SctrlHENFindFirstBEQ(addr uint32) int32

//go:linkname SctrlHENFindRefInGlobals sctrlHENFindRefInGlobals
func SctrlHENFindRefInGlobals(libname unsafe.Pointer, addr uint32, ptr uint32) int32

//go:linkname SctrlHENIsSystemBooted sctrlHENIsSystemBooted
func SctrlHENIsSystemBooted() int32

//go:linkname SctrlFindImportLib sctrlFindImportLib
func SctrlFindImportLib(mod unsafe.Pointer, library unsafe.Pointer) unsafe.Pointer

//go:linkname SctrlFindImportByNID sctrlFindImportByNID
func SctrlFindImportByNID(pMod unsafe.Pointer, library unsafe.Pointer, nid uint32) int32

//go:linkname SctrlHookImportByNID sctrlHookImportByNID
func SctrlHookImportByNID(mod unsafe.Pointer, library unsafe.Pointer, nid uint32, funcValue unsafe.Pointer) int32

//go:linkname SctrlKernelRand sctrlKernelRand
func SctrlKernelRand() int32

//go:linkname SctrlSetStartModuleExtra sctrlSetStartModuleExtra
func SctrlSetStartModuleExtra(funcValue unsafe.Pointer) unsafe.Pointer

//go:linkname SctrlGetSfoPARAM sctrlGetSfoPARAM
func SctrlGetSfoPARAM(sfo_path unsafe.Pointer, paramName unsafe.Pointer, paramType unsafe.Pointer, paramLength unsafe.Pointer, paramBuffer unsafe.Pointer) int32

//go:linkname SctrlGetInitPARAM sctrlGetInitPARAM
func SctrlGetInitPARAM(paramName unsafe.Pointer, paramType unsafe.Pointer, paramLength unsafe.Pointer, paramBuffer unsafe.Pointer) int32

//go:linkname SctrlGetThreadUIDByName sctrlGetThreadUIDByName
func SctrlGetThreadUIDByName(name unsafe.Pointer) int32

//go:linkname SctrlGetThreadContextByUID sctrlGetThreadContextByUID
func SctrlGetThreadContextByUID(uid int32, ctx unsafe.Pointer) int32

//go:linkname SctrlGetThreadContextByName sctrlGetThreadContextByName
func SctrlGetThreadContextByName(name unsafe.Pointer, ctx unsafe.Pointer) int32

//go:linkname SctrlFlushCache sctrlFlushCache
func SctrlFlushCache()

//go:linkname SctrlHENSetPSXVramHandler sctrlHENSetPSXVramHandler
func SctrlHENSetPSXVramHandler(handler unsafe.Pointer) unsafe.Pointer

//go:linkname SctrlDeflateDecompress sctrlDeflateDecompress
func SctrlDeflateDecompress(dest unsafe.Pointer, src unsafe.Pointer, size int32) int32

//go:linkname SctrlGzipDecompress sctrlGzipDecompress
func SctrlGzipDecompress(dest unsafe.Pointer, src unsafe.Pointer, size int32) int32

//go:linkname LZ4_decompress_fast LZ4_decompress_fast
func LZ4_decompress_fast(source unsafe.Pointer, dest unsafe.Pointer, outputSize int32) int32

//go:linkname Lzo1x_decompress lzo1x_decompress
func Lzo1x_decompress(source unsafe.Pointer, src_len uint32, dest unsafe.Pointer, dst_len unsafe.Pointer, unused unsafe.Pointer) int32

//go:linkname SctrlKernelMsIsEf sctrlKernelMsIsEf
func SctrlKernelMsIsEf() int32

//go:linkname SctrlKernelExitVSH sctrlKernelExitVSH
func SctrlKernelExitVSH(param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHDisc sctrlKernelLoadExecVSHDisc
func SctrlKernelLoadExecVSHDisc(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHDiscUpdater sctrlKernelLoadExecVSHDiscUpdater
func SctrlKernelLoadExecVSHDiscUpdater(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHMs1 sctrlKernelLoadExecVSHMs1
func SctrlKernelLoadExecVSHMs1(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHMs2 sctrlKernelLoadExecVSHMs2
func SctrlKernelLoadExecVSHMs2(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHEf2 sctrlKernelLoadExecVSHEf2
func SctrlKernelLoadExecVSHEf2(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHMs3 sctrlKernelLoadExecVSHMs3
func SctrlKernelLoadExecVSHMs3(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHMs4 sctrlKernelLoadExecVSHMs4
func SctrlKernelLoadExecVSHMs4(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelLoadExecVSHWithApitype sctrlKernelLoadExecVSHWithApitype
func SctrlKernelLoadExecVSHWithApitype(apitype int32, file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SctrlKernelSetInitApitype sctrlKernelSetInitApitype
func SctrlKernelSetInitApitype(apitype int32) int32

//go:linkname SctrlKernelSetInitFileName sctrlKernelSetInitFileName
func SctrlKernelSetInitFileName(filename unsafe.Pointer) int32

//go:linkname SctrlKernelSetApplicationType sctrlKernelSetApplicationType
func SctrlKernelSetApplicationType(key int32) int32

//go:linkname SctrlKernelSetInitKeyConfig sctrlKernelSetInitKeyConfig
func SctrlKernelSetInitKeyConfig(key int32) int32

//go:linkname SctrlKernelSetUserLevel sctrlKernelSetUserLevel
func SctrlKernelSetUserLevel(level int32) int32

//go:linkname SctrlKernelSetDevkitVersion sctrlKernelSetDevkitVersion
func SctrlKernelSetDevkitVersion(version int32) int32

//go:linkname SctrlHENIsSE sctrlHENIsSE
func SctrlHENIsSE() int32

//go:linkname SctrlHENIsDevhook sctrlHENIsDevhook
func SctrlHENIsDevhook() int32

//go:linkname SctrlHENGetVersion sctrlHENGetVersion
func SctrlHENGetVersion() int32

//go:linkname SctrlHENGetMinorVersion sctrlHENGetMinorVersion
func SctrlHENGetMinorVersion() int32

//go:linkname SctrlHENIsToolKit sctrlHENIsToolKit
func SctrlHENIsToolKit() int32

//go:linkname SctrlHENFindDriver sctrlHENFindDriver
func SctrlHENFindDriver(drvname unsafe.Pointer) unsafe.Pointer

//go:linkname SctrlHENFindFunction sctrlHENFindFunction
func SctrlHENFindFunction(mod_name unsafe.Pointer, library unsafe.Pointer, nid uint32) int32

//go:linkname SctrlHENFindFunctionInMod sctrlHENFindFunctionInMod
func SctrlHENFindFunctionInMod(mod unsafe.Pointer, library unsafe.Pointer, nid uint32) int32

//go:linkname SctrlHENFindFunctionOnSystem sctrlHENFindFunctionOnSystem
func SctrlHENFindFunctionOnSystem(libname unsafe.Pointer, nid uint32, user_mods_only int32) int32

//go:linkname SctrlHENFindImport sctrlHENFindImport
func SctrlHENFindImport(mod_name unsafe.Pointer, library unsafe.Pointer, nid uint32) int32

//go:linkname SctrlHENFindImportInMod sctrlHENFindImportInMod
func SctrlHENFindImportInMod(mod unsafe.Pointer, libname unsafe.Pointer, nid uint32) int32

//go:linkname SctrlHENHijackFunction sctrlHENHijackFunction
func SctrlHENHijackFunction(patch_data unsafe.Pointer, func_addr unsafe.Pointer, patch_func unsafe.Pointer, orig_func unsafe.Pointer)

//go:linkname SctrlHENSetStartModuleHandler sctrlHENSetStartModuleHandler
func SctrlHENSetStartModuleHandler(new_handler unsafe.Pointer) int32

//go:linkname SctrlHENMakeSyscallStub sctrlHENMakeSyscallStub
func SctrlHENMakeSyscallStub(function unsafe.Pointer) int32

//go:linkname SctrlHENSetSpeed sctrlHENSetSpeed
func SctrlHENSetSpeed(cpu int32, bus int32)

//go:linkname SctrlHENSetMemory sctrlHENSetMemory
func SctrlHENSetMemory(p2 uint32, p8_or_p11 uint32) int32

//go:linkname SctrlHENApplyMemory sctrlHENApplyMemory
func SctrlHENApplyMemory(p2 uint32) int32

//go:linkname SctrlKernelQuerySystemCall sctrlKernelQuerySystemCall
func SctrlKernelQuerySystemCall(func_addr unsafe.Pointer) int32

//go:linkname SctrlKernelBootFrom sctrlKernelBootFrom
func SctrlKernelBootFrom() int32

//go:linkname SctrlHENPatchSyscall sctrlHENPatchSyscall
func SctrlHENPatchSyscall(addr unsafe.Pointer, newaddr unsafe.Pointer)

//go:linkname SctrlPatchModule sctrlPatchModule
func SctrlPatchModule(mod_name unsafe.Pointer, inst uint32, offset uint32) int32

//go:linkname SctrlModuleTextAddr sctrlModuleTextAddr
func SctrlModuleTextAddr(mod_name unsafe.Pointer) int32

//go:linkname SctrlGetInitTextAddr sctrlGetInitTextAddr
func SctrlGetInitTextAddr() int32

//go:linkname SctrlSetCustomStartModule sctrlSetCustomStartModule
func SctrlSetCustomStartModule(funcValue unsafe.Pointer)

//go:linkname SctrlHENLoadModuleOnReboot sctrlHENLoadModuleOnReboot
func SctrlHENLoadModuleOnReboot(module_after unsafe.Pointer, buf unsafe.Pointer, size int32, flags int32)

//go:linkname SctrlHENSetRebootexOverride sctrlHENSetRebootexOverride
func SctrlHENSetRebootexOverride(rebootex unsafe.Pointer)

//go:linkname SctrlKernelSetNidResolver sctrlKernelSetNidResolver
func SctrlKernelSetNidResolver(libname unsafe.Pointer, enabled uint32) int32

//go:linkname SctrlGetRealEthernetAddress sctrlGetRealEthernetAddress
func SctrlGetRealEthernetAddress(mac unsafe.Pointer) int32

//go:linkname SctrlHENGetRebootexConfig sctrlHENGetRebootexConfig
func SctrlHENGetRebootexConfig(arg0 unsafe.Pointer) unsafe.Pointer

//go:linkname SctrlKernelResolveNid sctrlKernelResolveNid
func SctrlKernelResolveNid(libName unsafe.Pointer, nid uint32) int32
