// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnand_driver.h

// Package nand_driver provides direct TinyGo bindings for pspnand_driver.h.
package nand_driver

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspnandDriver() }

//go:linkname requirePspnandDriver pspsdk_go_require_pspnand_driver
func requirePspnandDriver()

//go:linkname SceNandSetWriteProtect sceNandSetWriteProtect
func SceNandSetWriteProtect(protectFlag int32) int32

//go:linkname SceNandLock sceNandLock
func SceNandLock(writeFlag int32) int32

//go:linkname SceNandUnlock sceNandUnlock
func SceNandUnlock()

//go:linkname SceNandReadStatus sceNandReadStatus
func SceNandReadStatus() int32

//go:linkname SceNandReset sceNandReset
func SceNandReset(flag int32) int32

//go:linkname SceNandReadId sceNandReadId
func SceNandReadId(buf unsafe.Pointer, size uint32) int32

//go:linkname SceNandReadPages sceNandReadPages
func SceNandReadPages(ppn uint32, buf unsafe.Pointer, buf2 unsafe.Pointer, count uint32) int32

//go:linkname SceNandReadPagesRawAll sceNandReadPagesRawAll
func SceNandReadPagesRawAll(ppn uint32, buf unsafe.Pointer, spare unsafe.Pointer, count uint32) int32

//go:linkname SceNandEraseBlock sceNandEraseBlock
func SceNandEraseBlock(ppn uint32) int32

//go:linkname SceNandWriteAccess sceNandWriteAccess
func SceNandWriteAccess(ppn uint32, buf unsafe.Pointer, spare unsafe.Pointer, arg3 int32, arg4 uint32) int32

//go:linkname SceNandReadExtraOnly sceNandReadExtraOnly
func SceNandReadExtraOnly(ppn uint32, buf unsafe.Pointer, arg2 int32) int32

//go:linkname SceNandGetPageSize sceNandGetPageSize
func SceNandGetPageSize() int32

//go:linkname SceNandGetPagesPerBlock sceNandGetPagesPerBlock
func SceNandGetPagesPerBlock() int32

//go:linkname SceNandGetTotalBlocks sceNandGetTotalBlocks
func SceNandGetTotalBlocks() int32

//go:linkname SceNandWriteBlockWithVerify sceNandWriteBlockWithVerify
func SceNandWriteBlockWithVerify(ppn uint32, buf unsafe.Pointer, spare unsafe.Pointer) int32

//go:linkname SceNandReadBlockWithRetry sceNandReadBlockWithRetry
func SceNandReadBlockWithRetry(ppn uint32, buf unsafe.Pointer, buf2 unsafe.Pointer) int32

//go:linkname SceNandEraseBlockWithRetry sceNandEraseBlockWithRetry
func SceNandEraseBlockWithRetry(ppn uint32) int32

//go:linkname SceNandIsBadBlock sceNandIsBadBlock
func SceNandIsBadBlock(ppn uint32) int32
