// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspidstorage.h

// Package idstorage provides direct TinyGo bindings for pspidstorage.h.
package idstorage

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceIdStorageLookup sceIdStorageLookup
func SceIdStorageLookup(key uint16, offset uint32, buf unsafe.Pointer, len uint32) int32

//go:linkname SceIdStorageReadLeaf sceIdStorageReadLeaf
func SceIdStorageReadLeaf(key uint16, buf unsafe.Pointer) int32

//go:linkname SceIdStorageWriteLeaf sceIdStorageWriteLeaf
func SceIdStorageWriteLeaf(key uint16, buf unsafe.Pointer) int32

//go:linkname SceIdStorageIsReadOnly sceIdStorageIsReadOnly
func SceIdStorageIsReadOnly() int32

//go:linkname SceIdStorageFlush sceIdStorageFlush
func SceIdStorageFlush() int32

//go:linkname SceIdStorageCreateLeaf sceIdStorageCreateLeaf
func SceIdStorageCreateLeaf(leafid uint32) int32

//go:linkname SceIdStorageCreateAtomicLeaves sceIdStorageCreateAtomicLeaves
func SceIdStorageCreateAtomicLeaves(leaves unsafe.Pointer, n int32) int32

//go:linkname SceIdStorageFormat sceIdStorageFormat
func SceIdStorageFormat() int32

//go:linkname SceIdStorageUnformat sceIdStorageUnformat
func SceIdStorageUnformat() int32
