// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmodulemgr.h

// Package modulemgr provides direct TinyGo bindings for pspmodulemgr.h.
package modulemgr

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelLoadModule sceKernelLoadModule
func SceKernelLoadModule(path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleMs sceKernelLoadModuleMs
func SceKernelLoadModuleMs(path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleMs2 sceKernelLoadModuleMs2
func SceKernelLoadModuleMs2(apitype int32, path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleByID sceKernelLoadModuleByID
func SceKernelLoadModuleByID(fid int32, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleBufferUsbWlan sceKernelLoadModuleBufferUsbWlan
func SceKernelLoadModuleBufferUsbWlan(bufsize uint32, buf unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelStartModule sceKernelStartModule
func SceKernelStartModule(modid int32, argsize uint32, argp unsafe.Pointer, status unsafe.Pointer, option unsafe.Pointer) int32

//go:linkname SceKernelStopModule sceKernelStopModule
func SceKernelStopModule(modid int32, argsize uint32, argp unsafe.Pointer, status unsafe.Pointer, option unsafe.Pointer) int32

//go:linkname SceKernelUnloadModule sceKernelUnloadModule
func SceKernelUnloadModule(modid int32) int32

//go:linkname SceKernelSelfStopUnloadModule sceKernelSelfStopUnloadModule
func SceKernelSelfStopUnloadModule(unknown int32, argsize uint32, argp unsafe.Pointer) int32

//go:linkname SceKernelStopUnloadSelfModule sceKernelStopUnloadSelfModule
func SceKernelStopUnloadSelfModule(argsize uint32, argp unsafe.Pointer, status unsafe.Pointer, option unsafe.Pointer) int32

//go:linkname SceKernelQueryModuleInfo sceKernelQueryModuleInfo
func SceKernelQueryModuleInfo(modid int32, info unsafe.Pointer) int32

//go:linkname SceKernelGetModuleIdList sceKernelGetModuleIdList
func SceKernelGetModuleIdList(readbuf unsafe.Pointer, readbufsize int32, idcount unsafe.Pointer) int32

//go:linkname SceKernelGetModuleIdByAddress sceKernelGetModuleIdByAddress
func SceKernelGetModuleIdByAddress(moduleAddr unsafe.Pointer) int32
