// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspdisplay_kernel.h

// Package display_kernel provides direct TinyGo bindings for pspdisplay_kernel.h.
package display_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspdisplayDriver() }

//go:linkname requirePspdisplayDriver pspsdk_go_require_pspdisplay_driver
func requirePspdisplayDriver()

//go:linkname SceDisplay_driver_63E22A26 sceDisplay_driver_63E22A26
func SceDisplay_driver_63E22A26(pri int32, topaddr unsafe.Pointer, bufferwidth int32, pixelformat int32, sync int32) int32

//go:linkname SceDisplay_driver_5B5AEFAD sceDisplay_driver_5B5AEFAD
func SceDisplay_driver_5B5AEFAD(pri int32, topaddr unsafe.Pointer, bufferwidth unsafe.Pointer, pixelformat unsafe.Pointer, sync unsafe.Pointer) int32

//go:linkname SceDisplaySetBrightness sceDisplaySetBrightness
func SceDisplaySetBrightness(level int32, unk1 int32)

//go:linkname SceDisplayGetBrightness sceDisplayGetBrightness
func SceDisplayGetBrightness(level unsafe.Pointer, unk1 unsafe.Pointer)
