// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspusbcam.h

// Package usbcam provides direct TinyGo bindings for pspusbcam.h.
package usbcam

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_USBCAM_RESOLUTION_160_120     = 0
	PSP_USBCAM_RESOLUTION_176_144     = 1
	PSP_USBCAM_RESOLUTION_320_240     = 2
	PSP_USBCAM_RESOLUTION_352_288     = 3
	PSP_USBCAM_RESOLUTION_640_480     = 4
	PSP_USBCAM_RESOLUTION_1024_768    = 5
	PSP_USBCAM_RESOLUTION_1280_960    = 6
	PSP_USBCAM_RESOLUTION_480_272     = 7
	PSP_USBCAM_RESOLUTION_360_272     = 8
	PSP_USBCAM_RESOLUTION_EX_160_120  = 0
	PSP_USBCAM_RESOLUTION_EX_176_144  = 1
	PSP_USBCAM_RESOLUTION_EX_320_240  = 2
	PSP_USBCAM_RESOLUTION_EX_352_288  = 3
	PSP_USBCAM_RESOLUTION_EX_360_272  = 4
	PSP_USBCAM_RESOLUTION_EX_480_272  = 5
	PSP_USBCAM_RESOLUTION_EX_640_480  = 6
	PSP_USBCAM_RESOLUTION_EX_1024_768 = 7
	PSP_USBCAM_RESOLUTION_EX_1280_960 = 8
	PSP_USBCAM_FLIP                   = 1
	PSP_USBCAM_MIRROR                 = 256
	PSP_USBCAM_NODELAY                = 0
	PSP_USBCAM_DELAY_10SEC            = 1
	PSP_USBCAM_DELAY_20SEC            = 2
	PSP_USBCAM_DELAY_30SEC            = 3
	PSP_USBCAM_FRAMERATE_3_75_FPS     = 0
	PSP_USBCAM_FRAMERATE_5_FPS        = 1
	PSP_USBCAM_FRAMERATE_7_5_FPS      = 2
	PSP_USBCAM_FRAMERATE_10_FPS       = 3
	PSP_USBCAM_FRAMERATE_15_FPS       = 4
	PSP_USBCAM_FRAMERATE_20_FPS       = 5
	PSP_USBCAM_FRAMERATE_30_FPS       = 6
	PSP_USBCAM_FRAMERATE_60_FPS       = 7
	PSP_USBCAM_WB_AUTO                = 0
	PSP_USBCAM_WB_DAYLIGHT            = 1
	PSP_USBCAM_WB_FLUORESCENT         = 2
	PSP_USBCAM_WB_INCADESCENT         = 3
	PSP_USBCAM_EFFECTMODE_NORMAL      = 0
	PSP_USBCAM_EFFECTMODE_NEGATIVE    = 1
	PSP_USBCAM_EFFECTMODE_BLACKWHITE  = 2
	PSP_USBCAM_EFFECTMODE_SEPIA       = 3
	PSP_USBCAM_EFFECTMODE_BLUE        = 4
	PSP_USBCAM_EFFECTMODE_RED         = 5
	PSP_USBCAM_EFFECTMODE_GREEN       = 6
	PSP_USBCAM_EVLEVEL_2_0_POSITIVE   = 0
	PSP_USBCAM_EVLEVEL_1_7_POSITIVE   = 1
	PSP_USBCAM_EVLEVEL_1_5_POSITIVE   = 2
	PSP_USBCAM_EVLEVEL_1_3_POSITIVE   = 3
	PSP_USBCAM_EVLEVEL_1_0_POSITIVE   = 4
	PSP_USBCAM_EVLEVEL_0_7_POSITIVE   = 5
	PSP_USBCAM_EVLEVEL_0_5_POSITIVE   = 6
	PSP_USBCAM_EVLEVEL_0_3_POSITIVE   = 7
	PSP_USBCAM_EVLEVEL_0_0            = 8
	PSP_USBCAM_EVLEVEL_0_3_NEGATIVE   = 9
	PSP_USBCAM_EVLEVEL_0_5_NEGATIVE   = 10
	PSP_USBCAM_EVLEVEL_0_7_NEGATIVE   = 11
	PSP_USBCAM_EVLEVEL_1_0_NEGATIVE   = 12
	PSP_USBCAM_EVLEVEL_1_3_NEGATIVE   = 13
	PSP_USBCAM_EVLEVEL_1_5_NEGATIVE   = 14
	PSP_USBCAM_EVLEVEL_1_7_NEGATIVE   = 15
	PSP_USBCAM_EVLEVEL_2_0_NEGATIVE   = 16
)

//go:linkname SceUsbCamSetupStill sceUsbCamSetupStill
func SceUsbCamSetupStill(param unsafe.Pointer) int32

//go:linkname SceUsbCamSetupStillEx sceUsbCamSetupStillEx
func SceUsbCamSetupStillEx(param unsafe.Pointer) int32

//go:linkname SceUsbCamStillInputBlocking sceUsbCamStillInputBlocking
func SceUsbCamStillInputBlocking(buf unsafe.Pointer, size uint32) int32

//go:linkname SceUsbCamStillInput sceUsbCamStillInput
func SceUsbCamStillInput(buf unsafe.Pointer, size uint32) int32

//go:linkname SceUsbCamStillWaitInputEnd sceUsbCamStillWaitInputEnd
func SceUsbCamStillWaitInputEnd() int32

//go:linkname SceUsbCamStillPollInputEnd sceUsbCamStillPollInputEnd
func SceUsbCamStillPollInputEnd() int32

//go:linkname SceUsbCamStillCancelInput sceUsbCamStillCancelInput
func SceUsbCamStillCancelInput() int32

//go:linkname SceUsbCamStillGetInputLength sceUsbCamStillGetInputLength
func SceUsbCamStillGetInputLength() int32

//go:linkname SceUsbCamSetupVideo sceUsbCamSetupVideo
func SceUsbCamSetupVideo(param unsafe.Pointer, workarea unsafe.Pointer, wasize int32) int32

//go:linkname SceUsbCamSetupVideoEx sceUsbCamSetupVideoEx
func SceUsbCamSetupVideoEx(param unsafe.Pointer, workarea unsafe.Pointer, wasize int32) int32

//go:linkname SceUsbCamStartVideo sceUsbCamStartVideo
func SceUsbCamStartVideo() int32

//go:linkname SceUsbCamStopVideo sceUsbCamStopVideo
func SceUsbCamStopVideo() int32

//go:linkname SceUsbCamReadVideoFrameBlocking sceUsbCamReadVideoFrameBlocking
func SceUsbCamReadVideoFrameBlocking(buf unsafe.Pointer, size uint32) int32

//go:linkname SceUsbCamReadVideoFrame sceUsbCamReadVideoFrame
func SceUsbCamReadVideoFrame(buf unsafe.Pointer, size uint32) int32

//go:linkname SceUsbCamWaitReadVideoFrameEnd sceUsbCamWaitReadVideoFrameEnd
func SceUsbCamWaitReadVideoFrameEnd() int32

//go:linkname SceUsbCamPollReadVideoFrameEnd sceUsbCamPollReadVideoFrameEnd
func SceUsbCamPollReadVideoFrameEnd() int32

//go:linkname SceUsbCamGetReadVideoFrameSize sceUsbCamGetReadVideoFrameSize
func SceUsbCamGetReadVideoFrameSize() int32

//go:linkname SceUsbCamSetSaturation sceUsbCamSetSaturation
func SceUsbCamSetSaturation(saturation int32) int32

//go:linkname SceUsbCamSetBrightness sceUsbCamSetBrightness
func SceUsbCamSetBrightness(brightness int32) int32

//go:linkname SceUsbCamSetContrast sceUsbCamSetContrast
func SceUsbCamSetContrast(contrast int32) int32

//go:linkname SceUsbCamSetSharpness sceUsbCamSetSharpness
func SceUsbCamSetSharpness(sharpness int32) int32

//go:linkname SceUsbCamSetImageEffectMode sceUsbCamSetImageEffectMode
func SceUsbCamSetImageEffectMode(effectmode int32) int32

//go:linkname SceUsbCamSetEvLevel sceUsbCamSetEvLevel
func SceUsbCamSetEvLevel(ev int32) int32

//go:linkname SceUsbCamSetReverseMode sceUsbCamSetReverseMode
func SceUsbCamSetReverseMode(reverseflags int32) int32

//go:linkname SceUsbCamSetZoom sceUsbCamSetZoom
func SceUsbCamSetZoom(zoom int32) int32

//go:linkname SceUsbCamGetSaturation sceUsbCamGetSaturation
func SceUsbCamGetSaturation(saturation unsafe.Pointer) int32

//go:linkname SceUsbCamGetBrightness sceUsbCamGetBrightness
func SceUsbCamGetBrightness(brightness unsafe.Pointer) int32

//go:linkname SceUsbCamGetContrast sceUsbCamGetContrast
func SceUsbCamGetContrast(contrast unsafe.Pointer) int32

//go:linkname SceUsbCamGetSharpness sceUsbCamGetSharpness
func SceUsbCamGetSharpness(sharpness unsafe.Pointer) int32

//go:linkname SceUsbCamGetImageEffectMode sceUsbCamGetImageEffectMode
func SceUsbCamGetImageEffectMode(effectmode unsafe.Pointer) int32

//go:linkname SceUsbCamGetEvLevel sceUsbCamGetEvLevel
func SceUsbCamGetEvLevel(ev unsafe.Pointer) int32

//go:linkname SceUsbCamGetReverseMode sceUsbCamGetReverseMode
func SceUsbCamGetReverseMode(reverseflags unsafe.Pointer) int32

//go:linkname SceUsbCamGetZoom sceUsbCamGetZoom
func SceUsbCamGetZoom(zoom unsafe.Pointer) int32

//go:linkname SceUsbCamAutoImageReverseSW sceUsbCamAutoImageReverseSW
func SceUsbCamAutoImageReverseSW(on int32) int32

//go:linkname SceUsbCamGetAutoImageReverseState sceUsbCamGetAutoImageReverseState
func SceUsbCamGetAutoImageReverseState() int32

//go:linkname SceUsbCamGetLensDirection sceUsbCamGetLensDirection
func SceUsbCamGetLensDirection() int32

//go:linkname SceUsbCamSetupMic sceUsbCamSetupMic
func SceUsbCamSetupMic(param unsafe.Pointer, workarea unsafe.Pointer, wasize int32) int32
