// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psploadcore.h

// Package loadcore provides direct TinyGo bindings for psploadcore.h.
package loadcore

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_MODULE_USER                 = 0
	PSP_MODULE_NO_STOP              = 1
	PSP_MODULE_SINGLE_LOAD          = 2
	PSP_MODULE_SINGLE_START         = 4
	PSP_MODULE_KERNEL               = 4096
	SCE_MODULE_ATTR_NONE            = 0
	SCE_MODULE_ATTR_CANT_STOP       = 1
	SCE_MODULE_ATTR_EXCLUSIVE_LOAD  = 2
	SCE_MODULE_ATTR_EXCLUSIVE_START = 4
	SCE_MODULE_USER                 = 0
	SCE_MODULE_MS                   = 512
	SCE_MODULE_USB_WLAN             = 1024
	SCE_MODULE_APP                  = 1536
	SCE_MODULE_VSH                  = 2048
	SCE_MODULE_KERNEL               = 4096
	SCE_MODULE_KIRK_MEMLMD_LIB      = 8192
	SCE_MODULE_KIRK_SEMAPHORE_LIB   = 16384
)

//go:linkname SceKernelFindModuleByName sceKernelFindModuleByName
func SceKernelFindModuleByName(modname unsafe.Pointer) unsafe.Pointer

//go:linkname SceKernelFindModuleByAddress sceKernelFindModuleByAddress
func SceKernelFindModuleByAddress(addr uint32) unsafe.Pointer

//go:linkname SceKernelFindModuleByUID sceKernelFindModuleByUID
func SceKernelFindModuleByUID(modid int32) unsafe.Pointer

//go:linkname SceKernelModuleCount sceKernelModuleCount
func SceKernelModuleCount() int32

//go:linkname SceKernelIcacheClearAll sceKernelIcacheClearAll
func SceKernelIcacheClearAll()

//go:linkname SceKernelCheckExecFile sceKernelCheckExecFile
func SceKernelCheckExecFile(buf unsafe.Pointer, execInfo unsafe.Pointer) int32

//go:linkname SceKernelProbeExecutableObject sceKernelProbeExecutableObject
func SceKernelProbeExecutableObject(buf unsafe.Pointer, execInfo unsafe.Pointer) int32

//go:linkname SceKernelGetModuleIdListForKernel sceKernelGetModuleIdListForKernel
func SceKernelGetModuleIdListForKernel(mod_id_list unsafe.Pointer, size uint32, mod_count unsafe.Pointer, user_mods_only uint32) int32

//go:linkname SceKernelCheckPspConfig sceKernelCheckPspConfig
func SceKernelCheckPspConfig(buf unsafe.Pointer, size int32, flag int32) int32
