// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspgum.h

// Package gum provides direct TinyGo bindings for pspgum.h.
package gum

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceGumDrawArray sceGumDrawArray
func SceGumDrawArray(prim int32, vtype int32, count int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGumDrawArrayN sceGumDrawArrayN
func SceGumDrawArrayN(prim int32, vtype int32, count int32, a3 int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGumDrawBezier sceGumDrawBezier
func SceGumDrawBezier(vtype int32, ucount int32, vcount int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGumDrawSpline sceGumDrawSpline
func SceGumDrawSpline(vtype int32, ucount int32, vcount int32, uedge int32, vedge int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGumLoadIdentity sceGumLoadIdentity
func SceGumLoadIdentity()

//go:linkname SceGumLoadMatrix sceGumLoadMatrix
func SceGumLoadMatrix(m unsafe.Pointer)

//go:linkname SceGumLookAt sceGumLookAt
func SceGumLookAt(eye unsafe.Pointer, center unsafe.Pointer, up unsafe.Pointer)

//go:linkname SceGumMatrixMode sceGumMatrixMode
func SceGumMatrixMode(mode int32)

//go:linkname SceGumMultMatrix sceGumMultMatrix
func SceGumMultMatrix(m unsafe.Pointer)

//go:linkname SceGumOrtho sceGumOrtho
func SceGumOrtho(left float32, right float32, bottom float32, top float32, near float32, far float32)

//go:linkname SceGumPerspective sceGumPerspective
func SceGumPerspective(fovy float32, aspect float32, near float32, far float32)

//go:linkname SceGumPopMatrix sceGumPopMatrix
func SceGumPopMatrix()

//go:linkname SceGumPushMatrix sceGumPushMatrix
func SceGumPushMatrix()

//go:linkname SceGumRotateX sceGumRotateX
func SceGumRotateX(angle float32)

//go:linkname SceGumRotateY sceGumRotateY
func SceGumRotateY(angle float32)

//go:linkname SceGumRotateZ sceGumRotateZ
func SceGumRotateZ(angle float32)

//go:linkname SceGumRotateXYZ sceGumRotateXYZ
func SceGumRotateXYZ(v unsafe.Pointer)

//go:linkname SceGumRotateZYX sceGumRotateZYX
func SceGumRotateZYX(v unsafe.Pointer)

//go:linkname SceGumRotate sceGumRotate
func SceGumRotate(q unsafe.Pointer)

//go:linkname SceGumScale sceGumScale
func SceGumScale(v unsafe.Pointer)

//go:linkname SceGumStoreMatrix sceGumStoreMatrix
func SceGumStoreMatrix(m unsafe.Pointer)

//go:linkname SceGumTranslate sceGumTranslate
func SceGumTranslate(v unsafe.Pointer)

//go:linkname SceGumUpdateMatrix sceGumUpdateMatrix
func SceGumUpdateMatrix()

//go:linkname SceGumFullInverse sceGumFullInverse
func SceGumFullInverse()

//go:linkname SceGumFastInverse sceGumFastInverse
func SceGumFastInverse()

//go:linkname SceGumBeginObject sceGumBeginObject
func SceGumBeginObject(vtype int32, count int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGumEndObject sceGumEndObject
func SceGumEndObject()

//go:linkname GumInit gumInit
func GumInit()

//go:linkname GumLoadIdentity gumLoadIdentity
func GumLoadIdentity(m unsafe.Pointer)

//go:linkname GumLoadQuaternion gumLoadQuaternion
func GumLoadQuaternion(r unsafe.Pointer, q unsafe.Pointer)

//go:linkname GumLoadMatrix gumLoadMatrix
func GumLoadMatrix(r unsafe.Pointer, a unsafe.Pointer)

//go:linkname GumLookAt gumLookAt
func GumLookAt(m unsafe.Pointer, eye unsafe.Pointer, center unsafe.Pointer, up unsafe.Pointer)

//go:linkname GumMultMatrix gumMultMatrix
func GumMultMatrix(result unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer)

//go:linkname GumOrtho gumOrtho
func GumOrtho(m unsafe.Pointer, left float32, right float32, bottom float32, top float32, near float32, far float32)

//go:linkname GumPerspective gumPerspective
func GumPerspective(m unsafe.Pointer, fovy float32, aspect float32, near float32, far float32)

//go:linkname GumRotateX gumRotateX
func GumRotateX(m unsafe.Pointer, angle float32)

//go:linkname GumRotateXYZ gumRotateXYZ
func GumRotateXYZ(m unsafe.Pointer, v unsafe.Pointer)

//go:linkname GumRotateY gumRotateY
func GumRotateY(m unsafe.Pointer, angle float32)

//go:linkname GumRotateZ gumRotateZ
func GumRotateZ(m unsafe.Pointer, angle float32)

//go:linkname GumRotateZYX gumRotateZYX
func GumRotateZYX(m unsafe.Pointer, v unsafe.Pointer)

//go:linkname GumRotateMatrix gumRotateMatrix
func GumRotateMatrix(m unsafe.Pointer, q unsafe.Pointer)

//go:linkname GumScale gumScale
func GumScale(m unsafe.Pointer, v unsafe.Pointer)

//go:linkname GumTranslate gumTranslate
func GumTranslate(m unsafe.Pointer, v unsafe.Pointer)

//go:linkname GumFullInverse gumFullInverse
func GumFullInverse(r unsafe.Pointer, a unsafe.Pointer)

//go:linkname GumFastInverse gumFastInverse
func GumFastInverse(r unsafe.Pointer, a unsafe.Pointer)

//go:linkname GumCrossProduct gumCrossProduct
func GumCrossProduct(r unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer)

//go:linkname GumDotProduct gumDotProduct
func GumDotProduct(a unsafe.Pointer, b unsafe.Pointer) float32

//go:linkname GumNormalize gumNormalize
func GumNormalize(v unsafe.Pointer)

//go:linkname GumRotateVector gumRotateVector
func GumRotateVector(r unsafe.Pointer, q unsafe.Pointer, v unsafe.Pointer)

//go:linkname GumNormalizeQuaternion gumNormalizeQuaternion
func GumNormalizeQuaternion(q unsafe.Pointer)

//go:linkname GumLoadAxisAngle gumLoadAxisAngle
func GumLoadAxisAngle(r unsafe.Pointer, axis unsafe.Pointer, t float32)

//go:linkname GumMultQuaternion gumMultQuaternion
func GumMultQuaternion(result unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer)
