// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspvfpu.h

// Package vfpu provides direct TinyGo bindings for pspvfpu.h.
package vfpu

import "unsafe"

var _ unsafe.Pointer

//go:linkname Pspvfpu_initcontext pspvfpu_initcontext
func Pspvfpu_initcontext() unsafe.Pointer

//go:linkname Pspvfpu_deletecontext pspvfpu_deletecontext
func Pspvfpu_deletecontext(context unsafe.Pointer)

//go:linkname Pspvfpu_use_matrices pspvfpu_use_matrices
func Pspvfpu_use_matrices(context unsafe.Pointer, keepset uint8, tempset uint8)
