// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: vshctrl.h

// Package vshctrl provides direct TinyGo bindings for vshctrl.h.
package vshctrl

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspvshctrl() }

//go:linkname requirePspvshctrl pspsdk_go_require_pspvshctrl
func requirePspvshctrl()

const (
	PSP_MODULE_USER                    = 0
	PSP_MODULE_NO_STOP                 = 1
	PSP_MODULE_SINGLE_LOAD             = 2
	PSP_MODULE_SINGLE_START            = 4
	PSP_MODULE_KERNEL                  = 4096
	PSP_THREAD_ATTR_VFPU               = 16384
	PSP_THREAD_ATTR_USER               = 2147483648
	PSP_THREAD_ATTR_USBWLAN            = 2684354560
	PSP_THREAD_ATTR_VSH                = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM       = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK       = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK        = 2097152
	PSP_THREAD_RUNNING                 = 1
	PSP_THREAD_READY                   = 2
	PSP_THREAD_WAITING                 = 4
	PSP_THREAD_SUSPEND                 = 8
	PSP_THREAD_STOPPED                 = 16
	PSP_THREAD_KILLED                  = 32
	PSP_LW_MUTEX_ATTR_THFIFO           = 0
	PSP_LW_MUTEX_ATTR_THPRI            = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE        = 512
	PSP_EVENT_WAITSINGLE               = 0
	PSP_EVENT_WAITMULTIPLE             = 512
	PSP_EVENT_WAITAND                  = 0
	PSP_EVENT_WAITOR                   = 1
	PSP_EVENT_WAITCLEAR                = 32
	SCE_KERNEL_TMID_Thread             = 1
	SCE_KERNEL_TMID_Semaphore          = 2
	SCE_KERNEL_TMID_EventFlag          = 3
	SCE_KERNEL_TMID_Mbox               = 4
	SCE_KERNEL_TMID_Vpl                = 5
	SCE_KERNEL_TMID_Fpl                = 6
	SCE_KERNEL_TMID_Mpipe              = 7
	SCE_KERNEL_TMID_Callback           = 8
	SCE_KERNEL_TMID_ThreadEventHandler = 9
	SCE_KERNEL_TMID_Alarm              = 10
	SCE_KERNEL_TMID_VTimer             = 11
	SCE_KERNEL_TMID_SleepThread        = 64
	SCE_KERNEL_TMID_DelayThread        = 65
	SCE_KERNEL_TMID_SuspendThread      = 66
	SCE_KERNEL_TMID_DormantThread      = 67
	THREADEVENT_ALL                    = 4294967295
	THREADEVENT_KERN                   = 4294967288
	THREADEVENT_USER                   = 4294967280
	THREADEVENT_CURRENT                = 0
	THREAD_CREATE                      = 1
	THREAD_START                       = 2
	THREAD_EXIT                        = 4
	THREAD_DELETE                      = 8
	PSP_CTRL_SELECT                    = 1
	PSP_CTRL_L3                        = 2
	PSP_CTRL_R3                        = 4
	PSP_CTRL_START                     = 8
	PSP_CTRL_UP                        = 16
	PSP_CTRL_RIGHT                     = 32
	PSP_CTRL_DOWN                      = 64
	PSP_CTRL_LEFT                      = 128
	PSP_CTRL_LTRIGGER                  = 256
	PSP_CTRL_RTRIGGER                  = 512
	PSP_CTRL_L2                        = 256
	PSP_CTRL_R2                        = 512
	PSP_CTRL_L1                        = 1024
	PSP_CTRL_R1                        = 2048
	PSP_CTRL_TRIANGLE                  = 4096
	PSP_CTRL_CIRCLE                    = 8192
	PSP_CTRL_CROSS                     = 16384
	PSP_CTRL_SQUARE                    = 32768
	PSP_CTRL_HOME                      = 65536
	PSP_CTRL_HOLD                      = 131072
	PSP_CTRL_NOTE                      = 8388608
	PSP_CTRL_SCREEN                    = 4194304
	PSP_CTRL_VOLUP                     = 1048576
	PSP_CTRL_VOLDOWN                   = 2097152
	PSP_CTRL_WLAN_UP                   = 262144
	PSP_CTRL_REMOTE                    = 524288
	PSP_CTRL_DISC                      = 16777216
	PSP_CTRL_MS                        = 33554432
	PSP_CTRL_MODE_DIGITAL              = 0
	PSP_CTRL_MODE_ANALOG               = 1
	FAKE_REGION_DISABLED               = 0
	FAKE_REGION_JAPAN                  = 1
	FAKE_REGION_AMERICA                = 2
	FAKE_REGION_EUROPE                 = 3
	FAKE_REGION_KOREA                  = 4
	FAKE_REGION_UNITED_KINGDOM         = 5
	FAKE_REGION_LATIN_AMERICA          = 6
	FAKE_REGION_AUSTRALIA              = 7
	FAKE_REGION_HONGKONG               = 8
	FAKE_REGION_TAIWAN                 = 9
	FAKE_REGION_RUSSIA                 = 10
	FAKE_REGION_CHINA                  = 11
	FAKE_REGION_DEBUG_TYPE_I           = 12
	FAKE_REGION_DEBUG_TYPE_II          = 13
	MODE_UMD                           = 0
	XO_CURRENT_O_PRIMARY               = 0
	XO_CURRENT_X_PRIMARY               = 1
	NORMAL_TO_PANDORA                  = 0
	PANDORA_TO_NORMAL                  = 1
	UNSUPPORTED                        = 2
)

//go:linkname User_malloc user_malloc
func User_malloc(size uint32) unsafe.Pointer

//go:linkname User_memalign user_memalign
func User_memalign(align uint32, size uint32) unsafe.Pointer

//go:linkname User_free user_free
func User_free(ptr unsafe.Pointer)

//go:linkname VctrlVSHRegisterVshMenu vctrlVSHRegisterVshMenu
func VctrlVSHRegisterVshMenu(ctrl unsafe.Pointer) int32

//go:linkname VctrlVSHExitVSHMenu vctrlVSHExitVSHMenu
func VctrlVSHExitVSHMenu(conf unsafe.Pointer, videoiso unsafe.Pointer, disctype int32) int32

//go:linkname VctrlVSHUpdateConfig vctrlVSHUpdateConfig
func VctrlVSHUpdateConfig(config unsafe.Pointer) int32

//go:linkname VshDetectDiscType vshDetectDiscType
func VshDetectDiscType(path unsafe.Pointer) int32

//go:linkname VshCtrlHibernationExists vshCtrlHibernationExists
func VshCtrlHibernationExists() int32

//go:linkname VshCtrlDeleteHibernation vshCtrlDeleteHibernation
func VshCtrlDeleteHibernation() int32

//go:linkname IsoOpen isoOpen
func IsoOpen(path unsafe.Pointer) int32

//go:linkname IsoRead isoRead
func IsoRead(buffer unsafe.Pointer, lba uint32, offset int32, size uint32) int32

//go:linkname IsoClose isoClose
func IsoClose()

//go:linkname IsoGetFileInfo isoGetFileInfo
func IsoGetFileInfo(path unsafe.Pointer, filesize unsafe.Pointer, lba unsafe.Pointer) int32

//go:linkname IsoGetTotalSectorSize isoGetTotalSectorSize
func IsoGetTotalSectorSize() int32

//go:linkname Has_prometheus_module has_prometheus_module
func Has_prometheus_module(isopath unsafe.Pointer) int32

//go:linkname Has_update_file has_update_file
func Has_update_file(isopath unsafe.Pointer, update_file unsafe.Pointer) int32

//go:linkname VctrlGetRegistryValue vctrlGetRegistryValue
func VctrlGetRegistryValue(dir unsafe.Pointer, name unsafe.Pointer, val unsafe.Pointer) int32

//go:linkname VctrlSetRegistryValue vctrlSetRegistryValue
func VctrlSetRegistryValue(dir unsafe.Pointer, name unsafe.Pointer, val uint32) int32
