// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspamctrl.h

// Package amctrl provides direct TinyGo bindings for pspamctrl.h.
package amctrl

import "unsafe"

var _ unsafe.Pointer

const (
	MAC_KEY_TYPE_UNK0       = 0
	MAC_KEY_TYPE_UNK1       = 1
	MAC_KEY_TYPE_FUSE_ID    = 2
	MAC_KEY_TYPE_FIXED      = 3
	MAC_KEY_TYPE_UNK6       = 6
	CIPHER_KEY_TYPE_FIXED   = 1
	CIPHER_KEY_TYPE_FUSE_ID = 2
	CIPHER_KEY_MODE_ENCRYPT = 1
	CIPHER_KEY_MODE_DECRYPT = 2
)

//go:linkname SceDrmBBMacInit sceDrmBBMacInit
func SceDrmBBMacInit(mac_key unsafe.Pointer, typeValue int32) int32

//go:linkname SceDrmBBMacUpdate sceDrmBBMacUpdate
func SceDrmBBMacUpdate(mac_key unsafe.Pointer, buf unsafe.Pointer, size int32) int32

//go:linkname SceAmctrl_driver_9227EA79 sceAmctrl_driver_9227EA79
func SceAmctrl_driver_9227EA79(mac_key unsafe.Pointer, buf unsafe.Pointer, size int32) int32

//go:linkname SceDrmBBMacFinal sceDrmBBMacFinal
func SceDrmBBMacFinal(mac_key unsafe.Pointer, buf unsafe.Pointer, version_key unsafe.Pointer) int32

//go:linkname SceDrmBBMacFinal2 sceDrmBBMacFinal2
func SceDrmBBMacFinal2(mac_key unsafe.Pointer, buf unsafe.Pointer, version_key unsafe.Pointer) int32

//go:linkname SceDrmBBCipherInit sceDrmBBCipherInit
func SceDrmBBCipherInit(cipher_key unsafe.Pointer, typeValue int32, mode int32, header_key unsafe.Pointer, version_key unsafe.Pointer, seed int32) int32

//go:linkname SceDrmBBCipherUpdate sceDrmBBCipherUpdate
func SceDrmBBCipherUpdate(cipher_key unsafe.Pointer, buf unsafe.Pointer, size int32) int32

//go:linkname SceAmctrl_driver_E04ADD4C sceAmctrl_driver_E04ADD4C
func SceAmctrl_driver_E04ADD4C(cipher_key unsafe.Pointer, buf unsafe.Pointer, size int32) int32

//go:linkname SceDrmBBCipherFinal sceDrmBBCipherFinal
func SceDrmBBCipherFinal(cipher_key unsafe.Pointer) int32
