// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: screenprinter.h

// Package screenprinter provides direct TinyGo bindings for screenprinter.h.
package screenprinter

import "unsafe"

var _ unsafe.Pointer

func init() { requireScreenprinter() }

//go:linkname requireScreenprinter pspsdk_go_require_screenprinter
func requireScreenprinter()

//go:linkname PrintTextScreen printTextScreen
func PrintTextScreen(x int32, y int32, text unsafe.Pointer, color int32)

//go:linkname Print_to_screen print_to_screen
func Print_to_screen(text unsafe.Pointer)

//go:linkname Print_to_screen_color print_to_screen_color
func Print_to_screen_color(text unsafe.Pointer, color int32)

//go:linkname PRTSTR11 PRTSTR11
func PRTSTR11(A unsafe.Pointer, B uint32, C uint32, D uint32, E uint32, F uint32, G uint32, H uint32, I uint32, J uint32, K uint32, L uint32)

//go:linkname InitScreen initScreen
func InitScreen(DisplaySetFrameBuf unsafe.Pointer)

//go:linkname Cls cls
func Cls()
