// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_htmlviewer.h

// Package utility_htmlviewer provides direct TinyGo bindings for psputility_htmlviewer.h.
package utility_htmlviewer

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_ENABLE               = 0
	PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_FULL                  = 0
	PSP_UTILITY_HTMLVIEWER_COOKIEMODE_DISABLED                 = 0
	PSP_UTILITY_HTMLVIEWER_TEXTSIZE_LARGE                      = 0
	PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_NORMAL                  = 0
	PSP_UTILITY_HTMLVIEWER_CONNECTMODE_LAST                    = 0
	PSP_UTILITY_HTMLVIEWER_OPEN_SCE_START_PAGE                 = 1
	PSP_UTILITY_HTMLVIEWER_DISABLE_STARTUP_LIMITS              = 2
	PSP_UTILITY_HTMLVIEWER_DISABLE_EXIT_DIALOG                 = 4
	PSP_UTILITY_HTMLVIEWER_DISABLE_CURSOR                      = 8
	PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_COMPLETE_DIALOG    = 16
	PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_START_DIALOG       = 32
	PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_DESTINATION_DIALOG = 64
	PSP_UTILITY_HTMLVIEWER_LOCK_DOWNLOAD_DESTINATION_DIALOG    = 128
	PSP_UTILITY_HTMLVIEWER_DISABLE_TAB_DISPLAY                 = 256
	PSP_UTILITY_HTMLVIEWER_ENABLE_ANALOG_HOLD                  = 512
	PSP_UTILITY_HTMLVIEWER_ENABLE_FLASH                        = 1024
	PSP_UTILITY_HTMLVIEWER_DISABLE_LRTRIGGER                   = 2048
)

//go:linkname SceUtilityHtmlViewerInitStart sceUtilityHtmlViewerInitStart
func SceUtilityHtmlViewerInitStart(params unsafe.Pointer) int32

//go:linkname SceUtilityHtmlViewerShutdownStart sceUtilityHtmlViewerShutdownStart
func SceUtilityHtmlViewerShutdownStart() int32

//go:linkname SceUtilityHtmlViewerUpdate sceUtilityHtmlViewerUpdate
func SceUtilityHtmlViewerUpdate(n int32) int32

//go:linkname SceUtilityHtmlViewerGetStatus sceUtilityHtmlViewerGetStatus
func SceUtilityHtmlViewerGetStatus() int32
