// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspaudiocodec.h

// Package audiocodec provides direct TinyGo bindings for pspaudiocodec.h.
package audiocodec

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceAudiocodecCheckNeedMem sceAudiocodecCheckNeedMem
func SceAudiocodecCheckNeedMem(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceAudiocodecInit sceAudiocodecInit
func SceAudiocodecInit(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceAudiocodecDecode sceAudiocodecDecode
func SceAudiocodecDecode(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceAudiocodecGetEDRAM sceAudiocodecGetEDRAM
func SceAudiocodecGetEDRAM(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceAudiocodecReleaseEDRAM sceAudiocodecReleaseEDRAM
func SceAudiocodecReleaseEDRAM(Buffer unsafe.Pointer) int32
