// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_netmodules.h

// Package utility_netmodules provides direct TinyGo bindings for psputility_netmodules.h.
package utility_netmodules

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityLoadNetModule sceUtilityLoadNetModule
func SceUtilityLoadNetModule(module int32) int32

//go:linkname SceUtilityUnloadNetModule sceUtilityUnloadNetModule
func SceUtilityUnloadNetModule(module int32) int32
