// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: kbooti_update.h

// Package kbooti_update provides direct TinyGo bindings for kbooti_update.h.
package kbooti_update

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkbootiupdate() }

//go:linkname requirePspkbootiupdate pspsdk_go_require_pspkbootiupdate
func requirePspkbootiupdate()

//go:linkname PspKbootiUpdateGetKbootiSize pspKbootiUpdateGetKbootiSize
func PspKbootiUpdateGetKbootiSize() int32

//go:linkname PspKbootiUpdateKbooti pspKbootiUpdateKbooti
func PspKbootiUpdateKbooti(cIplBlock unsafe.Pointer, cIplBlockSize uint32) int32

//go:linkname PspKbootiUpdateRestoreKbooti pspKbootiUpdateRestoreKbooti
func PspKbootiUpdateRestoreKbooti() int32
