// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: systemctrl_se.h

// Package systemctrl_se provides direct TinyGo bindings for systemctrl_se.h.
package systemctrl_se

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspsystemctrlKernel() }

//go:linkname requirePspsystemctrlKernel pspsdk_go_require_pspsystemctrl_kernel
func requirePspsystemctrlKernel()

const (
	FAKE_REGION_DISABLED       = 0
	FAKE_REGION_JAPAN          = 1
	FAKE_REGION_AMERICA        = 2
	FAKE_REGION_EUROPE         = 3
	FAKE_REGION_KOREA          = 4
	FAKE_REGION_UNITED_KINGDOM = 5
	FAKE_REGION_LATIN_AMERICA  = 6
	FAKE_REGION_AUSTRALIA      = 7
	FAKE_REGION_HONGKONG       = 8
	FAKE_REGION_TAIWAN         = 9
	FAKE_REGION_RUSSIA         = 10
	FAKE_REGION_CHINA          = 11
	FAKE_REGION_DEBUG_TYPE_I   = 12
	FAKE_REGION_DEBUG_TYPE_II  = 13
	MODE_UMD                   = 0
	XO_CURRENT_O_PRIMARY       = 0
	XO_CURRENT_X_PRIMARY       = 1
	NORMAL_TO_PANDORA          = 0
	PANDORA_TO_NORMAL          = 1
	UNSUPPORTED                = 2
)

//go:linkname SctrlSEGetVersion sctrlSEGetVersion
func SctrlSEGetVersion() int32

//go:linkname SctrlSEGetConfig sctrlSEGetConfig
func SctrlSEGetConfig(config unsafe.Pointer) int32

//go:linkname SctrlSEGetConfigEx sctrlSEGetConfigEx
func SctrlSEGetConfigEx(config unsafe.Pointer, size int32) int32

//go:linkname SctrlSESetConfig sctrlSESetConfig
func SctrlSESetConfig(config unsafe.Pointer) int32

//go:linkname SctrlSESetConfigEx sctrlSESetConfigEx
func SctrlSESetConfigEx(config unsafe.Pointer, size int32) int32

//go:linkname SctrlSEApplyConfig sctrlSEApplyConfig
func SctrlSEApplyConfig(conf unsafe.Pointer)

//go:linkname SctrlSEApplyConfigEX sctrlSEApplyConfigEX
func SctrlSEApplyConfigEX(conf unsafe.Pointer, size int32) int32

//go:linkname SctrlSEGetConfigInternal sctrlSEGetConfigInternal
func SctrlSEGetConfigInternal() unsafe.Pointer

//go:linkname SctrlSEMountUmdFromFile sctrlSEMountUmdFromFile
func SctrlSEMountUmdFromFile(file unsafe.Pointer, noumd int32, isofs int32) int32

//go:linkname SctrlSEUmountUmd sctrlSEUmountUmd
func SctrlSEUmountUmd() int32

//go:linkname SctrlSESetDiscOut sctrlSESetDiscOut
func SctrlSESetDiscOut(out int32)

//go:linkname SctrlSESetDiscType sctrlSESetDiscType
func SctrlSESetDiscType(typeValue int32)

//go:linkname SctrlSEGetDiscType sctrlSEGetDiscType
func SctrlSEGetDiscType() int32

//go:linkname SctrlSEGetUmdFile sctrlSEGetUmdFile
func SctrlSEGetUmdFile() unsafe.Pointer

//go:linkname GetUmdFile GetUmdFile
func GetUmdFile() unsafe.Pointer

//go:linkname SctrlSESetUmdFile sctrlSESetUmdFile
func SctrlSESetUmdFile(file unsafe.Pointer)

//go:linkname SetUmdFile SetUmdFile
func SetUmdFile(file unsafe.Pointer)

//go:linkname SctrlSESetBootConfFileIndex sctrlSESetBootConfFileIndex
func SctrlSESetBootConfFileIndex(index int32)

//go:linkname SctrlSEGetBootConfFileIndex sctrlSEGetBootConfFileIndex
func SctrlSEGetBootConfFileIndex() uint32

//go:linkname Oe_malloc oe_malloc
func Oe_malloc(size uint32) unsafe.Pointer

//go:linkname Oe_memalign oe_memalign
func Oe_memalign(align uint32, size uint32) unsafe.Pointer

//go:linkname Oe_free oe_free
func Oe_free(p unsafe.Pointer)
