// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspirkeyb_rawkeys.h

// Package irkeyb_rawkeys provides direct TinyGo bindings for pspirkeyb_rawkeys.h.
package irkeyb_rawkeys

import "unsafe"

var _ unsafe.Pointer

//go:linkname PspIrKeybRawkeyName pspIrKeybRawkeyName
func PspIrKeybRawkeyName(raw uint32) unsafe.Pointer
