// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: ciso.h

// Package ciso provides direct TinyGo bindings for ciso.h.
package ciso

import "unsafe"

var _ unsafe.Pointer

func init() { requireCisoread() }

//go:linkname requireCisoread pspsdk_go_require_cisoread
func requireCisoread()

const (
	JISO_METHOD_LZO  = 0
	JISO_METHOD_ZLIB = 1
	CISO_BAD_ARGS    = -1
	CISO_IO_ERROR    = -2
	CISO_NOT_VALID   = 0
)

//go:linkname Ciso_open ciso_open
func Ciso_open(file unsafe.Pointer) int32

//go:linkname Ciso_read ciso_read
func Ciso_read(file unsafe.Pointer, addr unsafe.Pointer, size uint32, offset uint32) int32

//go:linkname Ciso_close ciso_close
func Ciso_close(file unsafe.Pointer) int32
