// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_modules.h

// Package utility_modules provides direct TinyGo bindings for psputility_modules.h.
package utility_modules

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityLoadModule sceUtilityLoadModule
func SceUtilityLoadModule(module int32) int32

//go:linkname SceUtilityUnloadModule sceUtilityUnloadModule
func SceUtilityUnloadModule(module int32) int32
