// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspintrman_kernel.h

// Package intrman_kernel provides direct TinyGo bindings for pspintrman_kernel.h.
package intrman_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

//go:linkname SceKernelRegisterIntrHandler sceKernelRegisterIntrHandler
func SceKernelRegisterIntrHandler(intno int32, no int32, handler unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32

//go:linkname SceKernelReleaseIntrHandler sceKernelReleaseIntrHandler
func SceKernelReleaseIntrHandler(intno int32) int32

//go:linkname SceKernelEnableIntr sceKernelEnableIntr
func SceKernelEnableIntr(intno int32) int32

//go:linkname SceKernelDisableIntr sceKernelDisableIntr
func SceKernelDisableIntr(intno int32) int32

//go:linkname SceKernelIsIntrContext sceKernelIsIntrContext
func SceKernelIsIntrContext() int32

//go:linkname SceKernelQuerySystemCall sceKernelQuerySystemCall
func SceKernelQuerySystemCall(function unsafe.Pointer) int32
