// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspvaudio.h

// Package vaudio provides direct TinyGo bindings for pspvaudio.h.
package vaudio

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceVaudioOutputBlocking sceVaudioOutputBlocking
func SceVaudioOutputBlocking(volume int32, buffer unsafe.Pointer) int32

//go:linkname SceVaudioChReserve sceVaudioChReserve
func SceVaudioChReserve(samplecount int32, frequency int32, format int32) int32

//go:linkname SceVaudioChRelease sceVaudioChRelease
func SceVaudioChRelease() int32

//go:linkname SceVaudioSetEffectType sceVaudioSetEffectType
func SceVaudioSetEffectType(effect int32, volume int32) int32

//go:linkname SceVaudioSetAlcMode sceVaudioSetAlcMode
func SceVaudioSetAlcMode(mode int32) int32
