// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_avmodules.h

// Package utility_avmodules provides direct TinyGo bindings for psputility_avmodules.h.
package utility_avmodules

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityLoadAvModule sceUtilityLoadAvModule
func SceUtilityLoadAvModule(module int32) int32

//go:linkname SceUtilityUnloadAvModule sceUtilityUnloadAvModule
func SceUtilityUnloadAvModule(module int32) int32
