// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspaudiorouting.h

// Package audiorouting provides direct TinyGo bindings for pspaudiorouting.h.
package audiorouting

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceAudioRoutingSetMode sceAudioRoutingSetMode
func SceAudioRoutingSetMode(mode int32) int32

//go:linkname SceAudioRoutingGetMode sceAudioRoutingGetMode
func SceAudioRoutingGetMode() int32

//go:linkname SceAudioRoutingGetVolumeMode sceAudioRoutingGetVolumeMode
func SceAudioRoutingGetVolumeMode() int32

//go:linkname SceAudioRoutingSetVolumeMode sceAudioRoutingSetVolumeMode
func SceAudioRoutingSetVolumeMode(vol_mode int32) int32
