// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspctrl_kernel.h

// Package ctrl_kernel provides direct TinyGo bindings for pspctrl_kernel.h.
package ctrl_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspctrlDriver() }

//go:linkname requirePspctrlDriver pspsdk_go_require_pspctrl_driver
func requirePspctrlDriver()

const (
	SCE_CTRL_MASK_NO_MASK        = 0
	SCE_CTRL_MASK_IGNORE_BUTTONS = 1
	SCE_CTRL_MASK_APPLY_BUTTONS  = 2
)

//go:linkname SceCtrlSetButtonIntercept sceCtrlSetButtonIntercept
func SceCtrlSetButtonIntercept(buttons uint32, mask_mode uint32) int32

//go:linkname SceCtrlGetButtonIntercept sceCtrlGetButtonIntercept
func SceCtrlGetButtonIntercept(buttons uint32) int32

//go:linkname SceCtrlSetSpecialButtonCallback sceCtrlSetSpecialButtonCallback
func SceCtrlSetSpecialButtonCallback(slot uint32, button_mask uint32, callback unsafe.Pointer, opt unsafe.Pointer) int32
