// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspusb.h

// Package usb provides direct TinyGo bindings for pspusb.h.
package usb

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUsbStart sceUsbStart
func SceUsbStart(driverName unsafe.Pointer, size int32, args unsafe.Pointer) int32

//go:linkname SceUsbStop sceUsbStop
func SceUsbStop(driverName unsafe.Pointer, size int32, args unsafe.Pointer) int32

//go:linkname SceUsbActivate sceUsbActivate
func SceUsbActivate(pid int32) int32

//go:linkname SceUsbDeactivate sceUsbDeactivate
func SceUsbDeactivate(pid int32) int32

//go:linkname SceUsbGetState sceUsbGetState
func SceUsbGetState() int32

//go:linkname SceUsbGetDrvState sceUsbGetDrvState
func SceUsbGetDrvState(driverName unsafe.Pointer) int32
