// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspdebugkb.h

// Package debugkb provides direct TinyGo bindings for pspdebugkb.h.
package debugkb

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_DEBUG_KB_MAXLEN         = 40
	PSP_DEBUG_KB_BOX_X          = 6
	PSP_DEBUG_KB_BOX_Y          = 8
	PSP_DEBUG_KB_CHAR_COLOUR    = 4294967295
	PSP_DEBUG_KB_BACK_COLOUR    = 4278190080
	PSP_DEBUG_KB_CHAR_HIGHLIGHT = 4278255360
	PSP_DEBUG_KB_BACK_HIGHLIGHT = 4279242768
	PSP_DEBUG_KB_OFFSET_X       = 6
	PSP_DEBUG_KB_OFFSET_Y       = 4
	PSP_DEBUG_KB_SPACING_X      = 3
	PSP_DEBUG_KB_SPACING_Y      = 2
	PSP_DEBUG_KB_NUM_CHARS      = 13
	PSP_DEBUG_KB_NUM_ROWS       = 4
	PSP_DEBUG_KB_BOX_WIDTH      = 51
	PSP_DEBUG_KB_BOX_HEIGHT     = 14
	PSP_DEBUG_KB_COMMAND_ROW    = 4
	PSP_DEBUG_KB_NUM_COMMANDS   = 5
)

//go:linkname PspDebugKbShift pspDebugKbShift
func PspDebugKbShift(shiftState unsafe.Pointer)

//go:linkname PspDebugKbDrawKey pspDebugKbDrawKey
func PspDebugKbDrawKey(row int32, col int32, highlight int32)

//go:linkname PspDebugKbDrawString pspDebugKbDrawString
func PspDebugKbDrawString(str unsafe.Pointer)

//go:linkname PspDebugKbClearBox pspDebugKbClearBox
func PspDebugKbClearBox()

//go:linkname PspDebugKbDrawBox pspDebugKbDrawBox
func PspDebugKbDrawBox()

//go:linkname PspDebugKbInit pspDebugKbInit
func PspDebugKbInit(str unsafe.Pointer)
