// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspipl_update.h

// Package ipl_update provides direct TinyGo bindings for pspipl_update.h.
package ipl_update

import "unsafe"

var _ unsafe.Pointer

//go:linkname PspIplUpdateGetIpl pspIplUpdateGetIpl
func PspIplUpdateGetIpl(buf unsafe.Pointer) int32

//go:linkname PspIplUpdateClearIpl pspIplUpdateClearIpl
func PspIplUpdateClearIpl() int32

//go:linkname PspIplUpdateSetIpl pspIplUpdateSetIpl
func PspIplUpdateSetIpl(buf unsafe.Pointer, size int32, key int32) int32
