// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsysmem_kernel.h

// Package sysmem_kernel provides direct TinyGo bindings for pspsysmem_kernel.h.
package sysmem_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

const (
	PSP_SMEM_Low = 0
)

//go:linkname SceKernelSetCompiledSdkVersion sceKernelSetCompiledSdkVersion
func SceKernelSetCompiledSdkVersion(version int32) int32

//go:linkname SceKernelGetCompiledSdkVersion sceKernelGetCompiledSdkVersion
func SceKernelGetCompiledSdkVersion() int32

//go:linkname SceKernelQueryMemoryPartitionInfo sceKernelQueryMemoryPartitionInfo
func SceKernelQueryMemoryPartitionInfo(pid int32, info unsafe.Pointer) int32

//go:linkname SceKernelPartitionTotalFreeMemSize sceKernelPartitionTotalFreeMemSize
func SceKernelPartitionTotalFreeMemSize(pid int32) int32

//go:linkname SceKernelPartitionMaxFreeMemSize sceKernelPartitionMaxFreeMemSize
func SceKernelPartitionMaxFreeMemSize(pid int32) int32

//go:linkname SceKernelSysMemDump sceKernelSysMemDump
func SceKernelSysMemDump()

//go:linkname SceKernelSysMemDumpBlock sceKernelSysMemDumpBlock
func SceKernelSysMemDumpBlock()

//go:linkname SceKernelSysMemDumpTail sceKernelSysMemDumpTail
func SceKernelSysMemDumpTail()

//go:linkname SceKernelSetDdrMemoryProtection sceKernelSetDdrMemoryProtection
func SceKernelSetDdrMemoryProtection(addr unsafe.Pointer, size int32, prot int32) int32

//go:linkname SceKernelCreateHeap sceKernelCreateHeap
func SceKernelCreateHeap(partitionid int32, size uint32, unk int32, name unsafe.Pointer) int32

//go:linkname SceKernelAllocHeapMemory sceKernelAllocHeapMemory
func SceKernelAllocHeapMemory(heapid int32, size uint32) unsafe.Pointer

//go:linkname SceKernelFreeHeapMemory sceKernelFreeHeapMemory
func SceKernelFreeHeapMemory(heapid int32, block unsafe.Pointer) int32

//go:linkname SceKernelDeleteHeap sceKernelDeleteHeap
func SceKernelDeleteHeap(heapid int32) int32

//go:linkname SceKernelHeapTotalFreeSize sceKernelHeapTotalFreeSize
func SceKernelHeapTotalFreeSize(heapid int32) int32

//go:linkname SceKernelGetSceUidControlBlock sceKernelGetSceUidControlBlock
func SceKernelGetSceUidControlBlock(uid int32, block unsafe.Pointer) int32

//go:linkname SceKernelGetSceUidControlBlockWithType sceKernelGetSceUidControlBlockWithType
func SceKernelGetSceUidControlBlockWithType(uid int32, typeValue unsafe.Pointer, block unsafe.Pointer) int32

//go:linkname SysMemForKernel_536AD5E1 SysMemForKernel_536AD5E1
func SysMemForKernel_536AD5E1() unsafe.Pointer

//go:linkname SceKernelDeleteUID sceKernelDeleteUID
func SceKernelDeleteUID(uid int32) int32

//go:linkname SceKernelGetModel sceKernelGetModel
func SceKernelGetModel() int32

//go:linkname SceKernelGetGameInfo sceKernelGetGameInfo
func SceKernelGetGameInfo() unsafe.Pointer

//go:linkname SceKernelGetSystemStatus sceKernelGetSystemStatus
func SceKernelGetSystemStatus() int32

//go:linkname SceKernelGetUIDcontrolBlock sceKernelGetUIDcontrolBlock
func SceKernelGetUIDcontrolBlock(uid int32, block unsafe.Pointer) int32
