// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspdmac.h

// Package dmac provides direct TinyGo bindings for pspdmac.h.
package dmac

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceDmacMemcpy sceDmacMemcpy
func SceDmacMemcpy(dst unsafe.Pointer, src unsafe.Pointer, n uint32) int32

//go:linkname SceDmacTryMemcpy sceDmacTryMemcpy
func SceDmacTryMemcpy(dst unsafe.Pointer, src unsafe.Pointer, n uint32) int32
