// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspusbacc.h

// Package usbacc provides direct TinyGo bindings for pspusbacc.h.
package usbacc

import "unsafe"

var _ unsafe.Pointer
