// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspextratypes.h

// Package extratypes provides direct TinyGo bindings for pspextratypes.h.
package extratypes

import "unsafe"

var _ unsafe.Pointer

const (
	ISO_DISC_TYPE_GAME  = 16
	ISO_DISC_TYPE_VIDEO = 32
	ISO_DISC_TYPE_AUDIO = 64
)
