// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_adhoc.h

// Package net_adhoc provides direct TinyGo bindings for pspnet_adhoc.h.
package net_adhoc

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceNetAdhocInit sceNetAdhocInit
func SceNetAdhocInit() int32

//go:linkname SceNetAdhocTerm sceNetAdhocTerm
func SceNetAdhocTerm() int32

//go:linkname SceNetAdhocPdpCreate sceNetAdhocPdpCreate
func SceNetAdhocPdpCreate(mac unsafe.Pointer, port uint16, bufsize uint32, unk1 int32) int32

//go:linkname SceNetAdhocPdpDelete sceNetAdhocPdpDelete
func SceNetAdhocPdpDelete(id int32, unk1 int32) int32

//go:linkname SceNetAdhocPdpSend sceNetAdhocPdpSend
func SceNetAdhocPdpSend(id int32, destMacAddr unsafe.Pointer, port uint16, data unsafe.Pointer, len uint32, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPdpRecv sceNetAdhocPdpRecv
func SceNetAdhocPdpRecv(id int32, srcMacAddr unsafe.Pointer, port unsafe.Pointer, data unsafe.Pointer, dataLength unsafe.Pointer, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocGetPdpStat sceNetAdhocGetPdpStat
func SceNetAdhocGetPdpStat(size unsafe.Pointer, stat unsafe.Pointer) int32

//go:linkname SceNetAdhocGameModeCreateMaster sceNetAdhocGameModeCreateMaster
func SceNetAdhocGameModeCreateMaster(data unsafe.Pointer, size int32) int32

//go:linkname SceNetAdhocGameModeCreateReplica sceNetAdhocGameModeCreateReplica
func SceNetAdhocGameModeCreateReplica(mac unsafe.Pointer, data unsafe.Pointer, size int32) int32

//go:linkname SceNetAdhocGameModeUpdateMaster sceNetAdhocGameModeUpdateMaster
func SceNetAdhocGameModeUpdateMaster() int32

//go:linkname SceNetAdhocGameModeUpdateReplica sceNetAdhocGameModeUpdateReplica
func SceNetAdhocGameModeUpdateReplica(id int32, unk1 int32) int32

//go:linkname SceNetAdhocGameModeDeleteMaster sceNetAdhocGameModeDeleteMaster
func SceNetAdhocGameModeDeleteMaster() int32

//go:linkname SceNetAdhocGameModeDeleteReplica sceNetAdhocGameModeDeleteReplica
func SceNetAdhocGameModeDeleteReplica(id int32) int32

//go:linkname SceNetAdhocPtpOpen sceNetAdhocPtpOpen
func SceNetAdhocPtpOpen(srcmac unsafe.Pointer, srcport uint16, destmac unsafe.Pointer, destport uint16, bufsize uint32, delay uint32, count int32, unk1 int32) int32

//go:linkname SceNetAdhocPtpConnect sceNetAdhocPtpConnect
func SceNetAdhocPtpConnect(id int32, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPtpListen sceNetAdhocPtpListen
func SceNetAdhocPtpListen(srcmac unsafe.Pointer, srcport uint16, bufsize uint32, delay uint32, count int32, queue int32, unk1 int32) int32

//go:linkname SceNetAdhocPtpAccept sceNetAdhocPtpAccept
func SceNetAdhocPtpAccept(id int32, mac unsafe.Pointer, port unsafe.Pointer, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPtpSend sceNetAdhocPtpSend
func SceNetAdhocPtpSend(id int32, data unsafe.Pointer, datasize unsafe.Pointer, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPtpRecv sceNetAdhocPtpRecv
func SceNetAdhocPtpRecv(id int32, data unsafe.Pointer, datasize unsafe.Pointer, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPtpFlush sceNetAdhocPtpFlush
func SceNetAdhocPtpFlush(id int32, timeout uint32, nonblock int32) int32

//go:linkname SceNetAdhocPtpClose sceNetAdhocPtpClose
func SceNetAdhocPtpClose(id int32, unk1 int32) int32

//go:linkname SceNetAdhocGetPtpStat sceNetAdhocGetPtpStat
func SceNetAdhocGetPtpStat(size unsafe.Pointer, stat unsafe.Pointer) int32
