// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputilsforkernel.h

// Package utilsforkernel provides direct TinyGo bindings for psputilsforkernel.h.
package utilsforkernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

//go:linkname SceKernelGzipDecompress sceKernelGzipDecompress
func SceKernelGzipDecompress(dest unsafe.Pointer, destSize int32, src unsafe.Pointer, src_out unsafe.Pointer) int32

//go:linkname SceKernelDeflateDecompress sceKernelDeflateDecompress
func SceKernelDeflateDecompress(dest unsafe.Pointer, destSize int32, src unsafe.Pointer, src_out unsafe.Pointer) int32

//go:linkname SceKernelDcacheInvalidateAll sceKernelDcacheInvalidateAll
func SceKernelDcacheInvalidateAll()

//go:linkname SceKernelDcacheProbe sceKernelDcacheProbe
func SceKernelDcacheProbe(addr unsafe.Pointer) int32

//go:linkname SceKernelIcacheInvalidateAll sceKernelIcacheInvalidateAll
func SceKernelIcacheInvalidateAll()

//go:linkname SceKernelIcacheInvalidateRange sceKernelIcacheInvalidateRange
func SceKernelIcacheInvalidateRange(addr unsafe.Pointer, size uint32)

//go:linkname SceKernelIcacheProbe sceKernelIcacheProbe
func SceKernelIcacheProbe(addr unsafe.Pointer) int32
