// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsircs.h

// Package sircs provides direct TinyGo bindings for pspsircs.h.
package sircs

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSircsSend sceSircsSend
func SceSircsSend(sd unsafe.Pointer, count int32) int32
