// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psphprm.h

// Package hprm provides direct TinyGo bindings for psphprm.h.
package hprm

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_HPRM_PLAYPAUSE = 1
	PSP_HPRM_FORWARD   = 4
	PSP_HPRM_BACK      = 8
	PSP_HPRM_VOL_UP    = 16
	PSP_HPRM_VOL_DOWN  = 32
	PSP_HPRM_HOLD      = 128
)

//go:linkname SceHprmPeekCurrentKey sceHprmPeekCurrentKey
func SceHprmPeekCurrentKey(key unsafe.Pointer) int32

//go:linkname SceHprmPeekLatch sceHprmPeekLatch
func SceHprmPeekLatch(latch unsafe.Pointer) int32

//go:linkname SceHprmReadLatch sceHprmReadLatch
func SceHprmReadLatch(latch unsafe.Pointer) int32

//go:linkname SceHprmIsHeadphoneExist sceHprmIsHeadphoneExist
func SceHprmIsHeadphoneExist() int32

//go:linkname SceHprmIsRemoteExist sceHprmIsRemoteExist
func SceHprmIsRemoteExist() int32

//go:linkname SceHprmIsMicrophoneExist sceHprmIsMicrophoneExist
func SceHprmIsMicrophoneExist() int32
