// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmpeg.h

// Package mpeg provides direct TinyGo bindings for pspmpeg.h.
package mpeg

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceMpegInit sceMpegInit
func SceMpegInit() int32

//go:linkname SceMpegFinish sceMpegFinish
func SceMpegFinish() int32

//go:linkname SceMpegRingbufferQueryMemSize sceMpegRingbufferQueryMemSize
func SceMpegRingbufferQueryMemSize(iPackets int32) int32

//go:linkname SceMpegRingbufferConstruct sceMpegRingbufferConstruct
func SceMpegRingbufferConstruct(Ringbuffer unsafe.Pointer, iPackets int32, pData unsafe.Pointer, iSize int32, Callback unsafe.Pointer, pCBparam unsafe.Pointer) int32

//go:linkname SceMpegRingbufferDestruct sceMpegRingbufferDestruct
func SceMpegRingbufferDestruct(Ringbuffer unsafe.Pointer) int32

//go:linkname SceMpegRingbufferAvailableSize sceMpegRingbufferAvailableSize
func SceMpegRingbufferAvailableSize(Ringbuffer unsafe.Pointer) int32

//go:linkname SceMpegRingbufferPut sceMpegRingbufferPut
func SceMpegRingbufferPut(Ringbuffer unsafe.Pointer, iNumPackets int32, iAvailable int32) int32

//go:linkname SceMpegQueryMemSize sceMpegQueryMemSize
func SceMpegQueryMemSize(iUnk int32) int32

//go:linkname SceMpegCreate sceMpegCreate
func SceMpegCreate(Mpeg unsafe.Pointer, pData unsafe.Pointer, iSize int32, Ringbuffer unsafe.Pointer, iFrameWidth int32, iUnk1 int32, iUnk2 int32) int32

//go:linkname SceMpegDelete sceMpegDelete
func SceMpegDelete(Mpeg unsafe.Pointer) int32

//go:linkname SceMpegQueryStreamOffset sceMpegQueryStreamOffset
func SceMpegQueryStreamOffset(Mpeg unsafe.Pointer, pBuffer unsafe.Pointer, iOffset unsafe.Pointer) int32

//go:linkname SceMpegQueryStreamSize sceMpegQueryStreamSize
func SceMpegQueryStreamSize(pBuffer unsafe.Pointer, iSize unsafe.Pointer) int32

//go:linkname SceMpegRegistStream sceMpegRegistStream
func SceMpegRegistStream(Mpeg unsafe.Pointer, iStreamID int32, iUnk int32) unsafe.Pointer

//go:linkname SceMpegUnRegistStream sceMpegUnRegistStream
func SceMpegUnRegistStream(Mpeg unsafe.Pointer, pStream unsafe.Pointer) int32

//go:linkname SceMpegFlushAllStream sceMpegFlushAllStream
func SceMpegFlushAllStream(Mpeg unsafe.Pointer) int32

//go:linkname SceMpegMallocAvcEsBuf sceMpegMallocAvcEsBuf
func SceMpegMallocAvcEsBuf(Mpeg unsafe.Pointer) int32

//go:linkname SceMpegFreeAvcEsBuf sceMpegFreeAvcEsBuf
func SceMpegFreeAvcEsBuf(Mpeg unsafe.Pointer, pBuf unsafe.Pointer) int32

//go:linkname SceMpegQueryAtracEsSize sceMpegQueryAtracEsSize
func SceMpegQueryAtracEsSize(Mpeg unsafe.Pointer, iEsSize unsafe.Pointer, iOutSize unsafe.Pointer) int32

//go:linkname SceMpegInitAu sceMpegInitAu
func SceMpegInitAu(Mpeg unsafe.Pointer, pEsBuffer unsafe.Pointer, pAu unsafe.Pointer) int32

//go:linkname SceMpegGetAvcAu sceMpegGetAvcAu
func SceMpegGetAvcAu(Mpeg unsafe.Pointer, pStream unsafe.Pointer, pAu unsafe.Pointer, iUnk unsafe.Pointer) int32

//go:linkname SceMpegAvcDecodeMode sceMpegAvcDecodeMode
func SceMpegAvcDecodeMode(Mpeg unsafe.Pointer, pMode unsafe.Pointer) int32

//go:linkname SceMpegAvcDecode sceMpegAvcDecode
func SceMpegAvcDecode(Mpeg unsafe.Pointer, pAu unsafe.Pointer, iFrameWidth int32, pBuffer unsafe.Pointer, iInit unsafe.Pointer) int32

//go:linkname SceMpegAvcDecodeStop sceMpegAvcDecodeStop
func SceMpegAvcDecodeStop(Mpeg unsafe.Pointer, iFrameWidth int32, pBuffer unsafe.Pointer, iStatus unsafe.Pointer) int32

//go:linkname SceMpegGetAtracAu sceMpegGetAtracAu
func SceMpegGetAtracAu(Mpeg unsafe.Pointer, pStream unsafe.Pointer, pAu unsafe.Pointer, pUnk unsafe.Pointer) int32

//go:linkname SceMpegAtracDecode sceMpegAtracDecode
func SceMpegAtracDecode(Mpeg unsafe.Pointer, pAu unsafe.Pointer, pBuffer unsafe.Pointer, iInit int32) int32
