// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspge.h

// Package ge provides direct TinyGo bindings for pspge.h.
package ge

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_GE_MATRIX_BONE0 = 0
	PSP_GE_LIST_DONE    = 0
)

//go:linkname SceGeEdramGetSize sceGeEdramGetSize
func SceGeEdramGetSize() uint32

//go:linkname SceGeEdramSetSize sceGeEdramSetSize
func SceGeEdramSetSize(size int32) int32

//go:linkname SceGeEdramGetAddr sceGeEdramGetAddr
func SceGeEdramGetAddr() unsafe.Pointer

//go:linkname SceGeGetCmd sceGeGetCmd
func SceGeGetCmd(cmd int32) uint32

//go:linkname SceGeGetMtx sceGeGetMtx
func SceGeGetMtx(typeValue int32, matrix unsafe.Pointer) int32

//go:linkname SceGeGetStack sceGeGetStack
func SceGeGetStack(stackId int32, stack unsafe.Pointer) int32

//go:linkname SceGeSaveContext sceGeSaveContext
func SceGeSaveContext(context unsafe.Pointer) int32

//go:linkname SceGeRestoreContext sceGeRestoreContext
func SceGeRestoreContext(context unsafe.Pointer) int32

//go:linkname SceGeListEnQueue sceGeListEnQueue
func SceGeListEnQueue(list unsafe.Pointer, stall unsafe.Pointer, cbid int32, arg unsafe.Pointer) int32

//go:linkname SceGeListEnQueueHead sceGeListEnQueueHead
func SceGeListEnQueueHead(list unsafe.Pointer, stall unsafe.Pointer, cbid int32, arg unsafe.Pointer) int32

//go:linkname SceGeListDeQueue sceGeListDeQueue
func SceGeListDeQueue(qid int32) int32

//go:linkname SceGeListUpdateStallAddr sceGeListUpdateStallAddr
func SceGeListUpdateStallAddr(qid int32, stall unsafe.Pointer) int32

//go:linkname SceGeListSync sceGeListSync
func SceGeListSync(qid int32, syncType int32) int32

//go:linkname SceGeDrawSync sceGeDrawSync
func SceGeDrawSync(syncType int32) int32

//go:linkname SceGeSetCallback sceGeSetCallback
func SceGeSetCallback(cb unsafe.Pointer) int32

//go:linkname SceGeUnsetCallback sceGeUnsetCallback
func SceGeUnsetCallback(cbid int32) int32

//go:linkname SceGeBreak sceGeBreak
func SceGeBreak(mode int32, pParam unsafe.Pointer) int32

//go:linkname SceGeContinue sceGeContinue
func SceGeContinue() int32

//go:linkname SceGeEdramSetAddrTranslation sceGeEdramSetAddrTranslation
func SceGeEdramSetAddrTranslation(width int32) int32
