// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet.h

// Package net provides direct TinyGo bindings for pspnet.h.
package net

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceNetInit sceNetInit
func SceNetInit(poolsize int32, calloutprio int32, calloutstack int32, netintrprio int32, netintrstack int32) int32

//go:linkname SceNetTerm sceNetTerm
func SceNetTerm() int32

//go:linkname SceNetFreeThreadinfo sceNetFreeThreadinfo
func SceNetFreeThreadinfo(thid int32) int32

//go:linkname SceNetThreadAbort sceNetThreadAbort
func SceNetThreadAbort(thid int32) int32

//go:linkname SceNetEtherStrton sceNetEtherStrton
func SceNetEtherStrton(name unsafe.Pointer, mac unsafe.Pointer)

//go:linkname SceNetEtherNtostr sceNetEtherNtostr
func SceNetEtherNtostr(mac unsafe.Pointer, name unsafe.Pointer)

//go:linkname SceNetGetLocalEtherAddr sceNetGetLocalEtherAddr
func SceNetGetLocalEtherAddr(mac unsafe.Pointer) int32

//go:linkname SceNetGetMallocStat sceNetGetMallocStat
func SceNetGetMallocStat(stat unsafe.Pointer) int32
