// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsysreg.h

// Package sysreg provides direct TinyGo bindings for pspsysreg.h.
package sysreg

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSysregMeResetEnable sceSysregMeResetEnable
func SceSysregMeResetEnable() int32

//go:linkname SceSysregMeResetDisable sceSysregMeResetDisable
func SceSysregMeResetDisable() int32

//go:linkname SceSysregVmeResetEnable sceSysregVmeResetEnable
func SceSysregVmeResetEnable() int32

//go:linkname SceSysregVmeResetDisable sceSysregVmeResetDisable
func SceSysregVmeResetDisable() int32

//go:linkname SceSysregMeBusClockEnable sceSysregMeBusClockEnable
func SceSysregMeBusClockEnable() int32

//go:linkname SceSysregMeBusClockDisable sceSysregMeBusClockDisable
func SceSysregMeBusClockDisable() int32

//go:linkname SceSysregGetTachyonVersion sceSysregGetTachyonVersion
func SceSysregGetTachyonVersion() int32

//go:linkname SceSysregKirkBusClockEnable sceSysregKirkBusClockEnable
func SceSysregKirkBusClockEnable() int32

//go:linkname SceSysregAtaBusClockEnable sceSysregAtaBusClockEnable
func SceSysregAtaBusClockEnable() int32
