// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: infernoctrl.h

// Package infernoctrl provides direct TinyGo bindings for infernoctrl.h.
package infernoctrl

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspinfernoDriver() }

//go:linkname requirePspinfernoDriver pspsdk_go_require_pspinferno_driver
func requirePspinfernoDriver()

const (
	INFERNO_CACHE_DISABLED = 0
	INFERNO_CACHE_LRU      = 1
	INFERNO_CACHE_RR       = 2
)

//go:linkname InfernoIsoRead infernoIsoRead
func InfernoIsoRead(offset uint32, ptr unsafe.Pointer, data_len uint32) int32

//go:linkname InfernoSetDiscType infernoSetDiscType
func InfernoSetDiscType(typeValue int32) int32

//go:linkname InfernoCacheSetPolicy infernoCacheSetPolicy
func InfernoCacheSetPolicy(policy int32)

//go:linkname InfernoCacheInit infernoCacheInit
func InfernoCacheInit(cache_size int32, cache_num int32, partition int32) int32

//go:linkname InfernoSetUmdDelay infernoSetUmdDelay
func InfernoSetUmdDelay(seek int32, speed int32)
