// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmoduleexport.h

// Package moduleexport provides direct TinyGo bindings for pspmoduleexport.h.
package moduleexport

import "unsafe"

var _ unsafe.Pointer
