// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspdecrypt.h

// Package decrypt provides direct TinyGo bindings for pspdecrypt.h.
package decrypt

import "unsafe"

var _ unsafe.Pointer

//go:linkname PspDecryptPRX pspDecryptPRX
func PspDecryptPRX(inbuf unsafe.Pointer, outbuf unsafe.Pointer, size int32) int32

//go:linkname PspSignCheck pspSignCheck
func PspSignCheck(buf unsafe.Pointer) int32

//go:linkname PspUnsignCheck pspUnsignCheck
func PspUnsignCheck(buf unsafe.Pointer) int32

//go:linkname PspIsSignChecked pspIsSignChecked
func PspIsSignChecked(buf unsafe.Pointer) int32

//go:linkname PspDecryptIPL1 pspDecryptIPL1
func PspDecryptIPL1(pbIn unsafe.Pointer, pbOut unsafe.Pointer, cbIn int32) int32

//go:linkname PspLinearizeIPL2 pspLinearizeIPL2
func PspLinearizeIPL2(pbIn unsafe.Pointer, pbOut unsafe.Pointer, cbIn int32) int32

//go:linkname PspDecryptIPL3 pspDecryptIPL3
func PspDecryptIPL3(pbIn unsafe.Pointer, pbOut unsafe.Pointer, cbIn int32) int32

//go:linkname PspIsCompressed pspIsCompressed
func PspIsCompressed(buf unsafe.Pointer) int32

//go:linkname PspDecompress pspDecompress
func PspDecompress(inbuf unsafe.Pointer, outbuf unsafe.Pointer, outcapacity int32) int32

//go:linkname PspDecryptTable pspDecryptTable
func PspDecryptTable(buf1 unsafe.Pointer, buf2 unsafe.Pointer, size int32, mode int32) int32
