// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmodulemgr_kernel.h

// Package modulemgr_kernel provides direct TinyGo bindings for pspmodulemgr_kernel.h.
package modulemgr_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

//go:linkname SceKernelGetModuleList sceKernelGetModuleList
func SceKernelGetModuleList(readbufsize int32, readbuf unsafe.Pointer) int32

//go:linkname SceKernelModuleCount sceKernelModuleCount
func SceKernelModuleCount() int32

//go:linkname SceKernelLoadModuleBuffer sceKernelLoadModuleBuffer
func SceKernelLoadModuleBuffer(buf unsafe.Pointer, bufsize uint32, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleWithApitype2 sceKernelLoadModuleWithApitype2
func SceKernelLoadModuleWithApitype2(apitype int32, path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname SceKernelLoadModuleBufferBootInitBtcnf sceKernelLoadModuleBufferBootInitBtcnf
func SceKernelLoadModuleBufferBootInitBtcnf(bufsize int32, buf unsafe.Pointer, flags int32, option unsafe.Pointer) int32
