// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspthreadman.h

// Package threadman provides direct TinyGo bindings for pspthreadman.h.
package threadman

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_MODULE_USER                    = 0
	PSP_MODULE_NO_STOP                 = 1
	PSP_MODULE_SINGLE_LOAD             = 2
	PSP_MODULE_SINGLE_START            = 4
	PSP_MODULE_KERNEL                  = 4096
	PSP_THREAD_ATTR_VFPU               = 16384
	PSP_THREAD_ATTR_USER               = 2147483648
	PSP_THREAD_ATTR_USBWLAN            = 2684354560
	PSP_THREAD_ATTR_VSH                = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM       = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK       = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK        = 2097152
	PSP_THREAD_RUNNING                 = 1
	PSP_THREAD_READY                   = 2
	PSP_THREAD_WAITING                 = 4
	PSP_THREAD_SUSPEND                 = 8
	PSP_THREAD_STOPPED                 = 16
	PSP_THREAD_KILLED                  = 32
	PSP_LW_MUTEX_ATTR_THFIFO           = 0
	PSP_LW_MUTEX_ATTR_THPRI            = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE        = 512
	PSP_EVENT_WAITSINGLE               = 0
	PSP_EVENT_WAITMULTIPLE             = 512
	PSP_EVENT_WAITAND                  = 0
	PSP_EVENT_WAITOR                   = 1
	PSP_EVENT_WAITCLEAR                = 32
	SCE_KERNEL_TMID_Thread             = 1
	SCE_KERNEL_TMID_Semaphore          = 2
	SCE_KERNEL_TMID_EventFlag          = 3
	SCE_KERNEL_TMID_Mbox               = 4
	SCE_KERNEL_TMID_Vpl                = 5
	SCE_KERNEL_TMID_Fpl                = 6
	SCE_KERNEL_TMID_Mpipe              = 7
	SCE_KERNEL_TMID_Callback           = 8
	SCE_KERNEL_TMID_ThreadEventHandler = 9
	SCE_KERNEL_TMID_Alarm              = 10
	SCE_KERNEL_TMID_VTimer             = 11
	SCE_KERNEL_TMID_SleepThread        = 64
	SCE_KERNEL_TMID_DelayThread        = 65
	SCE_KERNEL_TMID_SuspendThread      = 66
	SCE_KERNEL_TMID_DormantThread      = 67
	THREADEVENT_ALL                    = 4294967295
	THREADEVENT_KERN                   = 4294967288
	THREADEVENT_USER                   = 4294967280
	THREADEVENT_CURRENT                = 0
	THREAD_CREATE                      = 1
	THREAD_START                       = 2
	THREAD_EXIT                        = 4
	THREAD_DELETE                      = 8
)

//go:linkname SceKernelCreateThread sceKernelCreateThread
func SceKernelCreateThread(name unsafe.Pointer, entry unsafe.Pointer, initPriority int32, stackSize int32, attr uint32, option unsafe.Pointer) int32

//go:linkname SceKernelDeleteThread sceKernelDeleteThread
func SceKernelDeleteThread(thid int32) int32

//go:linkname SceKernelStartThread sceKernelStartThread
func SceKernelStartThread(thid int32, arglen uint32, argp unsafe.Pointer) int32

//go:linkname SceKernelExitThread sceKernelExitThread
func SceKernelExitThread(status int32) int32

//go:linkname SceKernelExitDeleteThread sceKernelExitDeleteThread
func SceKernelExitDeleteThread(status int32) int32

//go:linkname SceKernelTerminateThread sceKernelTerminateThread
func SceKernelTerminateThread(thid int32) int32

//go:linkname SceKernelTerminateDeleteThread sceKernelTerminateDeleteThread
func SceKernelTerminateDeleteThread(thid int32) int32

//go:linkname SceKernelSuspendDispatchThread sceKernelSuspendDispatchThread
func SceKernelSuspendDispatchThread() int32

//go:linkname SceKernelResumeDispatchThread sceKernelResumeDispatchThread
func SceKernelResumeDispatchThread(state int32) int32

//go:linkname SceKernelSleepThread sceKernelSleepThread
func SceKernelSleepThread() int32

//go:linkname SceKernelSleepThreadCB sceKernelSleepThreadCB
func SceKernelSleepThreadCB() int32

//go:linkname SceKernelWakeupThread sceKernelWakeupThread
func SceKernelWakeupThread(thid int32) int32

//go:linkname SceKernelCancelWakeupThread sceKernelCancelWakeupThread
func SceKernelCancelWakeupThread(thid int32) int32

//go:linkname SceKernelSuspendThread sceKernelSuspendThread
func SceKernelSuspendThread(thid int32) int32

//go:linkname SceKernelResumeThread sceKernelResumeThread
func SceKernelResumeThread(thid int32) int32

//go:linkname SceKernelWaitThreadEnd sceKernelWaitThreadEnd
func SceKernelWaitThreadEnd(thid int32, timeout unsafe.Pointer) int32

//go:linkname SceKernelWaitThreadEndCB sceKernelWaitThreadEndCB
func SceKernelWaitThreadEndCB(thid int32, timeout unsafe.Pointer) int32

//go:linkname SceKernelDelayThread sceKernelDelayThread
func SceKernelDelayThread(delay uint32) int32

//go:linkname SceKernelDelayThreadCB sceKernelDelayThreadCB
func SceKernelDelayThreadCB(delay uint32) int32

//go:linkname SceKernelDelaySysClockThread sceKernelDelaySysClockThread
func SceKernelDelaySysClockThread(delay unsafe.Pointer) int32

//go:linkname SceKernelDelaySysClockThreadCB sceKernelDelaySysClockThreadCB
func SceKernelDelaySysClockThreadCB(delay unsafe.Pointer) int32

//go:linkname SceKernelChangeCurrentThreadAttr sceKernelChangeCurrentThreadAttr
func SceKernelChangeCurrentThreadAttr(unknown int32, attr uint32) int32

//go:linkname SceKernelChangeThreadPriority sceKernelChangeThreadPriority
func SceKernelChangeThreadPriority(thid int32, priority int32) int32

//go:linkname SceKernelRotateThreadReadyQueue sceKernelRotateThreadReadyQueue
func SceKernelRotateThreadReadyQueue(priority int32) int32

//go:linkname SceKernelReleaseWaitThread sceKernelReleaseWaitThread
func SceKernelReleaseWaitThread(thid int32) int32

//go:linkname SceKernelGetThreadId sceKernelGetThreadId
func SceKernelGetThreadId() int32

//go:linkname SceKernelGetThreadCurrentPriority sceKernelGetThreadCurrentPriority
func SceKernelGetThreadCurrentPriority() int32

//go:linkname SceKernelGetThreadExitStatus sceKernelGetThreadExitStatus
func SceKernelGetThreadExitStatus(thid int32) int32

//go:linkname SceKernelCheckThreadStack sceKernelCheckThreadStack
func SceKernelCheckThreadStack() int32

//go:linkname SceKernelGetThreadStackFreeSize sceKernelGetThreadStackFreeSize
func SceKernelGetThreadStackFreeSize(thid int32) int32

//go:linkname SceKernelReferThreadStatus sceKernelReferThreadStatus
func SceKernelReferThreadStatus(thid int32, info unsafe.Pointer) int32

//go:linkname SceKernelReferThreadRunStatus sceKernelReferThreadRunStatus
func SceKernelReferThreadRunStatus(thid int32, status unsafe.Pointer) int32

//go:linkname SceKernelCreateSema sceKernelCreateSema
func SceKernelCreateSema(name unsafe.Pointer, attr uint32, initVal int32, maxVal int32, option unsafe.Pointer) int32

//go:linkname SceKernelDeleteSema sceKernelDeleteSema
func SceKernelDeleteSema(semaid int32) int32

//go:linkname SceKernelSignalSema sceKernelSignalSema
func SceKernelSignalSema(semaid int32, signal int32) int32

//go:linkname SceKernelWaitSema sceKernelWaitSema
func SceKernelWaitSema(semaid int32, signal int32, timeout unsafe.Pointer) int32

//go:linkname SceKernelWaitSemaCB sceKernelWaitSemaCB
func SceKernelWaitSemaCB(semaid int32, signal int32, timeout unsafe.Pointer) int32

//go:linkname SceKernelPollSema sceKernelPollSema
func SceKernelPollSema(semaid int32, signal int32) int32

//go:linkname SceKernelReferSemaStatus sceKernelReferSemaStatus
func SceKernelReferSemaStatus(semaid int32, info unsafe.Pointer) int32

//go:linkname SceKernelCreateLwMutex sceKernelCreateLwMutex
func SceKernelCreateLwMutex(workarea unsafe.Pointer, name unsafe.Pointer, attr uint32, initialCount int32, optionsPtr unsafe.Pointer) int32

//go:linkname SceKernelDeleteLwMutex sceKernelDeleteLwMutex
func SceKernelDeleteLwMutex(workarea unsafe.Pointer) int32

//go:linkname SceKernelTryLockLwMutex sceKernelTryLockLwMutex
func SceKernelTryLockLwMutex(workarea unsafe.Pointer, lockCount int32) int32

//go:linkname SceKernelLockLwMutex sceKernelLockLwMutex
func SceKernelLockLwMutex(workarea unsafe.Pointer, lockCount int32, pTimeout unsafe.Pointer) int32

//go:linkname SceKernelUnlockLwMutex sceKernelUnlockLwMutex
func SceKernelUnlockLwMutex(workarea unsafe.Pointer, lockCount int32) int32

//go:linkname SceKernelCreateEventFlag sceKernelCreateEventFlag
func SceKernelCreateEventFlag(name unsafe.Pointer, attr int32, bits int32, opt unsafe.Pointer) int32

//go:linkname SceKernelSetEventFlag sceKernelSetEventFlag
func SceKernelSetEventFlag(evid int32, bits uint32) int32

//go:linkname SceKernelClearEventFlag sceKernelClearEventFlag
func SceKernelClearEventFlag(evid int32, bits uint32) int32

//go:linkname SceKernelPollEventFlag sceKernelPollEventFlag
func SceKernelPollEventFlag(evid int32, bits uint32, wait uint32, outBits unsafe.Pointer) int32

//go:linkname SceKernelWaitEventFlag sceKernelWaitEventFlag
func SceKernelWaitEventFlag(evid int32, bits uint32, wait uint32, outBits unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelWaitEventFlagCB sceKernelWaitEventFlagCB
func SceKernelWaitEventFlagCB(evid int32, bits uint32, wait uint32, outBits unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelDeleteEventFlag sceKernelDeleteEventFlag
func SceKernelDeleteEventFlag(evid int32) int32

//go:linkname SceKernelReferEventFlagStatus sceKernelReferEventFlagStatus
func SceKernelReferEventFlagStatus(event int32, status unsafe.Pointer) int32

//go:linkname SceKernelCreateMbx sceKernelCreateMbx
func SceKernelCreateMbx(name unsafe.Pointer, attr uint32, option unsafe.Pointer) int32

//go:linkname SceKernelDeleteMbx sceKernelDeleteMbx
func SceKernelDeleteMbx(mbxid int32) int32

//go:linkname SceKernelSendMbx sceKernelSendMbx
func SceKernelSendMbx(mbxid int32, message unsafe.Pointer) int32

//go:linkname SceKernelReceiveMbx sceKernelReceiveMbx
func SceKernelReceiveMbx(mbxid int32, pmessage unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelReceiveMbxCB sceKernelReceiveMbxCB
func SceKernelReceiveMbxCB(mbxid int32, pmessage unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelPollMbx sceKernelPollMbx
func SceKernelPollMbx(mbxid int32, pmessage unsafe.Pointer) int32

//go:linkname SceKernelCancelReceiveMbx sceKernelCancelReceiveMbx
func SceKernelCancelReceiveMbx(mbxid int32, pnum unsafe.Pointer) int32

//go:linkname SceKernelReferMbxStatus sceKernelReferMbxStatus
func SceKernelReferMbxStatus(mbxid int32, info unsafe.Pointer) int32

//go:linkname SceKernelSetAlarm sceKernelSetAlarm
func SceKernelSetAlarm(clock uint32, handler unsafe.Pointer, common unsafe.Pointer) int32

//go:linkname SceKernelSetSysClockAlarm sceKernelSetSysClockAlarm
func SceKernelSetSysClockAlarm(clock unsafe.Pointer, handler unsafe.Pointer, common unsafe.Pointer) int32

//go:linkname SceKernelCancelAlarm sceKernelCancelAlarm
func SceKernelCancelAlarm(alarmid int32) int32

//go:linkname SceKernelReferAlarmStatus sceKernelReferAlarmStatus
func SceKernelReferAlarmStatus(alarmid int32, info unsafe.Pointer) int32

//go:linkname SceKernelCreateCallback sceKernelCreateCallback
func SceKernelCreateCallback(name unsafe.Pointer, funcValue unsafe.Pointer, arg unsafe.Pointer) int32

//go:linkname SceKernelReferCallbackStatus sceKernelReferCallbackStatus
func SceKernelReferCallbackStatus(cb int32, status unsafe.Pointer) int32

//go:linkname SceKernelDeleteCallback sceKernelDeleteCallback
func SceKernelDeleteCallback(cb int32) int32

//go:linkname SceKernelNotifyCallback sceKernelNotifyCallback
func SceKernelNotifyCallback(cb int32, arg2 int32) int32

//go:linkname SceKernelCancelCallback sceKernelCancelCallback
func SceKernelCancelCallback(cb int32) int32

//go:linkname SceKernelGetCallbackCount sceKernelGetCallbackCount
func SceKernelGetCallbackCount(cb int32) int32

//go:linkname SceKernelCheckCallback sceKernelCheckCallback
func SceKernelCheckCallback() int32

//go:linkname SceKernelGetThreadmanIdList sceKernelGetThreadmanIdList
func SceKernelGetThreadmanIdList(typeValue int32, readbuf unsafe.Pointer, readbufsize int32, idcount unsafe.Pointer) int32

//go:linkname SceKernelReferSystemStatus sceKernelReferSystemStatus
func SceKernelReferSystemStatus(status unsafe.Pointer) int32

//go:linkname SceKernelCreateMsgPipe sceKernelCreateMsgPipe
func SceKernelCreateMsgPipe(name unsafe.Pointer, part int32, attr int32, unk1 unsafe.Pointer, opt unsafe.Pointer) int32

//go:linkname SceKernelDeleteMsgPipe sceKernelDeleteMsgPipe
func SceKernelDeleteMsgPipe(uid int32) int32

//go:linkname SceKernelSendMsgPipe sceKernelSendMsgPipe
func SceKernelSendMsgPipe(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelSendMsgPipeCB sceKernelSendMsgPipeCB
func SceKernelSendMsgPipeCB(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelTrySendMsgPipe sceKernelTrySendMsgPipe
func SceKernelTrySendMsgPipe(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer) int32

//go:linkname SceKernelReceiveMsgPipe sceKernelReceiveMsgPipe
func SceKernelReceiveMsgPipe(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelReceiveMsgPipeCB sceKernelReceiveMsgPipeCB
func SceKernelReceiveMsgPipeCB(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelTryReceiveMsgPipe sceKernelTryReceiveMsgPipe
func SceKernelTryReceiveMsgPipe(uid int32, message unsafe.Pointer, size uint32, unk1 int32, unk2 unsafe.Pointer) int32

//go:linkname SceKernelCancelMsgPipe sceKernelCancelMsgPipe
func SceKernelCancelMsgPipe(uid int32, psend unsafe.Pointer, precv unsafe.Pointer) int32

//go:linkname SceKernelReferMsgPipeStatus sceKernelReferMsgPipeStatus
func SceKernelReferMsgPipeStatus(uid int32, info unsafe.Pointer) int32

//go:linkname SceKernelCreateVpl sceKernelCreateVpl
func SceKernelCreateVpl(name unsafe.Pointer, part int32, attr int32, size uint32, opt unsafe.Pointer) int32

//go:linkname SceKernelDeleteVpl sceKernelDeleteVpl
func SceKernelDeleteVpl(uid int32) int32

//go:linkname SceKernelAllocateVpl sceKernelAllocateVpl
func SceKernelAllocateVpl(uid int32, size uint32, data unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelAllocateVplCB sceKernelAllocateVplCB
func SceKernelAllocateVplCB(uid int32, size uint32, data unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelTryAllocateVpl sceKernelTryAllocateVpl
func SceKernelTryAllocateVpl(uid int32, size uint32, data unsafe.Pointer) int32

//go:linkname SceKernelFreeVpl sceKernelFreeVpl
func SceKernelFreeVpl(uid int32, data unsafe.Pointer) int32

//go:linkname SceKernelCancelVpl sceKernelCancelVpl
func SceKernelCancelVpl(uid int32, pnum unsafe.Pointer) int32

//go:linkname SceKernelReferVplStatus sceKernelReferVplStatus
func SceKernelReferVplStatus(uid int32, info unsafe.Pointer) int32

//go:linkname SceKernelCreateFpl sceKernelCreateFpl
func SceKernelCreateFpl(name unsafe.Pointer, part int32, attr int32, size uint32, blocks uint32, opt unsafe.Pointer) int32

//go:linkname SceKernelDeleteFpl sceKernelDeleteFpl
func SceKernelDeleteFpl(uid int32) int32

//go:linkname SceKernelAllocateFpl sceKernelAllocateFpl
func SceKernelAllocateFpl(uid int32, data unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelAllocateFplCB sceKernelAllocateFplCB
func SceKernelAllocateFplCB(uid int32, data unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceKernelTryAllocateFpl sceKernelTryAllocateFpl
func SceKernelTryAllocateFpl(uid int32, data unsafe.Pointer) int32

//go:linkname SceKernelFreeFpl sceKernelFreeFpl
func SceKernelFreeFpl(uid int32, data unsafe.Pointer) int32

//go:linkname SceKernelCancelFpl sceKernelCancelFpl
func SceKernelCancelFpl(uid int32, pnum unsafe.Pointer) int32

//go:linkname SceKernelReferFplStatus sceKernelReferFplStatus
func SceKernelReferFplStatus(uid int32, info unsafe.Pointer) int32

//go:linkname _sceKernelReturnFromTimerHandler _sceKernelReturnFromTimerHandler
func _sceKernelReturnFromTimerHandler()

//go:linkname _sceKernelReturnFromCallback _sceKernelReturnFromCallback
func _sceKernelReturnFromCallback()

//go:linkname SceKernelUSec2SysClock sceKernelUSec2SysClock
func SceKernelUSec2SysClock(usec uint32, clock unsafe.Pointer) int32

//go:linkname SceKernelUSec2SysClockWide sceKernelUSec2SysClockWide
func SceKernelUSec2SysClockWide(usec uint32) int64

//go:linkname SceKernelSysClock2USec sceKernelSysClock2USec
func SceKernelSysClock2USec(clock unsafe.Pointer, low unsafe.Pointer, high unsafe.Pointer) int32

//go:linkname SceKernelSysClock2USecWide sceKernelSysClock2USecWide
func SceKernelSysClock2USecWide(clock int64, low unsafe.Pointer, high unsafe.Pointer) int32

//go:linkname SceKernelGetSystemTime sceKernelGetSystemTime
func SceKernelGetSystemTime(time unsafe.Pointer) int32

//go:linkname SceKernelGetSystemTimeWide sceKernelGetSystemTimeWide
func SceKernelGetSystemTimeWide() int64

//go:linkname SceKernelGetSystemTimeLow sceKernelGetSystemTimeLow
func SceKernelGetSystemTimeLow() uint32

//go:linkname SceKernelCreateVTimer sceKernelCreateVTimer
func SceKernelCreateVTimer(name unsafe.Pointer, opt unsafe.Pointer) int32

//go:linkname SceKernelDeleteVTimer sceKernelDeleteVTimer
func SceKernelDeleteVTimer(uid int32) int32

//go:linkname SceKernelGetVTimerBase sceKernelGetVTimerBase
func SceKernelGetVTimerBase(uid int32, base unsafe.Pointer) int32

//go:linkname SceKernelGetVTimerBaseWide sceKernelGetVTimerBaseWide
func SceKernelGetVTimerBaseWide(uid int32) int64

//go:linkname SceKernelGetVTimerTime sceKernelGetVTimerTime
func SceKernelGetVTimerTime(uid int32, time unsafe.Pointer) int32

//go:linkname SceKernelGetVTimerTimeWide sceKernelGetVTimerTimeWide
func SceKernelGetVTimerTimeWide(uid int32) int64

//go:linkname SceKernelSetVTimerTime sceKernelSetVTimerTime
func SceKernelSetVTimerTime(uid int32, time unsafe.Pointer) int32

//go:linkname SceKernelSetVTimerTimeWide sceKernelSetVTimerTimeWide
func SceKernelSetVTimerTimeWide(uid int32, time int64) int64

//go:linkname SceKernelStartVTimer sceKernelStartVTimer
func SceKernelStartVTimer(uid int32) int32

//go:linkname SceKernelStopVTimer sceKernelStopVTimer
func SceKernelStopVTimer(uid int32) int32

//go:linkname SceKernelSetVTimerHandler sceKernelSetVTimerHandler
func SceKernelSetVTimerHandler(uid int32, time unsafe.Pointer, handler unsafe.Pointer, common unsafe.Pointer) int32

//go:linkname SceKernelSetVTimerHandlerWide sceKernelSetVTimerHandlerWide
func SceKernelSetVTimerHandlerWide(uid int32, time int64, handler unsafe.Pointer, common unsafe.Pointer) int32

//go:linkname SceKernelCancelVTimerHandler sceKernelCancelVTimerHandler
func SceKernelCancelVTimerHandler(uid int32) int32

//go:linkname SceKernelReferVTimerStatus sceKernelReferVTimerStatus
func SceKernelReferVTimerStatus(uid int32, info unsafe.Pointer) int32

//go:linkname _sceKernelExitThread _sceKernelExitThread
func _sceKernelExitThread()

//go:linkname SceKernelGetThreadmanIdType sceKernelGetThreadmanIdType
func SceKernelGetThreadmanIdType(uid int32) int32

//go:linkname SceKernelRegisterThreadEventHandler sceKernelRegisterThreadEventHandler
func SceKernelRegisterThreadEventHandler(name unsafe.Pointer, threadID int32, mask int32, handler unsafe.Pointer, common unsafe.Pointer) int32

//go:linkname SceKernelReleaseThreadEventHandler sceKernelReleaseThreadEventHandler
func SceKernelReleaseThreadEventHandler(uid int32) int32

//go:linkname SceKernelReferThreadEventHandlerStatus sceKernelReferThreadEventHandlerStatus
func SceKernelReferThreadEventHandlerStatus(uid int32, info unsafe.Pointer) int32

//go:linkname SceKernelReferThreadProfiler sceKernelReferThreadProfiler
func SceKernelReferThreadProfiler() unsafe.Pointer

//go:linkname SceKernelReferGlobalProfiler sceKernelReferGlobalProfiler
func SceKernelReferGlobalProfiler() unsafe.Pointer
