// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspirkeyb.h

// Package irkeyb provides direct TinyGo bindings for pspirkeyb.h.
package irkeyb

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_IRKBD_TYPE_NONE                        = 0
	PSP_IRKBD_TYPE_FOLDABLE                    = 1
	PSP_IRKBD_TYPE_SNAPNTYPE                   = 2
	PSP_IRKBD_TYPE_BELKINIRF8U1500             = 3
	PSP_IRKBD_TYPE_HPSLIM                      = 5
	PSP_IRKBD_TYPE_BELKINIR                    = 8
	PSP_IRKBD_TYPE_FLEXIS                      = 9
	PSP_IRKBD_TYPE_BENQ_GAMEPAD                = 10
	PSP_IRKBD_TYPE_MICRO_INNOVATIONS           = 11
	PSP_IRKBD_TYPE_MICRO_FOLDAWAY              = 12
	PSP_IRKBD_TYPE_MICRO_DATAPAD               = 13
	PSP_IRKBD_TYPE_COMPAQ_MICROKBD             = 14
	PSP_IRKBD_TYPE_TARGUSIR                    = 15
	PSP_IRKBD_TYPE_FREEDOM                     = 18
	PSP_IRKBD_TYPE_NOVAETS_KIS2                = 19
	PSP_IRKBD_TYPE_PALM_UW                     = 20
	PSP_IRKBD_TYPE_HAMA                        = 21
	PSP_IRKBD_TYPE_SPRINT                      = 22
	PSP_IRKBD_TYPE_PALM_ONE                    = 23
	PSP_IRKBD_RESULT_OK                        = 0
	PSP_IRKBD_RESULT_FAILED                    = -1
	PSP_IRKBD_RESULT_CANT_OPEN_DEVICE          = -2
	PSP_IRKBD_RESULT_CANT_OPEN_MAPFILE         = -3
	PSP_IRKBD_RESULT_MAPFILE_MAXDEPTHLEVEL     = -4
	PSP_IRKBD_RESULT_CANT_OPEN_MAPFILE_INCLUDE = -5
	PSP_IRKBD_RESULT_CANT_SET_BAUDTATE         = -6
	PSP_IRKBD_RESULT_CONFIG_FILE_NOT_FOUND     = -7
	PSP_IRKBD_RESULT_UNKNOW_KEYBOARD           = -8
	PSP_IRKBD_OUTPUT_MODE_ASCII                = 0
	PSP_IRKBD_OUTPUT_MODE_RAW                  = 1
	PSP_IRKBD_OUTPUT_MODE_SCANCODE             = 2
	PSP_IRKBD_OUTPUT_MODE_VT100                = 3
)

//go:linkname PspIrKeybInit pspIrKeybInit
func PspIrKeybInit(inifile unsafe.Pointer, kernelmode int32) int32

//go:linkname PspIrKeybOutputMode pspIrKeybOutputMode
func PspIrKeybOutputMode(outputmode int32) int32

//go:linkname PspIrKeybGetOutputMode pspIrKeybGetOutputMode
func PspIrKeybGetOutputMode() int32

//go:linkname PspIrKeybReadinput pspIrKeybReadinput
func PspIrKeybReadinput(buffer unsafe.Pointer, length unsafe.Pointer) int32

//go:linkname PspIrKeybFinish pspIrKeybFinish
func PspIrKeybFinish() int32
