// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psprtc.h

// Package rtc provides direct TinyGo bindings for psprtc.h.
package rtc

import "unsafe"

var _ unsafe.Pointer

const (
	SCHED_OTHER                   = 0
	SCHED_MIN                     = 0
	SCHED_MAX                     = 2
	PTHREAD_MUTEX_TIMED_NP        = 0
	PTHREAD_MUTEX_ADAPTIVE_NP     = 0
	PTHREAD_MUTEX_NORMAL          = 0
	PTHREAD_MUTEX_RECURSIVE       = 1
	PTHREAD_MUTEX_ERRORCHECK      = 2
	PTHREAD_MUTEX_DEFAULT         = 0
	PSP_TIME_INVALID_YEAR         = -1
	PSP_TIME_INVALID_MONTH        = -2
	PSP_TIME_INVALID_DAY          = -3
	PSP_TIME_INVALID_HOUR         = -4
	PSP_TIME_INVALID_MINUTES      = -5
	PSP_TIME_INVALID_SECONDS      = -6
	PSP_TIME_INVALID_MICROSECONDS = -7
)

//go:linkname SceRtcGetTickResolution sceRtcGetTickResolution
func SceRtcGetTickResolution() int32

//go:linkname SceRtcGetCurrentTick sceRtcGetCurrentTick
func SceRtcGetCurrentTick(tick unsafe.Pointer) int32

//go:linkname SceRtcGetCurrentClock sceRtcGetCurrentClock
func SceRtcGetCurrentClock(time unsafe.Pointer, tz int32) int32

//go:linkname SceRtcGetCurrentClockLocalTime sceRtcGetCurrentClockLocalTime
func SceRtcGetCurrentClockLocalTime(time unsafe.Pointer) int32

//go:linkname SceRtcConvertUtcToLocalTime sceRtcConvertUtcToLocalTime
func SceRtcConvertUtcToLocalTime(tickUTC unsafe.Pointer, tickLocal unsafe.Pointer) int32

//go:linkname SceRtcConvertLocalTimeToUTC sceRtcConvertLocalTimeToUTC
func SceRtcConvertLocalTimeToUTC(tickLocal unsafe.Pointer, tickUTC unsafe.Pointer) int32

//go:linkname SceRtcIsLeapYear sceRtcIsLeapYear
func SceRtcIsLeapYear(year int32) int32

//go:linkname SceRtcGetDaysInMonth sceRtcGetDaysInMonth
func SceRtcGetDaysInMonth(year int32, month int32) int32

//go:linkname SceRtcGetDayOfWeek sceRtcGetDayOfWeek
func SceRtcGetDayOfWeek(year int32, month int32, day int32) int32

//go:linkname SceRtcCheckValid sceRtcCheckValid
func SceRtcCheckValid(date unsafe.Pointer) int32

//go:linkname SceRtcSetTick sceRtcSetTick
func SceRtcSetTick(date unsafe.Pointer, tick unsafe.Pointer) int32

//go:linkname SceRtcGetTick sceRtcGetTick
func SceRtcGetTick(date unsafe.Pointer, tick unsafe.Pointer) int32

//go:linkname SceRtcCompareTick sceRtcCompareTick
func SceRtcCompareTick(tick1 unsafe.Pointer, tick2 unsafe.Pointer) int32

//go:linkname SceRtcTickAddTicks sceRtcTickAddTicks
func SceRtcTickAddTicks(destTick unsafe.Pointer, srcTick unsafe.Pointer, numTicks uint64) int32

//go:linkname SceRtcTickAddMicroseconds sceRtcTickAddMicroseconds
func SceRtcTickAddMicroseconds(destTick unsafe.Pointer, srcTick unsafe.Pointer, numMS uint64) int32

//go:linkname SceRtcTickAddSeconds sceRtcTickAddSeconds
func SceRtcTickAddSeconds(destTick unsafe.Pointer, srcTick unsafe.Pointer, numSecs uint64) int32

//go:linkname SceRtcTickAddMinutes sceRtcTickAddMinutes
func SceRtcTickAddMinutes(destTick unsafe.Pointer, srcTick unsafe.Pointer, numMins uint64) int32

//go:linkname SceRtcTickAddHours sceRtcTickAddHours
func SceRtcTickAddHours(destTick unsafe.Pointer, srcTick unsafe.Pointer, numHours int32) int32

//go:linkname SceRtcTickAddDays sceRtcTickAddDays
func SceRtcTickAddDays(destTick unsafe.Pointer, srcTick unsafe.Pointer, numDays int32) int32

//go:linkname SceRtcTickAddWeeks sceRtcTickAddWeeks
func SceRtcTickAddWeeks(destTick unsafe.Pointer, srcTick unsafe.Pointer, numWeeks int32) int32

//go:linkname SceRtcTickAddMonths sceRtcTickAddMonths
func SceRtcTickAddMonths(destTick unsafe.Pointer, srcTick unsafe.Pointer, numMonths int32) int32

//go:linkname SceRtcTickAddYears sceRtcTickAddYears
func SceRtcTickAddYears(destTick unsafe.Pointer, srcTick unsafe.Pointer, numYears int32) int32

//go:linkname SceRtcSetTime_t sceRtcSetTime_t
func SceRtcSetTime_t(date unsafe.Pointer, time int64) int32

//go:linkname SceRtcGetTime_t sceRtcGetTime_t
func SceRtcGetTime_t(date unsafe.Pointer, time unsafe.Pointer) int32

//go:linkname SceRtcSetDosTime sceRtcSetDosTime
func SceRtcSetDosTime(date unsafe.Pointer, dosTime uint32) int32

//go:linkname SceRtcGetDosTime sceRtcGetDosTime
func SceRtcGetDosTime(date unsafe.Pointer, dosTime uint32) int32

//go:linkname SceRtcSetWin32FileTime sceRtcSetWin32FileTime
func SceRtcSetWin32FileTime(date unsafe.Pointer, win32Time unsafe.Pointer) int32

//go:linkname SceRtcGetWin32FileTime sceRtcGetWin32FileTime
func SceRtcGetWin32FileTime(date unsafe.Pointer, win32Time unsafe.Pointer) int32

//go:linkname SceRtcParseDateTime sceRtcParseDateTime
func SceRtcParseDateTime(destTick unsafe.Pointer, dateString unsafe.Pointer) int32

//go:linkname SceRtcFormatRFC2822 sceRtcFormatRFC2822
func SceRtcFormatRFC2822(pszDateTime unsafe.Pointer, pUtc unsafe.Pointer, iTimeZoneMinutes int32) int32

//go:linkname SceRtcFormatRFC2822LocalTime sceRtcFormatRFC2822LocalTime
func SceRtcFormatRFC2822LocalTime(pszDateTime unsafe.Pointer, pUtc unsafe.Pointer) int32

//go:linkname SceRtcFormatRFC3339 sceRtcFormatRFC3339
func SceRtcFormatRFC3339(pszDateTime unsafe.Pointer, pUtc unsafe.Pointer, iTimeZoneMinutes int32) int32

//go:linkname SceRtcFormatRFC3339LocalTime sceRtcFormatRFC3339LocalTime
func SceRtcFormatRFC3339LocalTime(pszDateTime unsafe.Pointer, pUtc unsafe.Pointer) int32

//go:linkname SceRtcParseRFC3339 sceRtcParseRFC3339
func SceRtcParseRFC3339(pUtc unsafe.Pointer, pszDateTime unsafe.Pointer) int32
