// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: bootloadex.h

// Package bootloadex provides direct TinyGo bindings for bootloadex.h.
package bootloadex

import "unsafe"

var _ unsafe.Pointer

func init() { requireBootloadex() }

//go:linkname requireBootloadex pspsdk_go_require_bootloadex
func requireBootloadex()

const (
	PSP_MODULE_USER                    = 0
	PSP_MODULE_NO_STOP                 = 1
	PSP_MODULE_SINGLE_LOAD             = 2
	PSP_MODULE_SINGLE_START            = 4
	PSP_MODULE_KERNEL                  = 4096
	PSP_THREAD_ATTR_VFPU               = 16384
	PSP_THREAD_ATTR_USER               = 2147483648
	PSP_THREAD_ATTR_USBWLAN            = 2684354560
	PSP_THREAD_ATTR_VSH                = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM       = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK       = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK        = 2097152
	PSP_THREAD_RUNNING                 = 1
	PSP_THREAD_READY                   = 2
	PSP_THREAD_WAITING                 = 4
	PSP_THREAD_SUSPEND                 = 8
	PSP_THREAD_STOPPED                 = 16
	PSP_THREAD_KILLED                  = 32
	PSP_LW_MUTEX_ATTR_THFIFO           = 0
	PSP_LW_MUTEX_ATTR_THPRI            = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE        = 512
	PSP_EVENT_WAITSINGLE               = 0
	PSP_EVENT_WAITMULTIPLE             = 512
	PSP_EVENT_WAITAND                  = 0
	PSP_EVENT_WAITOR                   = 1
	PSP_EVENT_WAITCLEAR                = 32
	SCE_KERNEL_TMID_Thread             = 1
	SCE_KERNEL_TMID_Semaphore          = 2
	SCE_KERNEL_TMID_EventFlag          = 3
	SCE_KERNEL_TMID_Mbox               = 4
	SCE_KERNEL_TMID_Vpl                = 5
	SCE_KERNEL_TMID_Fpl                = 6
	SCE_KERNEL_TMID_Mpipe              = 7
	SCE_KERNEL_TMID_Callback           = 8
	SCE_KERNEL_TMID_ThreadEventHandler = 9
	SCE_KERNEL_TMID_Alarm              = 10
	SCE_KERNEL_TMID_VTimer             = 11
	SCE_KERNEL_TMID_SleepThread        = 64
	SCE_KERNEL_TMID_DelayThread        = 65
	SCE_KERNEL_TMID_SuspendThread      = 66
	SCE_KERNEL_TMID_DormantThread      = 67
	THREADEVENT_ALL                    = 4294967295
	THREADEVENT_KERN                   = 4294967288
	THREADEVENT_USER                   = 4294967280
	THREADEVENT_CURRENT                = 0
	THREAD_CREATE                      = 1
	THREAD_START                       = 2
	THREAD_EXIT                        = 4
	THREAD_DELETE                      = 8
)

//go:linkname UnPatchLoadCorePRXDecrypt unPatchLoadCorePRXDecrypt
func UnPatchLoadCorePRXDecrypt()

//go:linkname UnPatchLoadCoreCheckExec unPatchLoadCoreCheckExec
func UnPatchLoadCoreCheckExec()

//go:linkname SearchPrx SearchPrx
func SearchPrx(buffer unsafe.Pointer, modname unsafe.Pointer) int32

//go:linkname AddPRXNoCopyName AddPRXNoCopyName
func AddPRXNoCopyName(buffer unsafe.Pointer, insertbefore unsafe.Pointer, prxname_offset int32, flags uint32) int32

//go:linkname AddPRX AddPRX
func AddPRX(buffer unsafe.Pointer, insertbefore unsafe.Pointer, prxname unsafe.Pointer, flags uint32) int32

//go:linkname RemovePrx RemovePrx
func RemovePrx(buffer unsafe.Pointer, prxname unsafe.Pointer, flags uint32) int32

//go:linkname MovePrx MovePrx
func MovePrx(buffer unsafe.Pointer, insertbefore unsafe.Pointer, prxname unsafe.Pointer, flags uint32) int32

//go:linkname ModifyPrxFlag ModifyPrxFlag
func ModifyPrxFlag(buffer unsafe.Pointer, modname unsafe.Pointer, flags uint32) int32

//go:linkname GetPrxFlag GetPrxFlag
func GetPrxFlag(buffer unsafe.Pointer, modname unsafe.Pointer, flags unsafe.Pointer) int32

//go:linkname FindImportRange FindImportRange
func FindImportRange(libname unsafe.Pointer, nid uint32, lower uint32, higher uint32) int32

//go:linkname ConfigureBoot configureBoot
func ConfigureBoot(arg0 unsafe.Pointer)

//go:linkname FindBootFunctions findBootFunctions
func FindBootFunctions()

//go:linkname PatchLoadCore patchLoadCore
func PatchLoadCore(entry uint32)

//go:linkname PatchRebootBuffer patchRebootBuffer
func PatchRebootBuffer()

//go:linkname PatchBootPSP patchBootPSP
func PatchBootPSP()

//go:linkname File_exists file_exists
func File_exists(path unsafe.Pointer) int32

//go:linkname Is_fatms371 is_fatms371
func Is_fatms371() int32

//go:linkname Patch_bootconf_fatms371 patch_bootconf_fatms371
func Patch_bootconf_fatms371(buffer unsafe.Pointer, length int32) int32

//go:linkname Patch_bootconf_timemachine patch_bootconf_timemachine
func Patch_bootconf_timemachine(buffer unsafe.Pointer, length int32) int32

//go:linkname PatchBootVita patchBootVita
func PatchBootVita()

//go:linkname RelocateFlashFile relocateFlashFile
func RelocateFlashFile(file unsafe.Pointer)

//go:linkname FlushCache flushCache
func FlushCache()
