// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmoduleinfo.h

// Package moduleinfo provides direct TinyGo bindings for pspmoduleinfo.h.
package moduleinfo

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_MODULE_USER         = 0
	PSP_MODULE_NO_STOP      = 1
	PSP_MODULE_SINGLE_LOAD  = 2
	PSP_MODULE_SINGLE_START = 4
	PSP_MODULE_KERNEL       = 4096
)
