// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspiofilemgr.h

// Package iofilemgr provides direct TinyGo bindings for pspiofilemgr.h.
package iofilemgr

import "unsafe"

var _ unsafe.Pointer

const (
	FIO_S_IFMT      = 61440
	FIO_S_IFLNK     = 16384
	FIO_S_IFDIR     = 4096
	FIO_S_IFREG     = 8192
	FIO_S_ISUID     = 2048
	FIO_S_ISGID     = 1024
	FIO_S_ISVTX     = 512
	FIO_S_IRWXU     = 448
	FIO_S_IRUSR     = 256
	FIO_S_IWUSR     = 128
	FIO_S_IXUSR     = 64
	FIO_S_IRWXG     = 56
	FIO_S_IRGRP     = 32
	FIO_S_IWGRP     = 16
	FIO_S_IXGRP     = 8
	FIO_S_IRWXO     = 7
	FIO_S_IROTH     = 4
	FIO_S_IWOTH     = 2
	FIO_S_IXOTH     = 1
	FIO_SO_IFMT     = 56
	FIO_SO_IFLNK    = 8
	FIO_SO_IFDIR    = 16
	FIO_SO_IFREG    = 32
	FIO_SO_IROTH    = 4
	FIO_SO_IWOTH    = 2
	FIO_SO_IXOTH    = 1
	IOASSIGN_RDWR   = 0
	IOASSIGN_RDONLY = 1
)

//go:linkname SceIoOpen sceIoOpen
func SceIoOpen(file unsafe.Pointer, flags int32, mode int32) int32

//go:linkname SceIoOpenAsync sceIoOpenAsync
func SceIoOpenAsync(file unsafe.Pointer, flags int32, mode int32) int32

//go:linkname SceIoClose sceIoClose
func SceIoClose(fd int32) int32

//go:linkname SceIoCloseAsync sceIoCloseAsync
func SceIoCloseAsync(fd int32) int32

//go:linkname SceIoRead sceIoRead
func SceIoRead(fd int32, data unsafe.Pointer, size uint32) int32

//go:linkname SceIoReadAsync sceIoReadAsync
func SceIoReadAsync(fd int32, data unsafe.Pointer, size uint32) int32

//go:linkname SceIoWrite sceIoWrite
func SceIoWrite(fd int32, data unsafe.Pointer, size uint32) int32

//go:linkname SceIoWriteAsync sceIoWriteAsync
func SceIoWriteAsync(fd int32, data unsafe.Pointer, size uint32) int32

//go:linkname SceIoLseek sceIoLseek
func SceIoLseek(fd int32, offset int64, whence int32) int64

//go:linkname SceIoLseekAsync sceIoLseekAsync
func SceIoLseekAsync(fd int32, offset int64, whence int32) int32

//go:linkname SceIoLseek32 sceIoLseek32
func SceIoLseek32(fd int32, offset int32, whence int32) int32

//go:linkname SceIoLseek32Async sceIoLseek32Async
func SceIoLseek32Async(fd int32, offset int32, whence int32) int32

//go:linkname SceIoRemove sceIoRemove
func SceIoRemove(file unsafe.Pointer) int32

//go:linkname SceIoMkdir sceIoMkdir
func SceIoMkdir(dir unsafe.Pointer, mode int32) int32

//go:linkname SceIoRmdir sceIoRmdir
func SceIoRmdir(path unsafe.Pointer) int32

//go:linkname SceIoChdir sceIoChdir
func SceIoChdir(path unsafe.Pointer) int32

//go:linkname SceIoRename sceIoRename
func SceIoRename(oldname unsafe.Pointer, newname unsafe.Pointer) int32

//go:linkname SceIoDopen sceIoDopen
func SceIoDopen(dirname unsafe.Pointer) int32

//go:linkname SceIoDread sceIoDread
func SceIoDread(fd int32, dir unsafe.Pointer) int32

//go:linkname SceIoDclose sceIoDclose
func SceIoDclose(fd int32) int32

//go:linkname SceIoDevctl sceIoDevctl
func SceIoDevctl(dev unsafe.Pointer, cmd uint32, indata unsafe.Pointer, inlen int32, outdata unsafe.Pointer, outlen int32) int32

//go:linkname SceIoAssign sceIoAssign
func SceIoAssign(dev1 unsafe.Pointer, dev2 unsafe.Pointer, dev3 unsafe.Pointer, mode int32, unk1 unsafe.Pointer, unk2 int32) int32

//go:linkname SceIoUnassign sceIoUnassign
func SceIoUnassign(dev unsafe.Pointer) int32

//go:linkname SceIoGetstat sceIoGetstat
func SceIoGetstat(file unsafe.Pointer, stat unsafe.Pointer) int32

//go:linkname SceIoChstat sceIoChstat
func SceIoChstat(file unsafe.Pointer, stat unsafe.Pointer, bits int32) int32

//go:linkname SceIoIoctl sceIoIoctl
func SceIoIoctl(fd int32, cmd uint32, indata unsafe.Pointer, inlen int32, outdata unsafe.Pointer, outlen int32) int32

//go:linkname SceIoIoctlAsync sceIoIoctlAsync
func SceIoIoctlAsync(fd int32, cmd uint32, indata unsafe.Pointer, inlen int32, outdata unsafe.Pointer, outlen int32) int32

//go:linkname SceIoSync sceIoSync
func SceIoSync(device unsafe.Pointer, unk uint32) int32

//go:linkname SceIoWaitAsync sceIoWaitAsync
func SceIoWaitAsync(fd int32, res unsafe.Pointer) int32

//go:linkname SceIoWaitAsyncCB sceIoWaitAsyncCB
func SceIoWaitAsyncCB(fd int32, res unsafe.Pointer) int32

//go:linkname SceIoPollAsync sceIoPollAsync
func SceIoPollAsync(fd int32, res unsafe.Pointer) int32

//go:linkname SceIoGetAsyncStat sceIoGetAsyncStat
func SceIoGetAsyncStat(fd int32, poll int32, res unsafe.Pointer) int32

//go:linkname SceIoCancel sceIoCancel
func SceIoCancel(fd int32) int32

//go:linkname SceIoGetDevType sceIoGetDevType
func SceIoGetDevType(fd int32) int32

//go:linkname SceIoChangeAsyncPriority sceIoChangeAsyncPriority
func SceIoChangeAsyncPriority(fd int32, pri int32) int32

//go:linkname SceIoSetAsyncCallback sceIoSetAsyncCallback
func SceIoSetAsyncCallback(fd int32, cb int32, argp unsafe.Pointer) int32
