// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: vitapops.h

// Package vitapops provides direct TinyGo bindings for vitapops.h.
package vitapops

import "unsafe"

var _ unsafe.Pointer

const (
	POPS_GPU_HEIGHT_240 = 0
	POPS_GPU_HEIGHT_480 = 4
	POPS_GPU_WIDTH_256  = 0
	POPS_GPU_WIDTH_320  = 1
	POPS_GPU_WIDTH_512  = 2
	POPS_GPU_WIDTH_640  = 3
	POPS_GPU_WIDTH_368  = 64
	POPS_GPU_PAL        = 8
	POPS_GPU_RGB24      = 16
	POPS_GPU_INTERLACED = 32
	POPS_GPU_REVERSE    = 128
)
