// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: idsregeneration.h

// Package idsregeneration provides direct TinyGo bindings for idsregeneration.h.
package idsregeneration

import "unsafe"

var _ unsafe.Pointer

func init() { requireIdsregeneration() }

//go:linkname requireIdsregeneration pspsdk_go_require_idsregeneration
func requireIdsregeneration()

//go:linkname IdsRegenerationSetup idsRegenerationSetup
func IdsRegenerationSetup(tachyon int32, baryon int32, pommel int32, mb int32, fuseid int32, region int32, setparam unsafe.Pointer) int32

//go:linkname IdsRegenerationGetIndex idsRegenerationGetIndex
func IdsRegenerationGetIndex(index unsafe.Pointer, n unsafe.Pointer) int32

//go:linkname IdsRegenerationCreateCertificatesAndUMDKeys idsRegenerationCreateCertificatesAndUMDKeys
func IdsRegenerationCreateCertificatesAndUMDKeys(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetHwConfigKeys idsRegenerationGetHwConfigKeys
func IdsRegenerationGetHwConfigKeys(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetMGKeys idsRegenerationGetMGKeys
func IdsRegenerationGetMGKeys(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetFactoryBadBlocksKey idsRegenerationGetFactoryBadBlocksKey
func IdsRegenerationGetFactoryBadBlocksKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetSerialKey idsRegenerationGetSerialKey
func IdsRegenerationGetSerialKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetWlanKey idsRegenerationGetWlanKey
func IdsRegenerationGetWlanKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetAudioVolumeSetupKey idsRegenerationGetAudioVolumeSetupKey
func IdsRegenerationGetAudioVolumeSetupKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetUsbKeys idsRegenerationGetUsbKeys
func IdsRegenerationGetUsbKeys(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetUnkKey140 idsRegenerationGetUnkKey140
func IdsRegenerationGetUnkKey140(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetMGKey40 idsRegenerationGetMGKey40
func IdsRegenerationGetMGKey40(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetUnkKeys3X idsRegenerationGetUnkKeys3X
func IdsRegenerationGetUnkKeys3X(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetParentalLockKey idsRegenerationGetParentalLockKey
func IdsRegenerationGetParentalLockKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGenerateFactoryFirmwareKey idsRegenerationGenerateFactoryFirmwareKey
func IdsRegenerationGenerateFactoryFirmwareKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetLCDKey idsRegenerationGetLCDKey
func IdsRegenerationGetLCDKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGenerateCallibrationKey idsRegenerationGenerateCallibrationKey
func IdsRegenerationGenerateCallibrationKey(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetUnkKeys5253 idsRegenerationGetUnkKeys5253
func IdsRegenerationGetUnkKeys5253(buf unsafe.Pointer) int32

//go:linkname IdsRegenerationGetDefaultXMBColorKey idsRegenerationGetDefaultXMBColorKey
func IdsRegenerationGetDefaultXMBColorKey(buf unsafe.Pointer) int32
