// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: as_reg_compat.h

// Package as_reg_compat provides direct TinyGo bindings for as_reg_compat.h.
package as_reg_compat

import "unsafe"

var _ unsafe.Pointer
