// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: systemctrl_private.h

// Package systemctrl_private provides direct TinyGo bindings for systemctrl_private.h.
package systemctrl_private

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_MODULE_USER                    = 0
	PSP_MODULE_NO_STOP                 = 1
	PSP_MODULE_SINGLE_LOAD             = 2
	PSP_MODULE_SINGLE_START            = 4
	PSP_MODULE_KERNEL                  = 4096
	SCE_MODULE_ATTR_NONE               = 0
	SCE_MODULE_ATTR_CANT_STOP          = 1
	SCE_MODULE_ATTR_EXCLUSIVE_LOAD     = 2
	SCE_MODULE_ATTR_EXCLUSIVE_START    = 4
	SCE_MODULE_USER                    = 0
	SCE_MODULE_MS                      = 512
	SCE_MODULE_USB_WLAN                = 1024
	SCE_MODULE_APP                     = 1536
	SCE_MODULE_VSH                     = 2048
	SCE_MODULE_KERNEL                  = 4096
	SCE_MODULE_KIRK_MEMLMD_LIB         = 8192
	SCE_MODULE_KIRK_SEMAPHORE_LIB      = 16384
	PSP_THREAD_ATTR_VFPU               = 16384
	PSP_THREAD_ATTR_USER               = 2147483648
	PSP_THREAD_ATTR_USBWLAN            = 2684354560
	PSP_THREAD_ATTR_VSH                = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM       = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK       = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK        = 2097152
	PSP_THREAD_RUNNING                 = 1
	PSP_THREAD_READY                   = 2
	PSP_THREAD_WAITING                 = 4
	PSP_THREAD_SUSPEND                 = 8
	PSP_THREAD_STOPPED                 = 16
	PSP_THREAD_KILLED                  = 32
	PSP_LW_MUTEX_ATTR_THFIFO           = 0
	PSP_LW_MUTEX_ATTR_THPRI            = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE        = 512
	PSP_EVENT_WAITSINGLE               = 0
	PSP_EVENT_WAITMULTIPLE             = 512
	PSP_EVENT_WAITAND                  = 0
	PSP_EVENT_WAITOR                   = 1
	PSP_EVENT_WAITCLEAR                = 32
	SCE_KERNEL_TMID_Thread             = 1
	SCE_KERNEL_TMID_Semaphore          = 2
	SCE_KERNEL_TMID_EventFlag          = 3
	SCE_KERNEL_TMID_Mbox               = 4
	SCE_KERNEL_TMID_Vpl                = 5
	SCE_KERNEL_TMID_Fpl                = 6
	SCE_KERNEL_TMID_Mpipe              = 7
	SCE_KERNEL_TMID_Callback           = 8
	SCE_KERNEL_TMID_ThreadEventHandler = 9
	SCE_KERNEL_TMID_Alarm              = 10
	SCE_KERNEL_TMID_VTimer             = 11
	SCE_KERNEL_TMID_SleepThread        = 64
	SCE_KERNEL_TMID_DelayThread        = 65
	SCE_KERNEL_TMID_SuspendThread      = 66
	SCE_KERNEL_TMID_DormantThread      = 67
	THREADEVENT_ALL                    = 4294967295
	THREADEVENT_KERN                   = 4294967288
	THREADEVENT_USER                   = 4294967280
	THREADEVENT_CURRENT                = 0
	THREAD_CREATE                      = 1
	THREAD_START                       = 2
	THREAD_EXIT                        = 4
	THREAD_DELETE                      = 8
	DEV_UNK                            = 0
	PSP_ORIG                           = 4
	PSP_TOOL                           = 5
	PS_VITA                            = 8
	PSV_ADR                            = 9
	PSV_POPS                           = 10
	DEV_MASK                           = 12
)

//go:linkname IsLoadingPlugins isLoadingPlugins
func IsLoadingPlugins() int32

//go:linkname MsstorCacheInit msstorCacheInit
func MsstorCacheInit(driver unsafe.Pointer) int32

//go:linkname SctrlKernelGetPSIDHash sctrlKernelGetPSIDHash
func SctrlKernelGetPSIDHash(psidHash unsafe.Pointer) int32

//go:linkname PrintkInit printkInit
func PrintkInit(filename unsafe.Pointer) int32

//go:linkname PrintkSync printkSync
func PrintkSync() int32

//go:linkname PrintkLock printkLock
func PrintkLock()

//go:linkname PrintkUnlock printkUnlock
func PrintkUnlock()

//go:linkname InstallJALTrace installJALTrace
func InstallJALTrace(address uint32)

//go:linkname InstallMemoryJALTrace installMemoryJALTrace
func InstallMemoryJALTrace(start uint32, size uint32)

//go:linkname InstallModuleJALTrace installModuleJALTrace
func InstallModuleJALTrace(module unsafe.Pointer)

// Unsupported C declarations:
// - printk: variadic
// - printkCached: variadic
