// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsysevent.h

// Package sysevent provides direct TinyGo bindings for pspsysevent.h.
package sysevent

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelSysEventDispatch sceKernelSysEventDispatch
func SceKernelSysEventDispatch(ev_type_mask int32, ev_id int32, ev_name unsafe.Pointer, param unsafe.Pointer, result unsafe.Pointer, break_nonzero int32, break_handler unsafe.Pointer) int32

//go:linkname SceKernelReferSysEventHandler sceKernelReferSysEventHandler
func SceKernelReferSysEventHandler() unsafe.Pointer

//go:linkname SceKernelIsRegisterSysEventHandler sceKernelIsRegisterSysEventHandler
func SceKernelIsRegisterSysEventHandler(handler unsafe.Pointer) int32

//go:linkname SceKernelRegisterSysEventHandler sceKernelRegisterSysEventHandler
func SceKernelRegisterSysEventHandler(handler unsafe.Pointer) int32

//go:linkname SceKernelUnregisterSysEventHandler sceKernelUnregisterSysEventHandler
func SceKernelUnregisterSysEventHandler(handler unsafe.Pointer) int32
