// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: kubridge.h

// Package kubridge provides direct TinyGo bindings for kubridge.h.
package kubridge

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkubridge() }

//go:linkname requirePspkubridge pspsdk_go_require_pspkubridge
func requirePspkubridge()

const (
	PSP_MODULE_USER                                 = 0
	PSP_MODULE_NO_STOP                              = 1
	PSP_MODULE_SINGLE_LOAD                          = 2
	PSP_MODULE_SINGLE_START                         = 4
	PSP_MODULE_KERNEL                               = 4096
	PSP_THREAD_ATTR_VFPU                            = 16384
	PSP_THREAD_ATTR_USER                            = 2147483648
	PSP_THREAD_ATTR_USBWLAN                         = 2684354560
	PSP_THREAD_ATTR_VSH                             = 3221225472
	PSP_THREAD_ATTR_SCRATCH_SRAM                    = 32768
	PSP_THREAD_ATTR_NO_FILLSTACK                    = 1048576
	PSP_THREAD_ATTR_CLEAR_STACK                     = 2097152
	PSP_THREAD_RUNNING                              = 1
	PSP_THREAD_READY                                = 2
	PSP_THREAD_WAITING                              = 4
	PSP_THREAD_SUSPEND                              = 8
	PSP_THREAD_STOPPED                              = 16
	PSP_THREAD_KILLED                               = 32
	PSP_LW_MUTEX_ATTR_THFIFO                        = 0
	PSP_LW_MUTEX_ATTR_THPRI                         = 256
	PSP_LW_MUTEX_ATTR_RECURSIVE                     = 512
	PSP_EVENT_WAITSINGLE                            = 0
	PSP_EVENT_WAITMULTIPLE                          = 512
	PSP_EVENT_WAITAND                               = 0
	PSP_EVENT_WAITOR                                = 1
	PSP_EVENT_WAITCLEAR                             = 32
	SCE_KERNEL_TMID_Thread                          = 1
	SCE_KERNEL_TMID_Semaphore                       = 2
	SCE_KERNEL_TMID_EventFlag                       = 3
	SCE_KERNEL_TMID_Mbox                            = 4
	SCE_KERNEL_TMID_Vpl                             = 5
	SCE_KERNEL_TMID_Fpl                             = 6
	SCE_KERNEL_TMID_Mpipe                           = 7
	SCE_KERNEL_TMID_Callback                        = 8
	SCE_KERNEL_TMID_ThreadEventHandler              = 9
	SCE_KERNEL_TMID_Alarm                           = 10
	SCE_KERNEL_TMID_VTimer                          = 11
	SCE_KERNEL_TMID_SleepThread                     = 64
	SCE_KERNEL_TMID_DelayThread                     = 65
	SCE_KERNEL_TMID_SuspendThread                   = 66
	SCE_KERNEL_TMID_DormantThread                   = 67
	THREADEVENT_ALL                                 = 4294967295
	THREADEVENT_KERN                                = 4294967288
	THREADEVENT_USER                                = 4294967280
	THREADEVENT_CURRENT                             = 0
	THREAD_CREATE                                   = 1
	THREAD_START                                    = 2
	THREAD_EXIT                                     = 4
	THREAD_DELETE                                   = 8
	FIO_S_IFMT                                      = 61440
	FIO_S_IFLNK                                     = 16384
	FIO_S_IFDIR                                     = 4096
	FIO_S_IFREG                                     = 8192
	FIO_S_ISUID                                     = 2048
	FIO_S_ISGID                                     = 1024
	FIO_S_ISVTX                                     = 512
	FIO_S_IRWXU                                     = 448
	FIO_S_IRUSR                                     = 256
	FIO_S_IWUSR                                     = 128
	FIO_S_IXUSR                                     = 64
	FIO_S_IRWXG                                     = 56
	FIO_S_IRGRP                                     = 32
	FIO_S_IWGRP                                     = 16
	FIO_S_IXGRP                                     = 8
	FIO_S_IRWXO                                     = 7
	FIO_S_IROTH                                     = 4
	FIO_S_IWOTH                                     = 2
	FIO_S_IXOTH                                     = 1
	FIO_SO_IFMT                                     = 56
	FIO_SO_IFLNK                                    = 8
	FIO_SO_IFDIR                                    = 16
	FIO_SO_IFREG                                    = 32
	FIO_SO_IROTH                                    = 4
	FIO_SO_IWOTH                                    = 2
	FIO_SO_IXOTH                                    = 1
	IOASSIGN_RDWR                                   = 0
	IOASSIGN_RDONLY                                 = 1
	PSP_SMEM_Low                                    = 0
	SCHED_OTHER                                     = 0
	SCHED_MIN                                       = 0
	SCHED_MAX                                       = 2
	PTHREAD_MUTEX_TIMED_NP                          = 0
	PTHREAD_MUTEX_ADAPTIVE_NP                       = 0
	PTHREAD_MUTEX_NORMAL                            = 0
	PTHREAD_MUTEX_RECURSIVE                         = 1
	PTHREAD_MUTEX_ERRORCHECK                        = 2
	PTHREAD_MUTEX_DEFAULT                           = 0
	SCE_KERNEL_ERROR_OK                             = 0
	SCE_KERNEL_ERROR_ERROR                          = 2147614721
	SCE_KERNEL_ERROR_NOTIMP                         = 2147614722
	SCE_KERNEL_ERROR_ILLEGAL_EXPCODE                = 2147614770
	SCE_KERNEL_ERROR_EXPHANDLER_NOUSE               = 2147614771
	SCE_KERNEL_ERROR_EXPHANDLER_USED                = 2147614772
	SCE_KERNEL_ERROR_SYCALLTABLE_NOUSED             = 2147614773
	SCE_KERNEL_ERROR_SYCALLTABLE_USED               = 2147614774
	SCE_KERNEL_ERROR_ILLEGAL_SYSCALLTABLE           = 2147614775
	SCE_KERNEL_ERROR_ILLEGAL_PRIMARY_SYSCALL_NUMBER = 2147614776
	SCE_KERNEL_ERROR_PRIMARY_SYSCALL_NUMBER_INUSE   = 2147614777
	SCE_KERNEL_ERROR_ILLEGAL_CONTEXT                = 2147614820
	SCE_KERNEL_ERROR_ILLEGAL_INTRCODE               = 2147614821
	SCE_KERNEL_ERROR_CPUDI                          = 2147614822
	SCE_KERNEL_ERROR_FOUND_HANDLER                  = 2147614823
	SCE_KERNEL_ERROR_NOTFOUND_HANDLER               = 2147614824
	SCE_KERNEL_ERROR_ILLEGAL_INTRLEVEL              = 2147614825
	SCE_KERNEL_ERROR_ILLEGAL_ADDRESS                = 2147614826
	SCE_KERNEL_ERROR_ILLEGAL_INTRPARAM              = 2147614827
	SCE_KERNEL_ERROR_ILLEGAL_STACK_ADDRESS          = 2147614828
	SCE_KERNEL_ERROR_ALREADY_STACK_SET              = 2147614829
	SCE_KERNEL_ERROR_NO_TIMER                       = 2147614870
	SCE_KERNEL_ERROR_ILLEGAL_TIMERID                = 2147614871
	SCE_KERNEL_ERROR_ILLEGAL_SOURCE                 = 2147614872
	SCE_KERNEL_ERROR_ILLEGAL_PRESCALE               = 2147614873
	SCE_KERNEL_ERROR_TIMER_BUSY                     = 2147614874
	SCE_KERNEL_ERROR_TIMER_NOT_SETUP                = 2147614875
	SCE_KERNEL_ERROR_TIMER_NOT_INUSE                = 2147614876
	SCE_KERNEL_ERROR_UNIT_USED                      = 2147614880
	SCE_KERNEL_ERROR_UNIT_NOUSE                     = 2147614881
	SCE_KERNEL_ERROR_NO_ROMDIR                      = 2147614882
	SCE_KERNEL_ERROR_IDTYPE_EXIST                   = 2147614920
	SCE_KERNEL_ERROR_IDTYPE_NOT_EXIST               = 2147614921
	SCE_KERNEL_ERROR_IDTYPE_NOT_EMPTY               = 2147614922
	SCE_KERNEL_ERROR_UNKNOWN_UID                    = 2147614923
	SCE_KERNEL_ERROR_UNMATCH_UID_TYPE               = 2147614924
	SCE_KERNEL_ERROR_ID_NOT_EXIST                   = 2147614925
	SCE_KERNEL_ERROR_NOT_FOUND_UIDFUNC              = 2147614926
	SCE_KERNEL_ERROR_UID_ALREADY_HOLDER             = 2147614927
	SCE_KERNEL_ERROR_UID_NOT_HOLDER                 = 2147614928
	SCE_KERNEL_ERROR_ILLEGAL_PERM                   = 2147614929
	SCE_KERNEL_ERROR_ILLEGAL_ARGUMENT               = 2147614930
	SCE_KERNEL_ERROR_ILLEGAL_ADDR                   = 2147614931
	SCE_KERNEL_ERROR_OUT_OF_RANGE                   = 2147614932
	SCE_KERNEL_ERROR_MEM_RANGE_OVERLAP              = 2147614933
	SCE_KERNEL_ERROR_ILLEGAL_PARTITION              = 2147614934
	SCE_KERNEL_ERROR_PARTITION_INUSE                = 2147614935
	SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCKTYPE           = 2147614936
	SCE_KERNEL_ERROR_MEMBLOCK_ALLOC_FAILED          = 2147614937
	SCE_KERNEL_ERROR_MEMBLOCK_RESIZE_LOCKED         = 2147614938
	SCE_KERNEL_ERROR_MEMBLOCK_RESIZE_FAILED         = 2147614939
	SCE_KERNEL_ERROR_HEAPBLOCK_ALLOC_FAILED         = 2147614940
	SCE_KERNEL_ERROR_HEAP_ALLOC_FAILED              = 2147614941
	SCE_KERNEL_ERROR_ILLEGAL_CHUNK_ID               = 2147614942
	SCE_KERNEL_ERROR_NOCHUNK                        = 2147614943
	SCE_KERNEL_ERROR_NO_FREECHUNK                   = 2147614944
	SCE_KERNEL_ERROR_LINKERR                        = 2147615020
	SCE_KERNEL_ERROR_ILLEGAL_OBJECT                 = 2147615021
	SCE_KERNEL_ERROR_UNKNOWN_MODULE                 = 2147615022
	SCE_KERNEL_ERROR_NOFILE                         = 2147615023
	SCE_KERNEL_ERROR_FILEERR                        = 2147615024
	SCE_KERNEL_ERROR_MEMINUSE                       = 2147615025
	SCE_KERNEL_ERROR_PARTITION_MISMATCH             = 2147615026
	SCE_KERNEL_ERROR_ALREADY_STARTED                = 2147615027
	SCE_KERNEL_ERROR_NOT_STARTED                    = 2147615028
	SCE_KERNEL_ERROR_ALREADY_STOPPED                = 2147615029
	SCE_KERNEL_ERROR_CAN_NOT_STOP                   = 2147615030
	SCE_KERNEL_ERROR_NOT_STOPPED                    = 2147615031
	SCE_KERNEL_ERROR_NOT_REMOVABLE                  = 2147615032
	SCE_KERNEL_ERROR_EXCLUSIVE_LOAD                 = 2147615033
	SCE_KERNEL_ERROR_LIBRARY_NOT_YET_LINKED         = 2147615034
	SCE_KERNEL_ERROR_LIBRARY_FOUND                  = 2147615035
	SCE_KERNEL_ERROR_LIBRARY_NOTFOUND               = 2147615036
	SCE_KERNEL_ERROR_ILLEGAL_LIBRARY                = 2147615037
	SCE_KERNEL_ERROR_LIBRARY_INUSE                  = 2147615038
	SCE_KERNEL_ERROR_ALREADY_STOPPING               = 2147615039
	SCE_KERNEL_ERROR_ILLEGAL_OFFSET                 = 2147615040
	SCE_KERNEL_ERROR_ILLEGAL_POSITION               = 2147615041
	SCE_KERNEL_ERROR_ILLEGAL_ACCESS                 = 2147615042
	SCE_KERNEL_ERROR_MODULE_MGR_BUSY                = 2147615043
	SCE_KERNEL_ERROR_ILLEGAL_FLAG                   = 2147615044
	SCE_KERNEL_ERROR_CANNOT_GET_MODULELIST          = 2147615045
	SCE_KERNEL_ERROR_PROHIBIT_LOADMODULE_DEVICE     = 2147615046
	SCE_KERNEL_ERROR_PROHIBIT_LOADEXEC_DEVICE       = 2147615047
	SCE_KERNEL_ERROR_UNSUPPORTED_PRX_TYPE           = 2147615048
	SCE_KERNEL_ERROR_ILLEGAL_PERM_CALL              = 2147615049
	SCE_KERNEL_ERROR_CANNOT_GET_MODULE_INFORMATION  = 2147615050
	SCE_KERNEL_ERROR_ILLEGAL_LOADEXEC_BUFFER        = 2147615051
	SCE_KERNEL_ERROR_ILLEGAL_LOADEXEC_FILENAME      = 2147615052
	SCE_KERNEL_ERROR_NO_EXIT_CALLBACK               = 2147615053
	SCE_KERNEL_ERROR_NO_MEMORY                      = 2147615120
	SCE_KERNEL_ERROR_ILLEGAL_ATTR                   = 2147615121
	SCE_KERNEL_ERROR_ILLEGAL_ENTRY                  = 2147615122
	SCE_KERNEL_ERROR_ILLEGAL_PRIORITY               = 2147615123
	SCE_KERNEL_ERROR_ILLEGAL_STACK_SIZE             = 2147615124
	SCE_KERNEL_ERROR_ILLEGAL_MODE                   = 2147615125
	SCE_KERNEL_ERROR_ILLEGAL_MASK                   = 2147615126
	SCE_KERNEL_ERROR_ILLEGAL_THID                   = 2147615127
	SCE_KERNEL_ERROR_UNKNOWN_THID                   = 2147615128
	SCE_KERNEL_ERROR_UNKNOWN_SEMID                  = 2147615129
	SCE_KERNEL_ERROR_UNKNOWN_EVFID                  = 2147615130
	SCE_KERNEL_ERROR_UNKNOWN_MBXID                  = 2147615131
	SCE_KERNEL_ERROR_UNKNOWN_VPLID                  = 2147615132
	SCE_KERNEL_ERROR_UNKNOWN_FPLID                  = 2147615133
	SCE_KERNEL_ERROR_UNKNOWN_MPPID                  = 2147615134
	SCE_KERNEL_ERROR_UNKNOWN_ALMID                  = 2147615135
	SCE_KERNEL_ERROR_UNKNOWN_TEID                   = 2147615136
	SCE_KERNEL_ERROR_UNKNOWN_CBID                   = 2147615137
	SCE_KERNEL_ERROR_DORMANT                        = 2147615138
	SCE_KERNEL_ERROR_SUSPEND                        = 2147615139
	SCE_KERNEL_ERROR_NOT_DORMANT                    = 2147615140
	SCE_KERNEL_ERROR_NOT_SUSPEND                    = 2147615141
	SCE_KERNEL_ERROR_NOT_WAIT                       = 2147615142
	SCE_KERNEL_ERROR_CAN_NOT_WAIT                   = 2147615143
	SCE_KERNEL_ERROR_WAIT_TIMEOUT                   = 2147615144
	SCE_KERNEL_ERROR_WAIT_CANCEL                    = 2147615145
	SCE_KERNEL_ERROR_RELEASE_WAIT                   = 2147615146
	SCE_KERNEL_ERROR_NOTIFY_CALLBACK                = 2147615147
	SCE_KERNEL_ERROR_THREAD_TERMINATED              = 2147615148
	SCE_KERNEL_ERROR_SEMA_ZERO                      = 2147615149
	SCE_KERNEL_ERROR_SEMA_OVF                       = 2147615150
	SCE_KERNEL_ERROR_EVF_COND                       = 2147615151
	SCE_KERNEL_ERROR_EVF_MULTI                      = 2147615152
	SCE_KERNEL_ERROR_EVF_ILPAT                      = 2147615153
	SCE_KERNEL_ERROR_MBOX_NOMSG                     = 2147615154
	SCE_KERNEL_ERROR_MPP_FULL                       = 2147615155
	SCE_KERNEL_ERROR_MPP_EMPTY                      = 2147615156
	SCE_KERNEL_ERROR_WAIT_DELETE                    = 2147615157
	SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK               = 2147615158
	SCE_KERNEL_ERROR_ILLEGAL_MEMSIZE                = 2147615159
	SCE_KERNEL_ERROR_ILLEGAL_SPADADDR               = 2147615160
	SCE_KERNEL_ERROR_SPAD_INUSE                     = 2147615161
	SCE_KERNEL_ERROR_SPAD_NOT_INUSE                 = 2147615162
	SCE_KERNEL_ERROR_ILLEGAL_TYPE                   = 2147615163
	SCE_KERNEL_ERROR_ILLEGAL_SIZE                   = 2147615164
	SCE_KERNEL_ERROR_ILLEGAL_COUNT                  = 2147615165
	SCE_KERNEL_ERROR_UNKNOWN_VTID                   = 2147615166
	SCE_KERNEL_ERROR_ILLEGAL_VTID                   = 2147615167
	SCE_KERNEL_ERROR_ILLEGAL_KTLSID                 = 2147615168
	SCE_KERNEL_ERROR_KTLS_FULL                      = 2147615169
	SCE_KERNEL_ERROR_KTLS_BUSY                      = 2147615170
	SCE_KERNEL_ERROR_PM_INVALID_PRIORITY            = 2147615320
	SCE_KERNEL_ERROR_PM_INVALID_DEVNAME             = 2147615321
	SCE_KERNEL_ERROR_PM_UNKNOWN_DEVNAME             = 2147615322
	SCE_KERNEL_ERROR_PM_PMINFO_REGISTERED           = 2147615323
	SCE_KERNEL_ERROR_PM_PMINFO_UNREGISTERED         = 2147615324
	SCE_KERNEL_ERROR_PM_INVALID_MAJOR_STATE         = 2147615325
	SCE_KERNEL_ERROR_PM_INVALID_REQUEST             = 2147615326
	SCE_KERNEL_ERROR_PM_UNKNOWN_REQUEST             = 2147615327
	SCE_KERNEL_ERROR_PM_INVALID_UNIT                = 2147615328
	SCE_KERNEL_ERROR_PM_CANNOT_CANCEL               = 2147615329
	SCE_KERNEL_ERROR_PM_INVALID_PMINFO              = 2147615330
	SCE_KERNEL_ERROR_PM_INVALID_ARGUMENT            = 2147615331
	SCE_KERNEL_ERROR_PM_ALREADY_TARGET_PWRSTATE     = 2147615332
	SCE_KERNEL_ERROR_PM_CHANGE_PWRSTATE_FAILED      = 2147615333
	SCE_KERNEL_ERROR_PM_CANNOT_CHANGE_DEVPWR_STATE  = 2147615334
	SCE_KERNEL_ERROR_PM_NO_SUPPORT_DEVPWR_STATE     = 2147615335
	SCE_KERNEL_ERROR_DMAC_REQUEST_FAILED            = 2147615420
	SCE_KERNEL_ERROR_DMAC_REQUEST_DENIED            = 2147615421
	SCE_KERNEL_ERROR_DMAC_OP_QUEUED                 = 2147615422
	SCE_KERNEL_ERROR_DMAC_OP_NOT_QUEUED             = 2147615423
	SCE_KERNEL_ERROR_DMAC_OP_RUNNING                = 2147615424
	SCE_KERNEL_ERROR_DMAC_OP_NOT_ASSIGNED           = 2147615425
	SCE_KERNEL_ERROR_DMAC_OP_TIMEOUT                = 2147615426
	SCE_KERNEL_ERROR_DMAC_OP_FREED                  = 2147615427
	SCE_KERNEL_ERROR_DMAC_OP_USED                   = 2147615428
	SCE_KERNEL_ERROR_DMAC_OP_EMPTY                  = 2147615429
	SCE_KERNEL_ERROR_DMAC_OP_ABORTED                = 2147615430
	SCE_KERNEL_ERROR_DMAC_OP_ERROR                  = 2147615431
	SCE_KERNEL_ERROR_DMAC_CHANNEL_RESERVED          = 2147615432
	SCE_KERNEL_ERROR_DMAC_CHANNEL_EXCLUDED          = 2147615433
	SCE_KERNEL_ERROR_DMAC_PRIVILEGE_ADDRESS         = 2147615434
	SCE_KERNEL_ERROR_DMAC_NO_ENOUGHSPACE            = 2147615435
	SCE_KERNEL_ERROR_DMAC_CHANNEL_NOT_ASSIGNED      = 2147615436
	SCE_KERNEL_ERROR_DMAC_CHILD_OPERATION           = 2147615437
	SCE_KERNEL_ERROR_DMAC_TOO_MUCH_SIZE             = 2147615438
	SCE_KERNEL_ERROR_DMAC_INVALID_ARGUMENT          = 2147615439
	SCE_KERNEL_ERROR_MFILE                          = 2147615520
	SCE_KERNEL_ERROR_NODEV                          = 2147615521
	SCE_KERNEL_ERROR_XDEV                           = 2147615522
	SCE_KERNEL_ERROR_BADF                           = 2147615523
	SCE_KERNEL_ERROR_INVAL                          = 2147615524
	SCE_KERNEL_ERROR_UNSUP                          = 2147615525
	SCE_KERNEL_ERROR_ALIAS_USED                     = 2147615526
	SCE_KERNEL_ERROR_CANNOT_MOUNT                   = 2147615527
	SCE_KERNEL_ERROR_DRIVER_DELETED                 = 2147615528
	SCE_KERNEL_ERROR_ASYNC_BUSY                     = 2147615529
	SCE_KERNEL_ERROR_NOASYNC                        = 2147615530
	SCE_KERNEL_ERROR_REGDEV                         = 2147615531
	SCE_KERNEL_ERROR_NOCWD                          = 2147615532
	SCE_KERNEL_ERROR_NAMETOOLONG                    = 2147615533
	SCE_KERNEL_ERROR_NXIO                           = 2147615720
	SCE_KERNEL_ERROR_IO                             = 2147615721
	SCE_KERNEL_ERROR_NOMEM                          = 2147615722
	SCE_KERNEL_ERROR_STDIO_NOT_OPENED               = 2147615723
	SCE_KERNEL_ERROR_CACHE_ALIGNMENT                = 2147615820
	SCE_KERNEL_ERROR_ERRORMAX                       = 2147615821
	PSP_GPIO_INT                                    = 4
	PSP_ATA_INT                                     = 5
	PSP_UMD_INT                                     = 6
	PSP_MSCM0_INT                                   = 7
	PSP_WLAN_INT                                    = 8
	PSP_AUDIO_INT                                   = 10
	PSP_I2C_INT                                     = 12
	PSP_SIRCS_INT                                   = 14
	PSP_SYSTIMER0_INT                               = 15
	PSP_SYSTIMER1_INT                               = 16
	PSP_SYSTIMER2_INT                               = 17
	PSP_SYSTIMER3_INT                               = 18
	PSP_THREAD0_INT                                 = 19
	PSP_NAND_INT                                    = 20
	PSP_DMACPLUS_INT                                = 21
	PSP_DMA0_INT                                    = 22
	PSP_DMA1_INT                                    = 23
	PSP_MEMLMD_INT                                  = 24
	PSP_GE_INT                                      = 25
	PSP_VBLANK_INT                                  = 30
	PSP_MECODEC_INT                                 = 31
	PSP_HPREMOTE_INT                                = 36
	PSP_MSCM1_INT                                   = 60
	PSP_MSCM2_INT                                   = 61
	PSP_THREAD1_INT                                 = 65
	PSP_INTERRUPT_INT                               = 66
	PSP_GPIO_SUBINT                                 = 4
	PSP_ATA_SUBINT                                  = 5
	PSP_UMD_SUBINT                                  = 6
	PSP_DMACPLUS_SUBINT                             = 21
	PSP_GE_SUBINT                                   = 25
	PSP_DISPLAY_SUBINT                              = 30
	SCE_MODULE_ATTR_NONE                            = 0
	SCE_MODULE_ATTR_CANT_STOP                       = 1
	SCE_MODULE_ATTR_EXCLUSIVE_LOAD                  = 2
	SCE_MODULE_ATTR_EXCLUSIVE_START                 = 4
	SCE_MODULE_USER                                 = 0
	SCE_MODULE_MS                                   = 512
	SCE_MODULE_USB_WLAN                             = 1024
	SCE_MODULE_APP                                  = 1536
	SCE_MODULE_VSH                                  = 2048
	SCE_MODULE_KERNEL                               = 4096
	SCE_MODULE_KIRK_MEMLMD_LIB                      = 8192
	SCE_MODULE_KIRK_SEMAPHORE_LIB                   = 16384
	PSP_CTRL_SELECT                                 = 1
	PSP_CTRL_L3                                     = 2
	PSP_CTRL_R3                                     = 4
	PSP_CTRL_START                                  = 8
	PSP_CTRL_UP                                     = 16
	PSP_CTRL_RIGHT                                  = 32
	PSP_CTRL_DOWN                                   = 64
	PSP_CTRL_LEFT                                   = 128
	PSP_CTRL_LTRIGGER                               = 256
	PSP_CTRL_RTRIGGER                               = 512
	PSP_CTRL_L2                                     = 256
	PSP_CTRL_R2                                     = 512
	PSP_CTRL_L1                                     = 1024
	PSP_CTRL_R1                                     = 2048
	PSP_CTRL_TRIANGLE                               = 4096
	PSP_CTRL_CIRCLE                                 = 8192
	PSP_CTRL_CROSS                                  = 16384
	PSP_CTRL_SQUARE                                 = 32768
	PSP_CTRL_HOME                                   = 65536
	PSP_CTRL_HOLD                                   = 131072
	PSP_CTRL_NOTE                                   = 8388608
	PSP_CTRL_SCREEN                                 = 4194304
	PSP_CTRL_VOLUP                                  = 1048576
	PSP_CTRL_VOLDOWN                                = 2097152
	PSP_CTRL_WLAN_UP                                = 262144
	PSP_CTRL_REMOTE                                 = 524288
	PSP_CTRL_DISC                                   = 16777216
	PSP_CTRL_MS                                     = 33554432
	PSP_CTRL_MODE_DIGITAL                           = 0
	PSP_CTRL_MODE_ANALOG                            = 1
)

//go:linkname KuKernelLoadModule kuKernelLoadModule
func KuKernelLoadModule(path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname KuKernelLoadModuleWithApitype2 kuKernelLoadModuleWithApitype2
func KuKernelLoadModuleWithApitype2(apitype int32, path unsafe.Pointer, flags int32, option unsafe.Pointer) int32

//go:linkname KuKernelInitApitype kuKernelInitApitype
func KuKernelInitApitype() int32

//go:linkname KuKernelInitFileName kuKernelInitFileName
func KuKernelInitFileName(initfilename unsafe.Pointer) int32

//go:linkname KuKernelBootFrom kuKernelBootFrom
func KuKernelBootFrom() int32

//go:linkname KuKernelInitKeyConfig kuKernelInitKeyConfig
func KuKernelInitKeyConfig() int32

//go:linkname KuKernelGetUserLevel kuKernelGetUserLevel
func KuKernelGetUserLevel() int32

//go:linkname KuKernelSetDdrMemoryProtection kuKernelSetDdrMemoryProtection
func KuKernelSetDdrMemoryProtection(addr unsafe.Pointer, size int32, prot int32) int32

//go:linkname KuKernelGetModel kuKernelGetModel
func KuKernelGetModel() int32

//go:linkname KuKernelFindModuleByName kuKernelFindModuleByName
func KuKernelFindModuleByName(modname unsafe.Pointer, mod unsafe.Pointer) int32

//go:linkname KuKernelFindModuleByAddress kuKernelFindModuleByAddress
func KuKernelFindModuleByAddress(addr unsafe.Pointer, mod unsafe.Pointer) int32

//go:linkname KuKernelIcacheInvalidateAll kuKernelIcacheInvalidateAll
func KuKernelIcacheInvalidateAll()

//go:linkname KuKernelPeekw kuKernelPeekw
func KuKernelPeekw(addr unsafe.Pointer) uint32

//go:linkname KuKernelPokew kuKernelPokew
func KuKernelPokew(addr unsafe.Pointer, value uint32)

//go:linkname KuKernelMemcpy kuKernelMemcpy
func KuKernelMemcpy(dest unsafe.Pointer, src unsafe.Pointer, num uint32) unsafe.Pointer

//go:linkname KuKernelCall kuKernelCall
func KuKernelCall(func_addr unsafe.Pointer, args unsafe.Pointer) int32

//go:linkname KuKernelCallExtendStack kuKernelCallExtendStack
func KuKernelCallExtendStack(func_addr unsafe.Pointer, args unsafe.Pointer, stack_size int32) int32

//go:linkname KuKernelGetUmdFile kuKernelGetUmdFile
func KuKernelGetUmdFile(umdfile unsafe.Pointer, size int32)
