// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmp3.h

// Package mp3 provides direct TinyGo bindings for pspmp3.h.
package mp3

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceMp3ReserveMp3Handle sceMp3ReserveMp3Handle
func SceMp3ReserveMp3Handle(args unsafe.Pointer) int32

//go:linkname SceMp3ReleaseMp3Handle sceMp3ReleaseMp3Handle
func SceMp3ReleaseMp3Handle(handle int32) int32

//go:linkname SceMp3InitResource sceMp3InitResource
func SceMp3InitResource() int32

//go:linkname SceMp3TermResource sceMp3TermResource
func SceMp3TermResource() int32

//go:linkname SceMp3Init sceMp3Init
func SceMp3Init(handle int32) int32

//go:linkname SceMp3Decode sceMp3Decode
func SceMp3Decode(handle int32, dst unsafe.Pointer) int32

//go:linkname SceMp3GetInfoToAddStreamData sceMp3GetInfoToAddStreamData
func SceMp3GetInfoToAddStreamData(handle int32, dst unsafe.Pointer, towrite unsafe.Pointer, srcpos unsafe.Pointer) int32

//go:linkname SceMp3NotifyAddStreamData sceMp3NotifyAddStreamData
func SceMp3NotifyAddStreamData(handle int32, size int32) int32

//go:linkname SceMp3CheckStreamDataNeeded sceMp3CheckStreamDataNeeded
func SceMp3CheckStreamDataNeeded(handle int32) int32

//go:linkname SceMp3SetLoopNum sceMp3SetLoopNum
func SceMp3SetLoopNum(handle int32, loop int32) int32

//go:linkname SceMp3GetLoopNum sceMp3GetLoopNum
func SceMp3GetLoopNum(handle int32) int32

//go:linkname SceMp3GetSumDecodedSample sceMp3GetSumDecodedSample
func SceMp3GetSumDecodedSample(handle int32) int32

//go:linkname SceMp3GetMaxOutputSample sceMp3GetMaxOutputSample
func SceMp3GetMaxOutputSample(handle int32) int32

//go:linkname SceMp3GetSamplingRate sceMp3GetSamplingRate
func SceMp3GetSamplingRate(handle int32) int32

//go:linkname SceMp3GetBitRate sceMp3GetBitRate
func SceMp3GetBitRate(handle int32) int32

//go:linkname SceMp3GetMp3ChannelNum sceMp3GetMp3ChannelNum
func SceMp3GetMp3ChannelNum(handle int32) int32

//go:linkname SceMp3ResetPlayPosition sceMp3ResetPlayPosition
func SceMp3ResetPlayPosition(handle int32) int32

//go:linkname SceMp3GetFrameNum sceMp3GetFrameNum
func SceMp3GetFrameNum(handle int32) int32

//go:linkname SceMp3ResetPlayPositionByFrame sceMp3ResetPlayPositionByFrame
func SceMp3ResetPlayPositionByFrame(handle int32, frame uint32) int32

//go:linkname SceMp3GetMPEGVersion sceMp3GetMPEGVersion
func SceMp3GetMPEGVersion(handle int32) int32

//go:linkname SceMp3LowLevelInit sceMp3LowLevelInit
func SceMp3LowLevelInit(handle int32, src unsafe.Pointer) int32

//go:linkname SceMp3LowLevelDecode sceMp3LowLevelDecode
func SceMp3LowLevelDecode(handle int32, mp3src unsafe.Pointer, mp3srcused unsafe.Pointer, pcmdst unsafe.Pointer, pcmdstoutsz unsafe.Pointer) int32
