// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspkerneltypes.h

// Package kerneltypes provides direct TinyGo bindings for pspkerneltypes.h.
package kerneltypes

import "unsafe"

var _ unsafe.Pointer
