// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspiofilemgr_stat.h

// Package iofilemgr_stat provides direct TinyGo bindings for pspiofilemgr_stat.h.
package iofilemgr_stat

import "unsafe"

var _ unsafe.Pointer

const (
	FIO_S_IFMT   = 61440
	FIO_S_IFLNK  = 16384
	FIO_S_IFDIR  = 4096
	FIO_S_IFREG  = 8192
	FIO_S_ISUID  = 2048
	FIO_S_ISGID  = 1024
	FIO_S_ISVTX  = 512
	FIO_S_IRWXU  = 448
	FIO_S_IRUSR  = 256
	FIO_S_IWUSR  = 128
	FIO_S_IXUSR  = 64
	FIO_S_IRWXG  = 56
	FIO_S_IRGRP  = 32
	FIO_S_IWGRP  = 16
	FIO_S_IXGRP  = 8
	FIO_S_IRWXO  = 7
	FIO_S_IROTH  = 4
	FIO_S_IWOTH  = 2
	FIO_S_IXOTH  = 1
	FIO_SO_IFMT  = 56
	FIO_SO_IFLNK = 8
	FIO_SO_IFDIR = 16
	FIO_SO_IFREG = 32
	FIO_SO_IROTH = 4
	FIO_SO_IWOTH = 2
	FIO_SO_IXOTH = 1
)
