// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspinit.h

// Package init provides direct TinyGo bindings for pspinit.h.
package init

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_BOOT_FLASH                           = 0
	PSP_BOOT_DISC                            = 32
	PSP_BOOT_USBWLAN                         = 48
	PSP_BOOT_MS                              = 64
	PSP_BOOT_EF                              = 80
	PSP_BOOT_FLASH3                          = 128
	PSP_INIT_APITYPE_KERNEL                  = 0
	PSP_INIT_APITYPE_BUFFER_KERNEL           = 2
	PSP_INIT_APITYPE_KERNEL_BLOCK            = 3
	PSP_INIT_APITYPE_USER                    = 16
	PSP_INIT_APITYPE_DNAS                    = 19
	PSP_INIT_APITYPE_NPDRM                   = 20
	PSP_INIT_APITYPE_VSH                     = 32
	PSP_INIT_APITYPE_BUFFER_VSH              = 33
	PSP_INIT_APITYPE_BUFFER_USBWLAN          = 48
	PSP_INIT_APITYPE_BUFFER_MS               = 66
	PSP_INIT_APITYPE_BUFFER_APP              = 67
	PSP_INIT_APITYPE_BUFFER_BOOT_INIT_BTCNF  = 81
	PSP_INIT_APITYPE_BUFFER_BOOT_INIT_CONFIG = 82
	PSP_INIT_APITYPE_BUFFER_DECI             = 112
	PSP_INIT_APITYPE_GAME_EBOOT              = 272
	PSP_INIT_APITYPE_GAME_BOOT               = 273
	PSP_INIT_APITYPE_EMU_EBOOT_MS            = 274
	PSP_INIT_APITYPE_EMU_BOOT_MS             = 275
	PSP_INIT_APITYPE_EMU_EBOOT_EF            = 276
	PSP_INIT_APITYPE_EMU_BOOT_EF             = 277
	PSP_INIT_APITYPE_NPDRM_MS                = 278
	PSP_INIT_APITYPE_UNK117                  = 279
	PSP_INIT_APITYPE_NPDRM_EF                = 280
	PSP_INIT_APITYPE_UNK119                  = 281
	PSP_INIT_APITYPE_UMD                     = 288
	PSP_INIT_APITYPE_UMD_UPDATER             = 289
	PSP_INIT_APITYPE_UMD_DEBUG               = 290
	PSP_INIT_APITYPE_UMD_EMU_MS1             = 291
	PSP_INIT_APITYPE_UMD_EMU_MS2             = 292
	PSP_INIT_APITYPE_UMD_EMU_EF1             = 293
	PSP_INIT_APITYPE_UMD_EMU_EF2             = 294
	PSP_INIT_APITYPE_USBWLAN                 = 304
	PSP_INIT_APITYPE_USBWLAN_DEBUG           = 305
	PSP_INIT_APITYPE_MS1                     = 320
	PSP_INIT_APITYPE_MS2                     = 321
	PSP_INIT_APITYPE_MS3                     = 322
	PSP_INIT_APITYPE_MS4                     = 323
	PSP_INIT_APITYPE_MS5                     = 324
	PSP_INIT_APITYPE_MS6                     = 325
	PSP_INIT_APITYPE_EF1                     = 337
	PSP_INIT_APITYPE_EF2                     = 338
	PSP_INIT_APITYPE_EF3                     = 339
	PSP_INIT_APITYPE_EF4                     = 340
	PSP_INIT_APITYPE_EF5                     = 341
	PSP_INIT_APITYPE_EF6                     = 342
	PSP_INIT_APITYPE_UMD2                    = 352
	PSP_INIT_APITYPE_UNK161                  = 353
	PSP_INIT_APITYPE_MLNAPP_MS               = 368
	PSP_INIT_APITYPE_MLNAPP_EF               = 369
	PSP_INIT_APITYPE_VSH_KERNEL              = 512
	PSP_INIT_APITYPE_VSH1                    = 528
	PSP_INIT_APITYPE_VSH2                    = 544
	PSP_INIT_APITYPE_KERNEL_REBOOT           = 768
	PSP_INIT_APITYPE_DEBUG                   = 1056
	PSP_INIT_APITYPE_DISC                    = 288
	PSP_INIT_APITYPE_DISC2                   = 352
	PSP_INIT_APITYPE_DISC_UPDATER            = 289
	PSP_INIT_APITYPE_DISC_DEBUG              = 290
	PSP_INIT_APITYPE_DISC_EMU_MS1            = 291
	PSP_INIT_APITYPE_DISC_EMU_MS2            = 292
	PSP_INIT_APITYPE_DISC_EMU_EF1            = 293
	PSP_INIT_APITYPE_DISC_EMU_EF2            = 294
	PSP_INIT_APITYPE_MS_UPDATER              = 320
	PSP_INIT_APITYPE_MS_GAME                 = 321
	PSP_INIT_APITYPE_MS_APP                  = 323
	PSP_INIT_APITYPE_MS_PS1                  = 324
	PSP_INIT_APITYPE_EF_UPDATER              = 337
	PSP_INIT_APITYPE_EF_GAME                 = 338
	PSP_INIT_APITYPE_EF_APP                  = 340
	PSP_INIT_APITYPE_EF_PS1                  = 341
	PSP_INIT_APITYPE_VSH_EXITGAME            = 528
	PSP_INIT_APITYPE_VSH_EXITVSH             = 544
	PSP_INIT_KEYCONFIG_VSH                   = 256
	PSP_INIT_KEYCONFIG_UPDATER               = 272
	PSP_INIT_KEYCONFIG_GAME                  = 512
	PSP_INIT_KEYCONFIG_POPS                  = 768
	PSP_INIT_KEYCONFIG_APP                   = 1024
)

//go:linkname SceKernelInitApitype sceKernelInitApitype
func SceKernelInitApitype() int32

//go:linkname SceKernelInitFileName sceKernelInitFileName
func SceKernelInitFileName() unsafe.Pointer

//go:linkname SceKernelBootFrom sceKernelBootFrom
func SceKernelBootFrom() int32

//go:linkname SceKernelApplicationType sceKernelApplicationType
func SceKernelApplicationType() int32

//go:linkname SceKernelQueryInitCB sceKernelQueryInitCB
func SceKernelQueryInitCB() unsafe.Pointer
