// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_osk.h

// Package utility_osk provides direct TinyGo bindings for psputility_osk.h.
package utility_osk

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UTILITY_OSK_LANGUAGE_DEFAULT                 = 0
	PSP_UTILITY_OSK_LANGUAGE_JAPANESE                = 1
	PSP_UTILITY_OSK_LANGUAGE_ENGLISH                 = 2
	PSP_UTILITY_OSK_LANGUAGE_FRENCH                  = 3
	PSP_UTILITY_OSK_LANGUAGE_SPANISH                 = 4
	PSP_UTILITY_OSK_LANGUAGE_GERMAN                  = 5
	PSP_UTILITY_OSK_LANGUAGE_ITALIAN                 = 6
	PSP_UTILITY_OSK_LANGUAGE_DUTCH                   = 7
	PSP_UTILITY_OSK_LANGUAGE_PORTUGESE               = 8
	PSP_UTILITY_OSK_LANGUAGE_RUSSIAN                 = 9
	PSP_UTILITY_OSK_LANGUAGE_KOREAN                  = 10
	PSP_UTILITY_OSK_DIALOG_NONE                      = 0
	PSP_UTILITY_OSK_RESULT_UNCHANGED                 = 0
	PSP_UTILITY_OSK_INPUTTYPE_ALL                    = 0
	PSP_UTILITY_OSK_INPUTTYPE_LATIN_DIGIT            = 1
	PSP_UTILITY_OSK_INPUTTYPE_LATIN_SYMBOL           = 2
	PSP_UTILITY_OSK_INPUTTYPE_LATIN_LOWERCASE        = 4
	PSP_UTILITY_OSK_INPUTTYPE_LATIN_UPPERCASE        = 8
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_DIGIT         = 256
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_SYMBOL        = 512
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_LOWERCASE     = 1024
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_UPPERCASE     = 2048
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HIRAGANA      = 4096
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HALF_KATAKANA = 8192
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KATAKANA      = 16384
	PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KANJI         = 32768
	PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_LOWERCASE      = 65536
	PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_UPPERCASE      = 131072
	PSP_UTILITY_OSK_INPUTTYPE_KOREAN                 = 262144
	PSP_UTILITY_OSK_INPUTTYPE_URL                    = 524288
)

//go:linkname SceUtilityOskInitStart sceUtilityOskInitStart
func SceUtilityOskInitStart(params unsafe.Pointer) int32

//go:linkname SceUtilityOskShutdownStart sceUtilityOskShutdownStart
func SceUtilityOskShutdownStart() int32

//go:linkname SceUtilityOskUpdate sceUtilityOskUpdate
func SceUtilityOskUpdate(n int32) int32

//go:linkname SceUtilityOskGetStatus sceUtilityOskGetStatus
func SceUtilityOskGetStatus() int32
