// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_inet.h

// Package net_inet provides direct TinyGo bindings for pspnet_inet.h.
package net_inet

import "unsafe"

var _ unsafe.Pointer

const (
	SCHED_OTHER               = 0
	SCHED_MIN                 = 0
	SCHED_MAX                 = 2
	PTHREAD_MUTEX_TIMED_NP    = 0
	PTHREAD_MUTEX_ADAPTIVE_NP = 0
	PTHREAD_MUTEX_NORMAL      = 0
	PTHREAD_MUTEX_RECURSIVE   = 1
	PTHREAD_MUTEX_ERRORCHECK  = 2
	PTHREAD_MUTEX_DEFAULT     = 0
)

//go:linkname SceNetInetInit sceNetInetInit
func SceNetInetInit() int32

//go:linkname SceNetInetSelect sceNetInetSelect
func SceNetInetSelect(n int32, readfds unsafe.Pointer, writefds unsafe.Pointer, exceptfds unsafe.Pointer, timeout unsafe.Pointer) int32

//go:linkname SceNetInetTerm sceNetInetTerm
func SceNetInetTerm() int32

//go:linkname SceNetInetGetErrno sceNetInetGetErrno
func SceNetInetGetErrno() int32

//go:linkname SceNetInetAccept sceNetInetAccept
func SceNetInetAccept(s int32, addr unsafe.Pointer, addrlen unsafe.Pointer) int32

//go:linkname SceNetInetBind sceNetInetBind
func SceNetInetBind(s int32, my_addr unsafe.Pointer, addrlen uint32) int32

//go:linkname SceNetInetConnect sceNetInetConnect
func SceNetInetConnect(s int32, serv_addr unsafe.Pointer, addrlen uint32) int32

//go:linkname SceNetInetGetsockopt sceNetInetGetsockopt
func SceNetInetGetsockopt(s int32, level int32, optname int32, optval unsafe.Pointer, optlen unsafe.Pointer) int32

//go:linkname SceNetInetListen sceNetInetListen
func SceNetInetListen(s int32, backlog int32) int32

//go:linkname SceNetInetRecv sceNetInetRecv
func SceNetInetRecv(s int32, buf unsafe.Pointer, len uint32, flags int32) int32

//go:linkname SceNetInetRecvfrom sceNetInetRecvfrom
func SceNetInetRecvfrom(s int32, buf unsafe.Pointer, flags uint32, arg3 int32, from unsafe.Pointer, fromlen unsafe.Pointer) int32

//go:linkname SceNetInetSend sceNetInetSend
func SceNetInetSend(s int32, buf unsafe.Pointer, len uint32, flags int32) int32

//go:linkname SceNetInetSendto sceNetInetSendto
func SceNetInetSendto(s int32, buf unsafe.Pointer, len uint32, flags int32, to unsafe.Pointer, tolen uint32) int32

//go:linkname SceNetInetSetsockopt sceNetInetSetsockopt
func SceNetInetSetsockopt(s int32, level int32, optname int32, optval unsafe.Pointer, optlen uint32) int32

//go:linkname SceNetInetShutdown sceNetInetShutdown
func SceNetInetShutdown(s int32, how int32) int32

//go:linkname SceNetInetSocket sceNetInetSocket
func SceNetInetSocket(domain int32, typeValue int32, protocol int32) int32

//go:linkname SceNetInetClose sceNetInetClose
func SceNetInetClose(s int32) int32

//go:linkname SceNetInetGetpeername sceNetInetGetpeername
func SceNetInetGetpeername(s int32, name unsafe.Pointer, namelen unsafe.Pointer) int32

//go:linkname SceNetInetGetsockname sceNetInetGetsockname
func SceNetInetGetsockname(s int32, name unsafe.Pointer, namelen unsafe.Pointer) int32

//go:linkname SceNetInetSendmsg sceNetInetSendmsg
func SceNetInetSendmsg(s int32, msg unsafe.Pointer, flags int32) int32

//go:linkname SceNetInetRecvmsg sceNetInetRecvmsg
func SceNetInetRecvmsg(s int32, msg unsafe.Pointer, flags int32) int32
