// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspusbstor.h

// Package usbstor provides direct TinyGo bindings for pspusbstor.h.
package usbstor

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUsbstorBootRegisterNotify sceUsbstorBootRegisterNotify
func SceUsbstorBootRegisterNotify(eventFlag int32) int32

//go:linkname SceUsbstorBootUnregisterNotify sceUsbstorBootUnregisterNotify
func SceUsbstorBootUnregisterNotify(eventFlag int32) int32

//go:linkname SceUsbstorBootSetCapacity sceUsbstorBootSetCapacity
func SceUsbstorBootSetCapacity(size int32) int32
