// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsystimer.h

// Package systimer provides direct TinyGo bindings for pspsystimer.h.
package systimer

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSTimerAlloc sceSTimerAlloc
func SceSTimerAlloc() int32

//go:linkname SceSTimerFree sceSTimerFree
func SceSTimerFree(timer int32)

//go:linkname SceSTimerStartCount sceSTimerStartCount
func SceSTimerStartCount(timer int32)

//go:linkname SceSTimerStopCount sceSTimerStopCount
func SceSTimerStopCount(timer int32)

//go:linkname SceSTimerResetCount sceSTimerResetCount
func SceSTimerResetCount(timer int32)

//go:linkname SceSTimerGetCount sceSTimerGetCount
func SceSTimerGetCount(timer int32, count unsafe.Pointer)

//go:linkname SceSTimerSetHandler sceSTimerSetHandler
func SceSTimerSetHandler(timer int32, cycle int32, handler unsafe.Pointer, unk1 int32)

//go:linkname SceSTimerSetTMCY sceSTimerSetTMCY
func SceSTimerSetTMCY(timer int32, unk1 int32)

//go:linkname SceSTimerSetPrscl sceSTimerSetPrscl
func SceSTimerSetPrscl(timer int32, unk1 int32, unk2 int32)
