// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspbtcnf.h

// Package btcnf provides direct TinyGo bindings for pspbtcnf.h.
package btcnf

import "unsafe"

var _ unsafe.Pointer

const (
	VSH_RUNLEVEL     = 1
	GAME_RUNLEVEL    = 2
	UPDATER_RUNLEVEL = 4
	POPS_RUNLEVEL    = 8
	APP_RUNLEVEL     = 32
	UMDEMU_RUNLEVEL  = 64
	MLNAPP_RUNLEVEL  = 128
)
