// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsysclib.h

// Package sysclib provides direct TinyGo bindings for pspsysclib.h.
package sysclib

import "unsafe"

var _ unsafe.Pointer

//go:linkname Prnt prnt
func Prnt(cb unsafe.Pointer, ctx unsafe.Pointer, fmt unsafe.Pointer, args unsafe.Pointer)
