// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_gamesharing.h

// Package utility_gamesharing provides direct TinyGo bindings for psputility_gamesharing.h.
package utility_gamesharing

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UTILITY_GAMESHARING_MODE_SINGLE      = 1
	PSP_UTILITY_GAMESHARING_MODE_MULTIPLE    = 2
	PSP_UTILITY_GAMESHARING_DATA_TYPE_FILE   = 1
	PSP_UTILITY_GAMESHARING_DATA_TYPE_MEMORY = 2
)

//go:linkname SceUtilityGameSharingInitStart sceUtilityGameSharingInitStart
func SceUtilityGameSharingInitStart(params unsafe.Pointer) int32

//go:linkname SceUtilityGameSharingShutdownStart sceUtilityGameSharingShutdownStart
func SceUtilityGameSharingShutdownStart()

//go:linkname SceUtilityGameSharingGetStatus sceUtilityGameSharingGetStatus
func SceUtilityGameSharingGetStatus() int32

//go:linkname SceUtilityGameSharingUpdate sceUtilityGameSharingUpdate
func SceUtilityGameSharingUpdate(n int32)
