// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspexception.h

// Package exception provides direct TinyGo bindings for pspexception.h.
package exception

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelRegisterDefaultExceptionHandler sceKernelRegisterDefaultExceptionHandler
func SceKernelRegisterDefaultExceptionHandler(funcValue unsafe.Pointer) int32

//go:linkname SceKernelRegisterExceptionHandler sceKernelRegisterExceptionHandler
func SceKernelRegisterExceptionHandler(exno int32, funcValue unsafe.Pointer) int32

//go:linkname SceKernelRegisterPriorityExceptionHandler sceKernelRegisterPriorityExceptionHandler
func SceKernelRegisterPriorityExceptionHandler(exno int32, priority int32, funcValue unsafe.Pointer) int32
