// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspprof.h

// Package prof provides direct TinyGo bindings for pspprof.h.
package prof

import "unsafe"

var _ unsafe.Pointer

//go:linkname Gprof_start gprof_start
func Gprof_start()

//go:linkname Gprof_stop gprof_stop
func Gprof_stop(filename unsafe.Pointer, should_dump int32)
