// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_savedata.h

// Package utility_savedata provides direct TinyGo bindings for psputility_savedata.h.
package utility_savedata

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UTILITY_SAVEDATA_AUTOLOAD      = 0
	PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN = 0
)

//go:linkname SceUtilitySavedataInitStart sceUtilitySavedataInitStart
func SceUtilitySavedataInitStart(params unsafe.Pointer) int32

//go:linkname SceUtilitySavedataGetStatus sceUtilitySavedataGetStatus
func SceUtilitySavedataGetStatus() int32

//go:linkname SceUtilitySavedataShutdownStart sceUtilitySavedataShutdownStart
func SceUtilitySavedataShutdownStart() int32

//go:linkname SceUtilitySavedataUpdate sceUtilitySavedataUpdate
func SceUtilitySavedataUpdate(unknown int32)
