// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_apctl.h

// Package net_apctl provides direct TinyGo bindings for pspnet_apctl.h.
package net_apctl

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceNetApctlInit sceNetApctlInit
func SceNetApctlInit(stackSize int32, initPriority int32) int32

//go:linkname SceNetApctlTerm sceNetApctlTerm
func SceNetApctlTerm() int32

//go:linkname SceNetApctlGetInfo sceNetApctlGetInfo
func SceNetApctlGetInfo(code int32, pInfo unsafe.Pointer) int32

//go:linkname SceNetApctlAddHandler sceNetApctlAddHandler
func SceNetApctlAddHandler(handler unsafe.Pointer, pArg unsafe.Pointer) int32

//go:linkname SceNetApctlDelHandler sceNetApctlDelHandler
func SceNetApctlDelHandler(handlerId int32) int32

//go:linkname SceNetApctlConnect sceNetApctlConnect
func SceNetApctlConnect(connIndex int32) int32

//go:linkname SceNetApctlDisconnect sceNetApctlDisconnect
func SceNetApctlDisconnect() int32

//go:linkname SceNetApctlGetState sceNetApctlGetState
func SceNetApctlGetState(pState unsafe.Pointer) int32
