// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspiofilemgr_fcntl.h

// Package iofilemgr_fcntl provides direct TinyGo bindings for pspiofilemgr_fcntl.h.
package iofilemgr_fcntl

import "unsafe"

var _ unsafe.Pointer
