// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspkdebug.h

// Package kdebug provides direct TinyGo bindings for pspkdebug.h.
package kdebug

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelRegisterDebugPutchar sceKernelRegisterDebugPutchar
func SceKernelRegisterDebugPutchar(funcValue unsafe.Pointer)

//go:linkname SceKernelGetDebugPutchar sceKernelGetDebugPutchar
func SceKernelGetDebugPutchar() int32

// Unsupported C declarations:
// - Kprintf: variadic
