// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspaudio_kernel.h

// Package audio_kernel provides direct TinyGo bindings for pspaudio_kernel.h.
package audio_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspaudioDriver() }

//go:linkname requirePspaudioDriver pspsdk_go_require_pspaudio_driver
func requirePspaudioDriver()

const (
	PSP_AUDIO_FREQ_44K = 44100
	PSP_AUDIO_FREQ_48K = 48000
)

//go:linkname SceAudioSetFrequency sceAudioSetFrequency
func SceAudioSetFrequency(frequency int32) int32
