// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspimpose_driver.h

// Package impose_driver provides direct TinyGo bindings for pspimpose_driver.h.
package impose_driver

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

//go:linkname SceImposeGetParam sceImposeGetParam
func SceImposeGetParam(param int32) int32

//go:linkname SceImposeSetParam sceImposeSetParam
func SceImposeSetParam(param int32, value int32) int32

//go:linkname SceImposeGetBacklightOffTime sceImposeGetBacklightOffTime
func SceImposeGetBacklightOffTime() int32

//go:linkname SceImposeSetBacklightOffTime sceImposeSetBacklightOffTime
func SceImposeSetBacklightOffTime(value int32) int32

//go:linkname SceImposeGetLanguageMode sceImposeGetLanguageMode
func SceImposeGetLanguageMode(lang unsafe.Pointer, button unsafe.Pointer) int32

//go:linkname SceImposeSetLanguageMode sceImposeSetLanguageMode
func SceImposeSetLanguageMode(lang int32, button int32) int32

//go:linkname SceImposeGetUMDPopup sceImposeGetUMDPopup
func SceImposeGetUMDPopup() int32

//go:linkname SceImposeSetUMDPopup sceImposeSetUMDPopup
func SceImposeSetUMDPopup(value int32) int32

//go:linkname SceImposeGetHomePopup sceImposeGetHomePopup
func SceImposeGetHomePopup() int32

//go:linkname SceImposeSetHomePopup sceImposeSetHomePopup
func SceImposeSetHomePopup(value int32) int32

//go:linkname SceImposeCheckVideoOut sceImposeCheckVideoOut
func SceImposeCheckVideoOut(value unsafe.Pointer) int32
