// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: vlf.h

// Package vlf provides direct TinyGo bindings for vlf.h.
package vlf

import "unsafe"

var _ unsafe.Pointer

func init() { requireVlfgui() }

//go:linkname requireVlfgui pspsdk_go_require_vlfgui
func requireVlfgui()

const (
	VLF_TEXT                  = 0
	VLF_PIC                   = 1
	VLF_SHADOWED_PIC          = 2
	VLF_PROGRESS_BAR          = 3
	VLF_ENTER                 = 0
	VLF_CANCEL                = 1
	VLF_CROSS                 = 2
	VLF_CIRCLE                = 3
	VLF_TRIANGLE              = 4
	VLF_SQUARE                = 5
	VLF_MD_BUTTONS_NONE       = 0
	VLF_MD_BUTTONS_YESNO      = 16
	VLF_MD_INITIAL_CURSOR_YES = 0
	VLF_MD_INITIAL_CURSOR_NO  = 256
	PSP_CTRL_ENTER            = 1073741824
	PSP_CTRL_CANCEL           = 2147483648
)

//go:linkname VlfGuiInit vlfGuiInit
func VlfGuiInit(heap_size int32, app_main unsafe.Pointer)

//go:linkname VlfGuiSystemSetup vlfGuiSystemSetup
func VlfGuiSystemSetup(battery int32, clock int32, notuserwp int32) int32

//go:linkname VlfGuiGetLanguage vlfGuiGetLanguage
func VlfGuiGetLanguage() int32

//go:linkname VlfGuiSetLanguage vlfGuiSetLanguage
func VlfGuiSetLanguage(lang int32)

//go:linkname VlfGuiGetButtonConfig vlfGuiGetButtonConfig
func VlfGuiGetButtonConfig() int32

//go:linkname VlfGuiSetButtonConfig vlfGuiSetButtonConfig
func VlfGuiSetButtonConfig(config int32)

//go:linkname VlfGuiSetResourceDir vlfGuiSetResourceDir
func VlfGuiSetResourceDir(dir unsafe.Pointer)

//go:linkname VlfGuiDrawFrame vlfGuiDrawFrame
func VlfGuiDrawFrame()

//go:linkname VlfGuiLoadResources vlfGuiLoadResources
func VlfGuiLoadResources(rco unsafe.Pointer, n int32, names unsafe.Pointer, types unsafe.Pointer, datas unsafe.Pointer, sizes unsafe.Pointer, pntable unsafe.Pointer) int32

//go:linkname VlfGuiCacheResource vlfGuiCacheResource
func VlfGuiCacheResource(rco unsafe.Pointer) int32

//go:linkname VlfGuiUncacheResource vlfGuiUncacheResource
func VlfGuiUncacheResource(rco unsafe.Pointer) int32

//go:linkname VlfGuiGetResourceSubParam vlfGuiGetResourceSubParam
func VlfGuiGetResourceSubParam(entry unsafe.Pointer, insize int32, ntable unsafe.Pointer, name unsafe.Pointer, data unsafe.Pointer, size unsafe.Pointer) int32

//go:linkname VlfGuiLoadLabel vlfGuiLoadLabel
func VlfGuiLoadLabel(str unsafe.Pointer, rco unsafe.Pointer, name unsafe.Pointer) int32

//go:linkname VlfGuiSetBackground vlfGuiSetBackground
func VlfGuiSetBackground(texture unsafe.Pointer, width int32, height int32, swizzled int32, scale_x float32, scale_y float32) int32

//go:linkname VlfGuiSetBackgroundFileBuffer vlfGuiSetBackgroundFileBuffer
func VlfGuiSetBackgroundFileBuffer(data unsafe.Pointer, size int32) int32

//go:linkname VlfGuiSetBackgroundFile vlfGuiSetBackgroundFile
func VlfGuiSetBackgroundFile(file unsafe.Pointer) int32

//go:linkname VlfGuiSetBackgroundIndex vlfGuiSetBackgroundIndex
func VlfGuiSetBackgroundIndex(index int32) int32

//go:linkname VlfGuiSetBackgroundDate vlfGuiSetBackgroundDate
func VlfGuiSetBackgroundDate() int32

//go:linkname VlfGuiSetBackgroundPlane vlfGuiSetBackgroundPlane
func VlfGuiSetBackgroundPlane(color int32) int32

//go:linkname VlfGuiSetBackgroundSystem vlfGuiSetBackgroundSystem
func VlfGuiSetBackgroundSystem(notuserwp int32) int32

//go:linkname VlfGuiSetSystemColor vlfGuiSetSystemColor
func VlfGuiSetSystemColor(index int32)

//go:linkname VlfGuiSetModel vlfGuiSetModel
func VlfGuiSetModel(data unsafe.Pointer, size int32) int32

//go:linkname VlfGuiSetModelFile vlfGuiSetModelFile
func VlfGuiSetModelFile(file unsafe.Pointer) int32

//go:linkname VlfGuiSetModelResource vlfGuiSetModelResource
func VlfGuiSetModelResource(rco unsafe.Pointer, name unsafe.Pointer) int32

//go:linkname VlfGuiSetModelSystem vlfGuiSetModelSystem
func VlfGuiSetModelSystem() int32

//go:linkname VlfGuiSetModelWorldMatrix vlfGuiSetModelWorldMatrix
func VlfGuiSetModelWorldMatrix(matrix unsafe.Pointer)

//go:linkname VlfGuiGetModelWorldMatrix vlfGuiGetModelWorldMatrix
func VlfGuiGetModelWorldMatrix() unsafe.Pointer

//go:linkname VlfGuiSetTitleBar vlfGuiSetTitleBar
func VlfGuiSetTitleBar(text int32, pic int32, visible int32, hideobj int32)

//go:linkname VlfGuiSetTitleBarEx vlfGuiSetTitleBarEx
func VlfGuiSetTitleBarEx(text int32, pic int32, visible int32, hideobj int32, color int32)

//go:linkname VlfGuiSetTitleBarVisibility vlfGuiSetTitleBarVisibility
func VlfGuiSetTitleBarVisibility(visible int32)

//go:linkname VlfGuiAddText vlfGuiAddText
func VlfGuiAddText(x int32, y int32, string unsafe.Pointer) int32

//go:linkname VlfGuiAddTextW vlfGuiAddTextW
func VlfGuiAddTextW(x int32, y int32, string unsafe.Pointer) int32

//go:linkname VlfGuiAddTextResource vlfGuiAddTextResource
func VlfGuiAddTextResource(rco unsafe.Pointer, name unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiRemoveText vlfGuiRemoveText
func VlfGuiRemoveText(text int32) int32

//go:linkname VlfGuiSetText vlfGuiSetText
func VlfGuiSetText(text int32, string unsafe.Pointer) int32

//go:linkname VlfGuiSetTextW vlfGuiSetTextW
func VlfGuiSetTextW(text int32, string unsafe.Pointer) int32

//go:linkname VlfGuiSetTextFocus vlfGuiSetTextFocus
func VlfGuiSetTextFocus(text int32) int32

//go:linkname VlfGuiRemoveTextFocus vlfGuiRemoveTextFocus
func VlfGuiRemoveTextFocus(text int32, keepres int32) int32

//go:linkname VlfGuiSetTextVisibility vlfGuiSetTextVisibility
func VlfGuiSetTextVisibility(text int32, visible int32) int32

//go:linkname VlfGuiSetTextBlinking vlfGuiSetTextBlinking
func VlfGuiSetTextBlinking(text int32, nshow int32, nhide int32) int32

//go:linkname VlfGuiSetTextFade vlfGuiSetTextFade
func VlfGuiSetTextFade(text int32, mode int32, effect int32, direction_out int32) int32

//go:linkname VlfGuiSetTextAlignment vlfGuiSetTextAlignment
func VlfGuiSetTextAlignment(text int32, alignment int32) int32

//go:linkname VlfGuiSetTextXY vlfGuiSetTextXY
func VlfGuiSetTextXY(text int32, x int32, y int32) int32

//go:linkname VlfGuiSetTextSize vlfGuiSetTextSize
func VlfGuiSetTextSize(text int32, size float32) int32

//go:linkname VlfGuiChangeCharacterByButton vlfGuiChangeCharacterByButton
func VlfGuiChangeCharacterByButton(ch int32, button int32) int32

//go:linkname VlfGuiAddPicture vlfGuiAddPicture
func VlfGuiAddPicture(data unsafe.Pointer, size int32, x int32, y int32) int32

//go:linkname VlfGuiAddPictureFile vlfGuiAddPictureFile
func VlfGuiAddPictureFile(file unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddPictureResource vlfGuiAddPictureResource
func VlfGuiAddPictureResource(rco unsafe.Pointer, name unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiRemovePicture vlfGuiRemovePicture
func VlfGuiRemovePicture(pic int32) int32

//go:linkname VlfGuiSetPictureXY vlfGuiSetPictureXY
func VlfGuiSetPictureXY(pic int32, x int32, y int32) int32

//go:linkname VlfGuiGetPictureSize vlfGuiGetPictureSize
func VlfGuiGetPictureSize(pic int32, width unsafe.Pointer, height unsafe.Pointer) int32

//go:linkname VlfGuiSetPictureDisplayArea vlfGuiSetPictureDisplayArea
func VlfGuiSetPictureDisplayArea(pic int32, x int32, y int32, width int32, height int32) int32

//go:linkname VlfGuiSetPictureAlphaBlend vlfGuiSetPictureAlphaBlend
func VlfGuiSetPictureAlphaBlend(pic int32, op int32, src int32, dst int32, srcfix int32, dstfix int32) int32

//go:linkname VlfGuiClonePicture vlfGuiClonePicture
func VlfGuiClonePicture(pic int32, real int32, x int32, y int32) int32

//go:linkname VlfGuiSetPictureVisibility vlfGuiSetPictureVisibility
func VlfGuiSetPictureVisibility(pic int32, visible int32) int32

//go:linkname VlfGuiSetPictureBlinking vlfGuiSetPictureBlinking
func VlfGuiSetPictureBlinking(pic int32, nshow int32, nhide int32) int32

//go:linkname VlfGuiAnimatePicture vlfGuiAnimatePicture
func VlfGuiAnimatePicture(pic int32, w int32, h int32, frames int32, vertical int32) int32

//go:linkname VlfGuiSetPictureFade vlfGuiSetPictureFade
func VlfGuiSetPictureFade(pic int32, mode int32, effect int32, direction_out int32) int32

//go:linkname VlfGuiAddShadowedPicture vlfGuiAddShadowedPicture
func VlfGuiAddShadowedPicture(sp unsafe.Pointer, pic unsafe.Pointer, pic_size int32, shpic unsafe.Pointer, shpic_size int32, x int32, y int32, sh_offsx int32, sh_offsy int32, shadow_before int32) int32

//go:linkname VlfGuiAddShadowedPictureFile vlfGuiAddShadowedPictureFile
func VlfGuiAddShadowedPictureFile(sp unsafe.Pointer, pic unsafe.Pointer, shpic unsafe.Pointer, x int32, y int32, sh_offsx int32, sh_offsy int32, shadow_before int32) int32

//go:linkname VlfGuiAddShadowedPictureResource vlfGuiAddShadowedPictureResource
func VlfGuiAddShadowedPictureResource(sp unsafe.Pointer, rco unsafe.Pointer, pic unsafe.Pointer, shpic unsafe.Pointer, x int32, y int32, sh_offsx int32, sh_offsy int32, shadow_before int32) int32

//go:linkname VlfGuiRemoveShadowedPicture vlfGuiRemoveShadowedPicture
func VlfGuiRemoveShadowedPicture(sp unsafe.Pointer) int32

//go:linkname VlfGuiSetShadowedPictureVisibility vlfGuiSetShadowedPictureVisibility
func VlfGuiSetShadowedPictureVisibility(sp unsafe.Pointer, visible int32) int32

//go:linkname VlfGuiSetShadowedPictureBlinking vlfGuiSetShadowedPictureBlinking
func VlfGuiSetShadowedPictureBlinking(sp unsafe.Pointer, nshow int32, nhide int32) int32

//go:linkname VlfGuiAnimateShadowedPicture vlfGuiAnimateShadowedPicture
func VlfGuiAnimateShadowedPicture(sp unsafe.Pointer, w int32, h int32, ws int32, hs int32, frames int32, vertical int32) int32

//go:linkname VlfGuiSetShadowedPictureFade vlfGuiSetShadowedPictureFade
func VlfGuiSetShadowedPictureFade(sp unsafe.Pointer, mode int32, effect int32, direction_out int32) int32

//go:linkname VlfGuiAddBatteryIcon vlfGuiAddBatteryIcon
func VlfGuiAddBatteryIcon(baticon unsafe.Pointer, status int32, blink int32) int32

//go:linkname VlfGuiAddBatteryIconEx vlfGuiAddBatteryIconEx
func VlfGuiAddBatteryIconEx(baticon unsafe.Pointer, x int32, y int32, status int32, blink int32) int32

//go:linkname VlfGuiAddBatteryIconSystem vlfGuiAddBatteryIconSystem
func VlfGuiAddBatteryIconSystem(baticon unsafe.Pointer, timer_ms int32) int32

//go:linkname VlfGuiSetBatteryIconStatus vlfGuiSetBatteryIconStatus
func VlfGuiSetBatteryIconStatus(baticon unsafe.Pointer, status int32, blink int32) int32

//go:linkname VlfGuiRemoveBatteryIcon vlfGuiRemoveBatteryIcon
func VlfGuiRemoveBatteryIcon(baticon unsafe.Pointer) int32

//go:linkname VlfGuiAddClock vlfGuiAddClock
func VlfGuiAddClock() int32

//go:linkname VlfGuiAddWaitIcon vlfGuiAddWaitIcon
func VlfGuiAddWaitIcon(waiticon unsafe.Pointer) int32

//go:linkname VlfGuiAddWaitIconEx vlfGuiAddWaitIconEx
func VlfGuiAddWaitIconEx(waiticon unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddCross vlfGuiAddCross
func VlfGuiAddCross(cross unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddCircle vlfGuiAddCircle
func VlfGuiAddCircle(circle unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddTriangle vlfGuiAddTriangle
func VlfGuiAddTriangle(triangle unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddSquare vlfGuiAddSquare
func VlfGuiAddSquare(square unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddEnter vlfGuiAddEnter
func VlfGuiAddEnter(enter unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddCancel vlfGuiAddCancel
func VlfGuiAddCancel(cancel unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddSpinUp vlfGuiAddSpinUp
func VlfGuiAddSpinUp(spinup unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddSpinDown vlfGuiAddSpinDown
func VlfGuiAddSpinDown(spindown unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddArrowLeft vlfGuiAddArrowLeft
func VlfGuiAddArrowLeft(arrowleft unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddArrowRight vlfGuiAddArrowRight
func VlfGuiAddArrowRight(arrowright unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddGameIcon vlfGuiAddGameIcon
func VlfGuiAddGameIcon(game unsafe.Pointer, x int32, y int32) int32

//go:linkname VlfGuiAddProgressBar vlfGuiAddProgressBar
func VlfGuiAddProgressBar(y int32) int32

//go:linkname VlfGuiAddProgressBarEx vlfGuiAddProgressBarEx
func VlfGuiAddProgressBarEx(x int32, y int32) int32

//go:linkname VlfGuiRemoveProgressBar vlfGuiRemoveProgressBar
func VlfGuiRemoveProgressBar(pb int32) int32

//go:linkname VlfGuiProgressBarSetProgress vlfGuiProgressBarSetProgress
func VlfGuiProgressBarSetProgress(pb int32, perc int32) int32

//go:linkname VlfGuiSetRectangleVisibility vlfGuiSetRectangleVisibility
func VlfGuiSetRectangleVisibility(x int32, y int32, w int32, h int32, visible int32) int32

//go:linkname VlfGuiSaveRectangleVisibilityContext vlfGuiSaveRectangleVisibilityContext
func VlfGuiSaveRectangleVisibilityContext(x int32, y int32, w int32, h int32) unsafe.Pointer

//go:linkname VlfGuiRestoreVisibilityContext vlfGuiRestoreVisibilityContext
func VlfGuiRestoreVisibilityContext(ctx unsafe.Pointer)

//go:linkname VlfGuiFreeVisibilityContext vlfGuiFreeVisibilityContext
func VlfGuiFreeVisibilityContext(ctx unsafe.Pointer)

//go:linkname VlfGuiSetRectangleBlinking vlfGuiSetRectangleBlinking
func VlfGuiSetRectangleBlinking(x int32, y int32, w int32, h int32, nshow int32, nhide int32) int32

//go:linkname VlfGuiSetSynchronizedBlinking vlfGuiSetSynchronizedBlinking
func VlfGuiSetSynchronizedBlinking(dst unsafe.Pointer, dst_type int32, src unsafe.Pointer, src_type int32) int32

//go:linkname VlfGuiMessageDialog vlfGuiMessageDialog
func VlfGuiMessageDialog(msg unsafe.Pointer, flags int32) int32

//go:linkname VlfGuiErrorDialog vlfGuiErrorDialog
func VlfGuiErrorDialog(error int32) int32

//go:linkname VlfGuiNetConfDialog vlfGuiNetConfDialog
func VlfGuiNetConfDialog() int32

//go:linkname VlfGuiBottomDialog vlfGuiBottomDialog
func VlfGuiBottomDialog(button1 int32, button2 int32, automatic int32, enter_is_left int32, distance int32, handler unsafe.Pointer) int32

//go:linkname VlfGuiCustomBottomDialog vlfGuiCustomBottomDialog
func VlfGuiCustomBottomDialog(button1 unsafe.Pointer, button2 unsafe.Pointer, automatic int32, enter_is_left int32, distance int32, handler unsafe.Pointer) int32

//go:linkname VlfGuiCancelBottomDialog vlfGuiCancelBottomDialog
func VlfGuiCancelBottomDialog()

//go:linkname VlfGuiCentralMenu vlfGuiCentralMenu
func VlfGuiCentralMenu(noptions int32, items unsafe.Pointer, defaultsel int32, handler unsafe.Pointer, dispx int32, dispy int32) int32

//go:linkname VlfGuiCancelCentralMenu vlfGuiCancelCentralMenu
func VlfGuiCancelCentralMenu()

//go:linkname VlfGuiCentralMenuSelection vlfGuiCentralMenuSelection
func VlfGuiCentralMenuSelection() int32

//go:linkname VlfGuiAddIntegerSpinControl vlfGuiAddIntegerSpinControl
func VlfGuiAddIntegerSpinControl(x int32, y int32, min int32, max int32, cur int32, step int32, loop int32, speed int32, initstate int32, prefix unsafe.Pointer, suffix unsafe.Pointer) int32

//go:linkname VlfGuiRemoveSpinControl vlfGuiRemoveSpinControl
func VlfGuiRemoveSpinControl(spin int32) int32

//go:linkname VlfGuiSetSpinState vlfGuiSetSpinState
func VlfGuiSetSpinState(spin int32, state int32) int32

//go:linkname VlfGuiSetIntegerSpinMinMax vlfGuiSetIntegerSpinMinMax
func VlfGuiSetIntegerSpinMinMax(spin int32, min int32, max int32) int32

//go:linkname VlfGuiGetIntegerSpinValue vlfGuiGetIntegerSpinValue
func VlfGuiGetIntegerSpinValue(spin int32, value unsafe.Pointer) int32

//go:linkname VlfGuiSetIntegerSpinValue vlfGuiSetIntegerSpinValue
func VlfGuiSetIntegerSpinValue(spin int32, value int32) int32

//go:linkname VlfGuiPreviousPageControl vlfGuiPreviousPageControl
func VlfGuiPreviousPageControl(handler unsafe.Pointer) int32

//go:linkname VlfGuiNextPageControl vlfGuiNextPageControl
func VlfGuiNextPageControl(handler unsafe.Pointer) int32

//go:linkname VlfGuiCancelPreviousPageControl vlfGuiCancelPreviousPageControl
func VlfGuiCancelPreviousPageControl()

//go:linkname VlfGuiCancelNextPageControl vlfGuiCancelNextPageControl
func VlfGuiCancelNextPageControl()

//go:linkname VlfGuiSetPageControlEnable vlfGuiSetPageControlEnable
func VlfGuiSetPageControlEnable(enable int32)

//go:linkname VlfGuiAddEventHandler vlfGuiAddEventHandler
func VlfGuiAddEventHandler(buttons int32, wait int32, funcValue unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname VlfGuiAddNegativeEventHandler vlfGuiAddNegativeEventHandler
func VlfGuiAddNegativeEventHandler(buttons int32, wait int32, funcValue unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname VlfGuiRemoveEventHandler vlfGuiRemoveEventHandler
func VlfGuiRemoveEventHandler(funcValue unsafe.Pointer) int32

//go:linkname VlfGuiRemoveEventHandlerEx vlfGuiRemoveEventHandlerEx
func VlfGuiRemoveEventHandlerEx(funcValue unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname VlfGuiIsEventRegistered vlfGuiIsEventRegistered
func VlfGuiIsEventRegistered(funcValue unsafe.Pointer) int32

//go:linkname VlfGuiSetEventDelay vlfGuiSetEventDelay
func VlfGuiSetEventDelay(funcValue unsafe.Pointer, delay int32) int32

//go:linkname VlfGuiSetEventDelayEx vlfGuiSetEventDelayEx
func VlfGuiSetEventDelayEx(funcValue unsafe.Pointer, param unsafe.Pointer, delay int32) int32

//go:linkname VlfGuiDelayAllEvents vlfGuiDelayAllEvents
func VlfGuiDelayAllEvents(delay int32) int32

// Unsupported C declarations:
// - vlfGuiAddTextF: variadic
// - vlfGuiSetTextF: variadic
