// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspwlan.h

// Package wlan provides direct TinyGo bindings for pspwlan.h.
package wlan

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceWlanDevIsPowerOn sceWlanDevIsPowerOn
func SceWlanDevIsPowerOn() int32

//go:linkname SceWlanGetSwitchState sceWlanGetSwitchState
func SceWlanGetSwitchState() int32

//go:linkname SceWlanGetEtherAddr sceWlanGetEtherAddr
func SceWlanGetEtherAddr(etherAddr unsafe.Pointer) int32

//go:linkname SceWlanDevAttach sceWlanDevAttach
func SceWlanDevAttach() int32

//go:linkname SceWlanDevDetach sceWlanDevDetach
func SceWlanDevDetach() int32
