// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsuspend.h

// Package suspend provides direct TinyGo bindings for pspsuspend.h.
package suspend

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelVolatileMemLock sceKernelVolatileMemLock
func SceKernelVolatileMemLock(unk int32, ptr unsafe.Pointer, size unsafe.Pointer) int32

//go:linkname SceKernelVolatileMemTryLock sceKernelVolatileMemTryLock
func SceKernelVolatileMemTryLock(unk int32, ptr unsafe.Pointer, size unsafe.Pointer) int32

//go:linkname SceKernelVolatileMemUnlock sceKernelVolatileMemUnlock
func SceKernelVolatileMemUnlock(unk int32) int32
