// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_adhocmatching.h

// Package net_adhocmatching provides direct TinyGo bindings for pspnet_adhocmatching.h.
package net_adhocmatching

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_ADHOC_MATCHING_EVENT_HELLO        = 1
	PSP_ADHOC_MATCHING_EVENT_JOIN         = 2
	PSP_ADHOC_MATCHING_EVENT_LEFT         = 3
	PSP_ADHOC_MATCHING_EVENT_REJECT       = 4
	PSP_ADHOC_MATCHING_EVENT_CANCEL       = 5
	PSP_ADHOC_MATCHING_EVENT_ACCEPT       = 6
	PSP_ADHOC_MATCHING_EVENT_COMPLETE     = 7
	PSP_ADHOC_MATCHING_EVENT_TIMEOUT      = 8
	PSP_ADHOC_MATCHING_EVENT_ERROR        = 9
	PSP_ADHOC_MATCHING_EVENT_DISCONNECT   = 10
	PSP_ADHOC_MATCHING_EVENT_DATA         = 11
	PSP_ADHOC_MATCHING_EVENT_DATA_CONFIRM = 12
	PSP_ADHOC_MATCHING_EVENT_DATA_TIMEOUT = 13
	PSP_ADHOC_MATCHING_MODE_HOST          = 1
	PSP_ADHOC_MATCHING_MODE_CLIENT        = 2
	PSP_ADHOC_MATCHING_MODE_PTP           = 3
)

//go:linkname SceNetAdhocMatchingInit sceNetAdhocMatchingInit
func SceNetAdhocMatchingInit(memsize int32) int32

//go:linkname SceNetAdhocMatchingTerm sceNetAdhocMatchingTerm
func SceNetAdhocMatchingTerm() int32

//go:linkname SceNetAdhocMatchingCreate sceNetAdhocMatchingCreate
func SceNetAdhocMatchingCreate(mode int32, maxpeers int32, port uint16, bufsize int32, hellodelay uint32, pingdelay uint32, initcount int32, msgdelay uint32, callback unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingDelete sceNetAdhocMatchingDelete
func SceNetAdhocMatchingDelete(matchingid int32) int32

//go:linkname SceNetAdhocMatchingStart sceNetAdhocMatchingStart
func SceNetAdhocMatchingStart(matchingid int32, evthpri int32, evthstack int32, inthpri int32, inthstack int32, optlen int32, optdata unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingStop sceNetAdhocMatchingStop
func SceNetAdhocMatchingStop(matchingid int32) int32

//go:linkname SceNetAdhocMatchingSelectTarget sceNetAdhocMatchingSelectTarget
func SceNetAdhocMatchingSelectTarget(matchingid int32, mac unsafe.Pointer, optlen int32, optdata unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingCancelTarget sceNetAdhocMatchingCancelTarget
func SceNetAdhocMatchingCancelTarget(matchingid int32, mac unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingCancelTargetWithOpt sceNetAdhocMatchingCancelTargetWithOpt
func SceNetAdhocMatchingCancelTargetWithOpt(matchingid int32, mac unsafe.Pointer, optlen int32, optdata unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingSendData sceNetAdhocMatchingSendData
func SceNetAdhocMatchingSendData(matchingid int32, mac unsafe.Pointer, datalen int32, data unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingAbortSendData sceNetAdhocMatchingAbortSendData
func SceNetAdhocMatchingAbortSendData(matchingid int32, mac unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingSetHelloOpt sceNetAdhocMatchingSetHelloOpt
func SceNetAdhocMatchingSetHelloOpt(matchingid int32, optlen int32, optdata unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingGetHelloOpt sceNetAdhocMatchingGetHelloOpt
func SceNetAdhocMatchingGetHelloOpt(matchingid int32, optlen unsafe.Pointer, optdata unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingGetMembers sceNetAdhocMatchingGetMembers
func SceNetAdhocMatchingGetMembers(matchingid int32, length unsafe.Pointer, buf unsafe.Pointer) int32

//go:linkname SceNetAdhocMatchingGetPoolMaxAlloc sceNetAdhocMatchingGetPoolMaxAlloc
func SceNetAdhocMatchingGetPoolMaxAlloc() int32

//go:linkname SceNetAdhocMatchingGetPoolStat sceNetAdhocMatchingGetPoolStat
func SceNetAdhocMatchingGetPoolStat(poolstat unsafe.Pointer) int32
