// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspumd.h

// Package umd provides direct TinyGo bindings for pspumd.h.
package umd

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UMD_TYPE_GAME   = 16
	PSP_UMD_TYPE_VIDEO  = 32
	PSP_UMD_TYPE_AUDIO  = 64
	PSP_UMD_NOT_PRESENT = 1
	PSP_UMD_PRESENT     = 2
	PSP_UMD_CHANGED     = 4
	PSP_UMD_INITING     = 8
	PSP_UMD_INITED      = 16
	PSP_UMD_READY       = 32
	UMD_WAITFORDISC     = 2
	UMD_WAITFORINIT     = 32
)

//go:linkname SceUmdCheckMedium sceUmdCheckMedium
func SceUmdCheckMedium() int32

//go:linkname SceUmdGetDiscInfo sceUmdGetDiscInfo
func SceUmdGetDiscInfo(info unsafe.Pointer) int32

//go:linkname SceUmdActivate sceUmdActivate
func SceUmdActivate(unit int32, drive unsafe.Pointer) int32

//go:linkname SceUmdDeactivate sceUmdDeactivate
func SceUmdDeactivate(unit int32, drive unsafe.Pointer) int32

//go:linkname SceUmdWaitDriveStat sceUmdWaitDriveStat
func SceUmdWaitDriveStat(stat int32) int32

//go:linkname SceUmdWaitDriveStatWithTimer sceUmdWaitDriveStatWithTimer
func SceUmdWaitDriveStatWithTimer(stat int32, timeout uint32) int32

//go:linkname SceUmdWaitDriveStatCB sceUmdWaitDriveStatCB
func SceUmdWaitDriveStatCB(stat int32, timeout uint32) int32

//go:linkname SceUmdCancelWaitDriveStat sceUmdCancelWaitDriveStat
func SceUmdCancelWaitDriveStat() int32

//go:linkname SceUmdGetDriveStat sceUmdGetDriveStat
func SceUmdGetDriveStat() int32

//go:linkname SceUmdGetErrorStat sceUmdGetErrorStat
func SceUmdGetErrorStat() int32

//go:linkname SceUmdRegisterUMDCallBack sceUmdRegisterUMDCallBack
func SceUmdRegisterUMDCallBack(cbid int32) int32

//go:linkname SceUmdUnRegisterUMDCallBack sceUmdUnRegisterUMDCallBack
func SceUmdUnRegisterUMDCallBack(cbid int32) int32

//go:linkname SceUmdReplacePermit sceUmdReplacePermit
func SceUmdReplacePermit() int32

//go:linkname SceUmdReplaceProhibit sceUmdReplaceProhibit
func SceUmdReplaceProhibit() int32
