// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_adhocctl.h

// Package net_adhocctl provides direct TinyGo bindings for pspnet_adhocctl.h.
package net_adhocctl

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceNetAdhocctlInit sceNetAdhocctlInit
func SceNetAdhocctlInit(stacksize int32, priority int32, product unsafe.Pointer) int32

//go:linkname SceNetAdhocctlTerm sceNetAdhocctlTerm
func SceNetAdhocctlTerm() int32

//go:linkname SceNetAdhocctlConnect sceNetAdhocctlConnect
func SceNetAdhocctlConnect(name unsafe.Pointer) int32

//go:linkname SceNetAdhocctlDisconnect sceNetAdhocctlDisconnect
func SceNetAdhocctlDisconnect() int32

//go:linkname SceNetAdhocctlGetState sceNetAdhocctlGetState
func SceNetAdhocctlGetState(event unsafe.Pointer) int32

//go:linkname SceNetAdhocctlCreate sceNetAdhocctlCreate
func SceNetAdhocctlCreate(name unsafe.Pointer) int32

//go:linkname SceNetAdhocctlJoin sceNetAdhocctlJoin
func SceNetAdhocctlJoin(scaninfo unsafe.Pointer) int32

//go:linkname SceNetAdhocctlGetAdhocId sceNetAdhocctlGetAdhocId
func SceNetAdhocctlGetAdhocId(product unsafe.Pointer) int32

//go:linkname SceNetAdhocctlCreateEnterGameMode sceNetAdhocctlCreateEnterGameMode
func SceNetAdhocctlCreateEnterGameMode(name unsafe.Pointer, unknown int32, num int32, macs unsafe.Pointer, timeout uint32, unknown2 int32) int32

//go:linkname SceNetAdhocctlJoinEnterGameMode sceNetAdhocctlJoinEnterGameMode
func SceNetAdhocctlJoinEnterGameMode(name unsafe.Pointer, hostmac unsafe.Pointer, timeout uint32, unknown int32) int32

//go:linkname SceNetAdhocctlGetGameModeInfo sceNetAdhocctlGetGameModeInfo
func SceNetAdhocctlGetGameModeInfo(gamemodeinfo unsafe.Pointer) int32

//go:linkname SceNetAdhocctlExitGameMode sceNetAdhocctlExitGameMode
func SceNetAdhocctlExitGameMode() int32

//go:linkname SceNetAdhocctlGetPeerList sceNetAdhocctlGetPeerList
func SceNetAdhocctlGetPeerList(length unsafe.Pointer, buf unsafe.Pointer) int32

//go:linkname SceNetAdhocctlGetPeerInfo sceNetAdhocctlGetPeerInfo
func SceNetAdhocctlGetPeerInfo(mac unsafe.Pointer, size int32, peerinfo unsafe.Pointer) int32

//go:linkname SceNetAdhocctlScan sceNetAdhocctlScan
func SceNetAdhocctlScan() int32

//go:linkname SceNetAdhocctlGetScanInfo sceNetAdhocctlGetScanInfo
func SceNetAdhocctlGetScanInfo(length unsafe.Pointer, buf unsafe.Pointer) int32

//go:linkname SceNetAdhocctlAddHandler sceNetAdhocctlAddHandler
func SceNetAdhocctlAddHandler(handler unsafe.Pointer, unknown unsafe.Pointer) int32

//go:linkname SceNetAdhocctlDelHandler sceNetAdhocctlDelHandler
func SceNetAdhocctlDelHandler(id int32) int32

//go:linkname SceNetAdhocctlGetNameByAddr sceNetAdhocctlGetNameByAddr
func SceNetAdhocctlGetNameByAddr(mac unsafe.Pointer, nickname unsafe.Pointer) int32

//go:linkname SceNetAdhocctlGetAddrByName sceNetAdhocctlGetAddrByName
func SceNetAdhocctlGetAddrByName(nickname unsafe.Pointer, length unsafe.Pointer, buf unsafe.Pointer) int32

//go:linkname SceNetAdhocctlGetParameter sceNetAdhocctlGetParameter
func SceNetAdhocctlGetParameter(params unsafe.Pointer) int32
