// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmpegbase.h

// Package mpegbase provides direct TinyGo bindings for pspmpegbase.h.
package mpegbase

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceMpegBaseYCrCbCopyVme sceMpegBaseYCrCbCopyVme
func SceMpegBaseYCrCbCopyVme(YUVBuffer unsafe.Pointer, Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceMpegBaseCscInit sceMpegBaseCscInit
func SceMpegBaseCscInit(width int32) int32

//go:linkname SceMpegBaseCscVme sceMpegBaseCscVme
func SceMpegBaseCscVme(pRGBbuffer unsafe.Pointer, pRGBbuffer2 unsafe.Pointer, width int32, pYCrCbBuffer unsafe.Pointer) int32

//go:linkname SceMpegbase_BEA18F91 sceMpegbase_BEA18F91
func SceMpegbase_BEA18F91(pLLI unsafe.Pointer) int32
