// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: dcman.h

// Package dcman provides direct TinyGo bindings for dcman.h.
package dcman

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspdcman() }

//go:linkname requirePspdcman pspsdk_go_require_pspdcman
func requirePspdcman()

//go:linkname DcGetHardwareInfo dcGetHardwareInfo
func DcGetHardwareInfo(ptachyon unsafe.Pointer, pbaryon unsafe.Pointer, ppommel unsafe.Pointer, pmb unsafe.Pointer, pfuseid unsafe.Pointer, pfuseconfig unsafe.Pointer, pnandsize unsafe.Pointer) int32

//go:linkname DcPatchModule dcPatchModule
func DcPatchModule(modname unsafe.Pointer, typeValue int32, addr int32, word int32) int32

//go:linkname DcPatchModuleString dcPatchModuleString
func DcPatchModuleString(modname unsafe.Pointer, string unsafe.Pointer, replace unsafe.Pointer) int32

//go:linkname DcGetCancelMode dcGetCancelMode
func DcGetCancelMode() int32

//go:linkname DcSetCancelMode dcSetCancelMode
func DcSetCancelMode(mode int32) int32

//go:linkname DcLflashStartFatfmt dcLflashStartFatfmt
func DcLflashStartFatfmt(argc int32, argv unsafe.Pointer) int32

//go:linkname DcLflashStartFDisk dcLflashStartFDisk
func DcLflashStartFDisk(argc int32, argv unsafe.Pointer) int32

//go:linkname DcGetNandInfo dcGetNandInfo
func DcGetNandInfo(pagesize unsafe.Pointer, ppb unsafe.Pointer, totalblocks unsafe.Pointer) int32

//go:linkname DcLockNand dcLockNand
func DcLockNand(flag int32) int32

//go:linkname DcUnlockNand dcUnlockNand
func DcUnlockNand() int32

//go:linkname DcReadNandBlock dcReadNandBlock
func DcReadNandBlock(page int32, block unsafe.Pointer) int32

//go:linkname DcWriteNandBlock dcWriteNandBlock
func DcWriteNandBlock(page int32, user unsafe.Pointer, spare unsafe.Pointer) int32

//go:linkname DcEraseNandBlock dcEraseNandBlock
func DcEraseNandBlock(page int32) int32

//go:linkname DcRegisterPhysicalFormatCallback dcRegisterPhysicalFormatCallback
func DcRegisterPhysicalFormatCallback(cbid int32) int32

//go:linkname DcUnregisterPhysicalFormatCallback dcUnregisterPhysicalFormatCallback
func DcUnregisterPhysicalFormatCallback() int32

//go:linkname DcQueryRealMacAddress dcQueryRealMacAddress
func DcQueryRealMacAddress(mac unsafe.Pointer) int32

//go:linkname DcIdStorageUnformat dcIdStorageUnformat
func DcIdStorageUnformat() int32

//go:linkname DcIdStorageFormat dcIdStorageFormat
func DcIdStorageFormat() int32

//go:linkname DcIdStorageCreateLeaf dcIdStorageCreateLeaf
func DcIdStorageCreateLeaf(leafid int32) int32

//go:linkname DcIdStorageCreateAtomicLeaves dcIdStorageCreateAtomicLeaves
func DcIdStorageCreateAtomicLeaves(leaves unsafe.Pointer, n int32) int32

//go:linkname DcIdStorageReadLeaf dcIdStorageReadLeaf
func DcIdStorageReadLeaf(leafid int32, buf unsafe.Pointer) int32

//go:linkname DcIdStorageWriteLeaf dcIdStorageWriteLeaf
func DcIdStorageWriteLeaf(leafid int32, buf unsafe.Pointer) int32

//go:linkname DcIdStorageFlush dcIdStorageFlush
func DcIdStorageFlush() int32

//go:linkname DcSysconReceiveSetParam dcSysconReceiveSetParam
func DcSysconReceiveSetParam(arg0 int32, arg1 unsafe.Pointer) int32

//go:linkname DcKirkCmd dcKirkCmd
func DcKirkCmd(in unsafe.Pointer, insize int32, out unsafe.Pointer, outsize int32, cmd int32) int32

//go:linkname SW SW
func SW(word int32, address int32)

//go:linkname LW LW
func LW(address int32) int32
