// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_sysparam.h

// Package utility_sysparam provides direct TinyGo bindings for psputility_sysparam.h.
package utility_sysparam

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilitySetSystemParamInt sceUtilitySetSystemParamInt
func SceUtilitySetSystemParamInt(id int32, value int32) int32

//go:linkname SceUtilitySetSystemParamString sceUtilitySetSystemParamString
func SceUtilitySetSystemParamString(id int32, str unsafe.Pointer) int32

//go:linkname SceUtilityGetSystemParamInt sceUtilityGetSystemParamInt
func SceUtilityGetSystemParamInt(id int32, value unsafe.Pointer) int32

//go:linkname SceUtilityGetSystemParamString sceUtilityGetSystemParamString
func SceUtilityGetSystemParamString(id int32, str unsafe.Pointer, len int32) int32
