// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_netparam.h

// Package utility_netparam provides direct TinyGo bindings for psputility_netparam.h.
package utility_netparam

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityCheckNetParam sceUtilityCheckNetParam
func SceUtilityCheckNetParam(id int32) int32

//go:linkname SceUtilityGetNetParam sceUtilityGetNetParam
func SceUtilityGetNetParam(conf int32, param int32, data unsafe.Pointer) int32

//go:linkname SceUtilityCreateNetParam sceUtilityCreateNetParam
func SceUtilityCreateNetParam(conf int32) int32

//go:linkname SceUtilitySetNetParam sceUtilitySetNetParam
func SceUtilitySetNetParam(param int32, val unsafe.Pointer) int32

//go:linkname SceUtilityCopyNetParam sceUtilityCopyNetParam
func SceUtilityCopyNetParam(src int32, dest int32) int32

//go:linkname SceUtilityDeleteNetParam sceUtilityDeleteNetParam
func SceUtilityDeleteNetParam(conf int32) int32
