// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmath.h

// Package math provides direct TinyGo bindings for pspmath.h.
package math

import "unsafe"

var _ unsafe.Pointer

//go:linkname PrintVFPURegisters printVFPURegisters
func PrintVFPURegisters(blockid int32)

//go:linkname Vfpu_srand vfpu_srand
func Vfpu_srand(x uint32)

//go:linkname Vfpu_randf vfpu_randf
func Vfpu_randf(min float32, max float32) float32

//go:linkname Vfpu_rand_8888 vfpu_rand_8888
func Vfpu_rand_8888(min int32, max int32) uint32

//go:linkname Vfpu_identity_matrix vfpu_identity_matrix
func Vfpu_identity_matrix(m unsafe.Pointer)

//go:linkname Vfpu_translate_matrix vfpu_translate_matrix
func Vfpu_translate_matrix(m unsafe.Pointer, x float32, y float32, z float32)

//go:linkname Vfpu_perspective_matrix vfpu_perspective_matrix
func Vfpu_perspective_matrix(m unsafe.Pointer, fovy float32, aspect float32, near float32, far float32)

//go:linkname Vfpu_ortho_matrix vfpu_ortho_matrix
func Vfpu_ortho_matrix(m unsafe.Pointer, left float32, right float32, bottom float32, top float32, near float32, far float32)

//go:linkname Vfpu_sinf vfpu_sinf
func Vfpu_sinf(x float32) float32

//go:linkname Vfpu_cosf vfpu_cosf
func Vfpu_cosf(x float32) float32

//go:linkname Vfpu_tanf vfpu_tanf
func Vfpu_tanf(x float32) float32

//go:linkname Vfpu_asinf vfpu_asinf
func Vfpu_asinf(x float32) float32

//go:linkname Vfpu_acosf vfpu_acosf
func Vfpu_acosf(x float32) float32

//go:linkname Vfpu_atanf vfpu_atanf
func Vfpu_atanf(x float32) float32

//go:linkname Vfpu_atan2f vfpu_atan2f
func Vfpu_atan2f(x float32, y float32) float32

//go:linkname Vfpu_sinhf vfpu_sinhf
func Vfpu_sinhf(x float32) float32

//go:linkname Vfpu_coshf vfpu_coshf
func Vfpu_coshf(x float32) float32

//go:linkname Vfpu_tanhf vfpu_tanhf
func Vfpu_tanhf(x float32) float32

//go:linkname Vfpu_sincos vfpu_sincos
func Vfpu_sincos(r float32, s unsafe.Pointer, c unsafe.Pointer)

//go:linkname Vfpu_expf vfpu_expf
func Vfpu_expf(x float32) float32

//go:linkname Vfpu_logf vfpu_logf
func Vfpu_logf(x float32) float32

//go:linkname Vfpu_powf vfpu_powf
func Vfpu_powf(x float32, y float32) float32

//go:linkname Vfpu_fmodf vfpu_fmodf
func Vfpu_fmodf(x float32, y float32) float32

//go:linkname Vfpu_ease_in_out vfpu_ease_in_out
func Vfpu_ease_in_out(t float32) float32

//go:linkname Vfpu_normalize_vector vfpu_normalize_vector
func Vfpu_normalize_vector(v unsafe.Pointer)

//go:linkname Vfpu_zero_vector vfpu_zero_vector
func Vfpu_zero_vector(v unsafe.Pointer)

//go:linkname Vfpu_scale_vector vfpu_scale_vector
func Vfpu_scale_vector(vout unsafe.Pointer, vin unsafe.Pointer, scale float32)

//go:linkname Vfpu_add_vector vfpu_add_vector
func Vfpu_add_vector(vout unsafe.Pointer, va unsafe.Pointer, vb unsafe.Pointer)

//go:linkname Vfpu_envmap_matrix vfpu_envmap_matrix
func Vfpu_envmap_matrix(envmat unsafe.Pointer, r float32)

//go:linkname Vfpu_transform_vector vfpu_transform_vector
func Vfpu_transform_vector(m unsafe.Pointer, vin unsafe.Pointer, vout unsafe.Pointer)

//go:linkname Vfpu_sphere_to_cartesian vfpu_sphere_to_cartesian
func Vfpu_sphere_to_cartesian(az float32, ze float32, rad float32, x unsafe.Pointer, y unsafe.Pointer, z unsafe.Pointer)

//go:linkname Vfpu_quaternion_identity vfpu_quaternion_identity
func Vfpu_quaternion_identity(q unsafe.Pointer)

//go:linkname Vfpu_quaternion_copy vfpu_quaternion_copy
func Vfpu_quaternion_copy(dst unsafe.Pointer, src unsafe.Pointer)

//go:linkname Vfpu_quaternion_normalize vfpu_quaternion_normalize
func Vfpu_quaternion_normalize(res unsafe.Pointer)

//go:linkname Vfpu_quaternion_multiply vfpu_quaternion_multiply
func Vfpu_quaternion_multiply(qout unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer)

//go:linkname Vfpu_quaternion_from_euler vfpu_quaternion_from_euler
func Vfpu_quaternion_from_euler(qout unsafe.Pointer, rx float32, ry float32, rz float32)

//go:linkname Vfpu_quaternion_exp vfpu_quaternion_exp
func Vfpu_quaternion_exp(qout unsafe.Pointer, qin unsafe.Pointer)

//go:linkname Vfpu_quaternion_ln vfpu_quaternion_ln
func Vfpu_quaternion_ln(qout unsafe.Pointer, qin unsafe.Pointer)

//go:linkname Vfpu_quaternion_sample_linear vfpu_quaternion_sample_linear
func Vfpu_quaternion_sample_linear(qout unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer, t float32)

//go:linkname Vfpu_quaternion_sample_hermite vfpu_quaternion_sample_hermite
func Vfpu_quaternion_sample_hermite(qout unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer, at unsafe.Pointer, bt unsafe.Pointer, t float32)

//go:linkname Vfpu_quaternion_hermite_tangent vfpu_quaternion_hermite_tangent
func Vfpu_quaternion_hermite_tangent(qout unsafe.Pointer, p1 unsafe.Pointer, p2 unsafe.Pointer, bias float32)

//go:linkname Vfpu_quaternion_to_matrix vfpu_quaternion_to_matrix
func Vfpu_quaternion_to_matrix(q unsafe.Pointer, m unsafe.Pointer)
