// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: isoctrl.h

// Package isoctrl provides direct TinyGo bindings for isoctrl.h.
package isoctrl

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspisoctrlDriver() }

//go:linkname requirePspisoctrlDriver pspsdk_go_require_pspisoctrl_driver
func requirePspisoctrlDriver()

//go:linkname IsoReadUmdFile isoReadUmdFile
func IsoReadUmdFile(offset uint32, buf unsafe.Pointer, size uint32) int32

//go:linkname IsoSetUmdDelay isoSetUmdDelay
func IsoSetUmdDelay(seek int32, speed int32)

//go:linkname IsoGetTitleId isoGetTitleId
func IsoGetTitleId(title_id unsafe.Pointer) int32
