// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psphttp.h

// Package http provides direct TinyGo bindings for psphttp.h.
package http

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceHttpInit sceHttpInit
func SceHttpInit(unknown1 uint32) int32

//go:linkname SceHttpEnd sceHttpEnd
func SceHttpEnd() int32

//go:linkname SceHttpCreateTemplate sceHttpCreateTemplate
func SceHttpCreateTemplate(agent unsafe.Pointer, unknown1 int32, unknown2 int32) int32

//go:linkname SceHttpDeleteTemplate sceHttpDeleteTemplate
func SceHttpDeleteTemplate(templateid int32) int32

//go:linkname SceHttpCreateConnection sceHttpCreateConnection
func SceHttpCreateConnection(templateid int32, host unsafe.Pointer, unknown1 unsafe.Pointer, port uint16, unknown2 int32) int32

//go:linkname SceHttpCreateConnectionWithURL sceHttpCreateConnectionWithURL
func SceHttpCreateConnectionWithURL(templateid int32, url unsafe.Pointer, unknown1 int32) int32

//go:linkname SceHttpDeleteConnection sceHttpDeleteConnection
func SceHttpDeleteConnection(connectionid int32) int32

//go:linkname SceHttpCreateRequest sceHttpCreateRequest
func SceHttpCreateRequest(connectionid int32, method int32, path unsafe.Pointer, contentlength uint64) int32

//go:linkname SceHttpCreateRequestWithURL sceHttpCreateRequestWithURL
func SceHttpCreateRequestWithURL(connectionid int32, method int32, url unsafe.Pointer, contentlength uint64) int32

//go:linkname SceHttpDeleteRequest sceHttpDeleteRequest
func SceHttpDeleteRequest(requestid int32) int32

//go:linkname SceHttpSendRequest sceHttpSendRequest
func SceHttpSendRequest(requestid int32, data unsafe.Pointer, datasize uint32) int32

//go:linkname SceHttpAbortRequest sceHttpAbortRequest
func SceHttpAbortRequest(requestid int32) int32

//go:linkname SceHttpReadData sceHttpReadData
func SceHttpReadData(requestid int32, data unsafe.Pointer, datasize uint32) int32

//go:linkname SceHttpGetContentLength sceHttpGetContentLength
func SceHttpGetContentLength(requestid int32, contentlength unsafe.Pointer) int32

//go:linkname SceHttpGetStatusCode sceHttpGetStatusCode
func SceHttpGetStatusCode(requestid int32, statuscode unsafe.Pointer) int32

//go:linkname SceHttpSetResolveTimeOut sceHttpSetResolveTimeOut
func SceHttpSetResolveTimeOut(id int32, timeout uint32) int32

//go:linkname SceHttpSetResolveRetry sceHttpSetResolveRetry
func SceHttpSetResolveRetry(id int32, count int32) int32

//go:linkname SceHttpSetConnectTimeOut sceHttpSetConnectTimeOut
func SceHttpSetConnectTimeOut(id int32, timeout uint32) int32

//go:linkname SceHttpSetSendTimeOut sceHttpSetSendTimeOut
func SceHttpSetSendTimeOut(id int32, timeout uint32) int32

//go:linkname SceHttpSetRecvTimeOut sceHttpSetRecvTimeOut
func SceHttpSetRecvTimeOut(id int32, timeout uint32) int32

//go:linkname SceHttpEnableKeepAlive sceHttpEnableKeepAlive
func SceHttpEnableKeepAlive(id int32) int32

//go:linkname SceHttpDisableKeepAlive sceHttpDisableKeepAlive
func SceHttpDisableKeepAlive(id int32) int32

//go:linkname SceHttpEnableRedirect sceHttpEnableRedirect
func SceHttpEnableRedirect(id int32) int32

//go:linkname SceHttpDisableRedirect sceHttpDisableRedirect
func SceHttpDisableRedirect(id int32) int32

//go:linkname SceHttpEnableCookie sceHttpEnableCookie
func SceHttpEnableCookie(id int32) int32

//go:linkname SceHttpDisableCookie sceHttpDisableCookie
func SceHttpDisableCookie(id int32) int32

//go:linkname SceHttpSaveSystemCookie sceHttpSaveSystemCookie
func SceHttpSaveSystemCookie() int32

//go:linkname SceHttpLoadSystemCookie sceHttpLoadSystemCookie
func SceHttpLoadSystemCookie() int32

//go:linkname SceHttpAddExtraHeader sceHttpAddExtraHeader
func SceHttpAddExtraHeader(id int32, name unsafe.Pointer, value unsafe.Pointer, unknown1 int32) int32

//go:linkname SceHttpDeleteHeader sceHttpDeleteHeader
func SceHttpDeleteHeader(id int32, name unsafe.Pointer) int32

//go:linkname SceHttpsInit sceHttpsInit
func SceHttpsInit(unknown1 int32, unknown2 int32, unknown3 int32, unknown4 int32) int32

//go:linkname SceHttpsEnd sceHttpsEnd
func SceHttpsEnd() int32

//go:linkname SceHttpsLoadDefaultCert sceHttpsLoadDefaultCert
func SceHttpsLoadDefaultCert(unknown1 int32, unknown2 int32) int32

//go:linkname SceHttpDisableAuth sceHttpDisableAuth
func SceHttpDisableAuth(id int32) int32

//go:linkname SceHttpDisableCache sceHttpDisableCache
func SceHttpDisableCache(id int32) int32

//go:linkname SceHttpEnableAuth sceHttpEnableAuth
func SceHttpEnableAuth(id int32) int32

//go:linkname SceHttpEnableCache sceHttpEnableCache
func SceHttpEnableCache(id int32) int32

//go:linkname SceHttpEndCache sceHttpEndCache
func SceHttpEndCache() int32

//go:linkname SceHttpGetAllHeader sceHttpGetAllHeader
func SceHttpGetAllHeader(request int32, header unsafe.Pointer, header_size unsafe.Pointer) int32

//go:linkname SceHttpGetNetworkErrno sceHttpGetNetworkErrno
func SceHttpGetNetworkErrno(request int32, err_num unsafe.Pointer) int32

//go:linkname SceHttpGetProxy sceHttpGetProxy
func SceHttpGetProxy(id int32, activate_flag unsafe.Pointer, mode unsafe.Pointer, proxy_host unsafe.Pointer, len uint32, proxy_port unsafe.Pointer) int32

//go:linkname SceHttpInitCache sceHttpInitCache
func SceHttpInitCache(max_size uint32) int32

//go:linkname SceHttpSetAuthInfoCB sceHttpSetAuthInfoCB
func SceHttpSetAuthInfoCB(id int32, cbfunc unsafe.Pointer) int32

//go:linkname SceHttpSetProxy sceHttpSetProxy
func SceHttpSetProxy(id int32, activate_flag int32, mode int32, new_proxy_host unsafe.Pointer, new_proxy_port uint16) int32

//go:linkname SceHttpSetResHeaderMaxSize sceHttpSetResHeaderMaxSize
func SceHttpSetResHeaderMaxSize(id int32, header_size uint32) int32

//go:linkname SceHttpSetMallocFunction sceHttpSetMallocFunction
func SceHttpSetMallocFunction(malloc_func unsafe.Pointer, free_func unsafe.Pointer, realloc_func unsafe.Pointer) int32
