// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspaudiolib.h

// Package audiolib provides direct TinyGo bindings for pspaudiolib.h.
package audiolib

import "unsafe"

var _ unsafe.Pointer

//go:linkname PspAudioInit pspAudioInit
func PspAudioInit() int32

//go:linkname PspAudioEndPre pspAudioEndPre
func PspAudioEndPre()

//go:linkname PspAudioEnd pspAudioEnd
func PspAudioEnd()

//go:linkname PspAudioSetVolume pspAudioSetVolume
func PspAudioSetVolume(channel int32, left int32, right int32)

//go:linkname PspAudioGetVolume pspAudioGetVolume
func PspAudioGetVolume(channel int32, left unsafe.Pointer, right unsafe.Pointer)

//go:linkname PspAudioSetChannelCallback pspAudioSetChannelCallback
func PspAudioSetChannelCallback(channel int32, callback unsafe.Pointer, pdata unsafe.Pointer)

//go:linkname PspAudioGetChannelCallback pspAudioGetChannelCallback
func PspAudioGetChannelCallback(channel int32, callback unsafe.Pointer, pdata unsafe.Pointer)

//go:linkname PspAudioOutBlocking pspAudioOutBlocking
func PspAudioOutBlocking(channel uint32, vol1 uint32, vol2 uint32, buf unsafe.Pointer) int32
