// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspintrman.h

// Package intrman provides direct TinyGo bindings for pspintrman.h.
package intrman

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_GPIO_INT        = 4
	PSP_ATA_INT         = 5
	PSP_UMD_INT         = 6
	PSP_MSCM0_INT       = 7
	PSP_WLAN_INT        = 8
	PSP_AUDIO_INT       = 10
	PSP_I2C_INT         = 12
	PSP_SIRCS_INT       = 14
	PSP_SYSTIMER0_INT   = 15
	PSP_SYSTIMER1_INT   = 16
	PSP_SYSTIMER2_INT   = 17
	PSP_SYSTIMER3_INT   = 18
	PSP_THREAD0_INT     = 19
	PSP_NAND_INT        = 20
	PSP_DMACPLUS_INT    = 21
	PSP_DMA0_INT        = 22
	PSP_DMA1_INT        = 23
	PSP_MEMLMD_INT      = 24
	PSP_GE_INT          = 25
	PSP_VBLANK_INT      = 30
	PSP_MECODEC_INT     = 31
	PSP_HPREMOTE_INT    = 36
	PSP_MSCM1_INT       = 60
	PSP_MSCM2_INT       = 61
	PSP_THREAD1_INT     = 65
	PSP_INTERRUPT_INT   = 66
	PSP_GPIO_SUBINT     = 4
	PSP_ATA_SUBINT      = 5
	PSP_UMD_SUBINT      = 6
	PSP_DMACPLUS_SUBINT = 21
	PSP_GE_SUBINT       = 25
	PSP_DISPLAY_SUBINT  = 30
)

//go:linkname SceKernelCpuSuspendIntr sceKernelCpuSuspendIntr
func SceKernelCpuSuspendIntr() uint32

//go:linkname SceKernelCpuResumeIntr sceKernelCpuResumeIntr
func SceKernelCpuResumeIntr(flags uint32)

//go:linkname SceKernelCpuResumeIntrWithSync sceKernelCpuResumeIntrWithSync
func SceKernelCpuResumeIntrWithSync(flags uint32)

//go:linkname SceKernelIsCpuIntrSuspended sceKernelIsCpuIntrSuspended
func SceKernelIsCpuIntrSuspended(flags uint32) int32

//go:linkname SceKernelIsCpuIntrEnable sceKernelIsCpuIntrEnable
func SceKernelIsCpuIntrEnable() int32

//go:linkname SceKernelRegisterSubIntrHandler sceKernelRegisterSubIntrHandler
func SceKernelRegisterSubIntrHandler(intno int32, no int32, handler unsafe.Pointer, arg unsafe.Pointer) int32

//go:linkname SceKernelReleaseSubIntrHandler sceKernelReleaseSubIntrHandler
func SceKernelReleaseSubIntrHandler(intno int32, no int32) int32

//go:linkname SceKernelEnableSubIntr sceKernelEnableSubIntr
func SceKernelEnableSubIntr(intno int32, no int32) int32

//go:linkname SceKernelDisableSubIntr sceKernelDisableSubIntr
func SceKernelDisableSubIntr(intno int32, no int32) int32

//go:linkname QueryIntrHandlerInfo QueryIntrHandlerInfo
func QueryIntrHandlerInfo(intr_code int32, sub_intr_code int32, data unsafe.Pointer) int32
