// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: mini2d.h

// Package mini2d provides direct TinyGo bindings for mini2d.h.
package mini2d

import "unsafe"

var _ unsafe.Pointer

func init() { requireMini2d() }

//go:linkname requireMini2d pspsdk_go_require_mini2d
func requireMini2d()

//go:linkname LoadImage loadImage
func LoadImage(filename unsafe.Pointer, offset uint32) unsafe.Pointer

//go:linkname BlitImageToImage blitImageToImage
func BlitImageToImage(sx int32, sy int32, width int32, height int32, source unsafe.Pointer, dx int32, dy int32, destination unsafe.Pointer)

//go:linkname BlitImageToScreen blitImageToScreen
func BlitImageToScreen(sx int32, sy int32, width int32, height int32, source unsafe.Pointer, dx int32, dy int32)

//go:linkname BlitAlphaImageToImage blitAlphaImageToImage
func BlitAlphaImageToImage(sx int32, sy int32, width int32, height int32, source unsafe.Pointer, dx int32, dy int32, destination unsafe.Pointer)

//go:linkname BlitAlphaImageToScreen blitAlphaImageToScreen
func BlitAlphaImageToScreen(sx int32, sy int32, width int32, height int32, source unsafe.Pointer, dx int32, dy int32)

//go:linkname CreateImage createImage
func CreateImage(width int32, height int32) unsafe.Pointer

//go:linkname FreeImage freeImage
func FreeImage(image unsafe.Pointer)

//go:linkname ClearImage clearImage
func ClearImage(color uint32, image unsafe.Pointer)

//go:linkname ClearScreen clearScreen
func ClearScreen(color uint32)

//go:linkname FillImageRect fillImageRect
func FillImageRect(color uint32, x0 int32, y0 int32, width int32, height int32, image unsafe.Pointer)

//go:linkname FillScreenRect fillScreenRect
func FillScreenRect(color uint32, x0 int32, y0 int32, width int32, height int32)

//go:linkname PutPixelScreen putPixelScreen
func PutPixelScreen(color uint32, x int32, y int32)

//go:linkname PutPixelImage putPixelImage
func PutPixelImage(color uint32, x int32, y int32, image unsafe.Pointer)

//go:linkname GetPixelScreen getPixelScreen
func GetPixelScreen(x int32, y int32) int32

//go:linkname GetPixelImage getPixelImage
func GetPixelImage(x int32, y int32, image unsafe.Pointer) int32

//go:linkname PrintTextScreen printTextScreen
func PrintTextScreen(x int32, y int32, text unsafe.Pointer, color uint32)

//go:linkname PrintTextImage printTextImage
func PrintTextImage(x int32, y int32, text unsafe.Pointer, color uint32, image unsafe.Pointer)

//go:linkname SaveImage saveImage
func SaveImage(filename unsafe.Pointer, data unsafe.Pointer, width int32, height int32, lineSize int32, saveAlpha int32)

//go:linkname FlipScreen flipScreen
func FlipScreen()

//go:linkname InitGraphics initGraphics
func InitGraphics()

//go:linkname EnableGraphics enableGraphics
func EnableGraphics()

//go:linkname DisableGraphics disableGraphics
func DisableGraphics()

//go:linkname DrawLineScreen drawLineScreen
func DrawLineScreen(x0 int32, y0 int32, x1 int32, y1 int32, color uint32)

//go:linkname DrawLineImage drawLineImage
func DrawLineImage(x0 int32, y0 int32, x1 int32, y1 int32, color uint32, image unsafe.Pointer)

//go:linkname GetVramDrawBuffer getVramDrawBuffer
func GetVramDrawBuffer() unsafe.Pointer

//go:linkname GetVramDisplayBuffer getVramDisplayBuffer
func GetVramDisplayBuffer() unsafe.Pointer

//go:linkname GuStart guStart
func GuStart()
