// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspstdio_kernel.h

// Package stdio_kernel provides direct TinyGo bindings for pspstdio_kernel.h.
package stdio_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

const (
	FIO_S_IFMT      = 61440
	FIO_S_IFLNK     = 16384
	FIO_S_IFDIR     = 4096
	FIO_S_IFREG     = 8192
	FIO_S_ISUID     = 2048
	FIO_S_ISGID     = 1024
	FIO_S_ISVTX     = 512
	FIO_S_IRWXU     = 448
	FIO_S_IRUSR     = 256
	FIO_S_IWUSR     = 128
	FIO_S_IXUSR     = 64
	FIO_S_IRWXG     = 56
	FIO_S_IRGRP     = 32
	FIO_S_IWGRP     = 16
	FIO_S_IXGRP     = 8
	FIO_S_IRWXO     = 7
	FIO_S_IROTH     = 4
	FIO_S_IWOTH     = 2
	FIO_S_IXOTH     = 1
	FIO_SO_IFMT     = 56
	FIO_SO_IFLNK    = 8
	FIO_SO_IFDIR    = 16
	FIO_SO_IFREG    = 32
	FIO_SO_IROTH    = 4
	FIO_SO_IWOTH    = 2
	FIO_SO_IXOTH    = 1
	IOASSIGN_RDWR   = 0
	IOASSIGN_RDONLY = 1
)

//go:linkname SceKernelStdoutReopen sceKernelStdoutReopen
func SceKernelStdoutReopen(file unsafe.Pointer, flags int32, mode int32) int32

//go:linkname SceKernelStderrReopen sceKernelStderrReopen
func SceKernelStderrReopen(file unsafe.Pointer, flags int32, mode int32) int32

// Unsupported C declarations:
// - fdprintf: variadic
