// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspaudio.h

// Package audio provides direct TinyGo bindings for pspaudio.h.
package audio

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_AUDIO_FORMAT_STEREO = 0
	PSP_AUDIO_FORMAT_MONO   = 16
)

//go:linkname SceAudioChReserve sceAudioChReserve
func SceAudioChReserve(channel int32, samplecount int32, format int32) int32

//go:linkname SceAudioChRelease sceAudioChRelease
func SceAudioChRelease(channel int32) int32

//go:linkname SceAudioOutput sceAudioOutput
func SceAudioOutput(channel int32, vol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioOutputBlocking sceAudioOutputBlocking
func SceAudioOutputBlocking(channel int32, vol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioOutputPanned sceAudioOutputPanned
func SceAudioOutputPanned(channel int32, leftvol int32, rightvol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioOutputPannedBlocking sceAudioOutputPannedBlocking
func SceAudioOutputPannedBlocking(channel int32, leftvol int32, rightvol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioGetChannelRestLen sceAudioGetChannelRestLen
func SceAudioGetChannelRestLen(channel int32) int32

//go:linkname SceAudioGetChannelRestLength sceAudioGetChannelRestLength
func SceAudioGetChannelRestLength(channel int32) int32

//go:linkname SceAudioSetChannelDataLen sceAudioSetChannelDataLen
func SceAudioSetChannelDataLen(channel int32, samplecount int32) int32

//go:linkname SceAudioChangeChannelConfig sceAudioChangeChannelConfig
func SceAudioChangeChannelConfig(channel int32, format int32) int32

//go:linkname SceAudioChangeChannelVolume sceAudioChangeChannelVolume
func SceAudioChangeChannelVolume(channel int32, leftvol int32, rightvol int32) int32

//go:linkname SceAudioOutput2Reserve sceAudioOutput2Reserve
func SceAudioOutput2Reserve(samplecount int32) int32

//go:linkname SceAudioOutput2Release sceAudioOutput2Release
func SceAudioOutput2Release() int32

//go:linkname SceAudioOutput2ChangeLength sceAudioOutput2ChangeLength
func SceAudioOutput2ChangeLength(samplecount int32) int32

//go:linkname SceAudioOutput2OutputBlocking sceAudioOutput2OutputBlocking
func SceAudioOutput2OutputBlocking(vol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioOutput2GetRestSample sceAudioOutput2GetRestSample
func SceAudioOutput2GetRestSample() int32

//go:linkname SceAudioSRCChReserve sceAudioSRCChReserve
func SceAudioSRCChReserve(samplecount int32, freq int32, channels int32) int32

//go:linkname SceAudioSRCChRelease sceAudioSRCChRelease
func SceAudioSRCChRelease() int32

//go:linkname SceAudioSRCOutputBlocking sceAudioSRCOutputBlocking
func SceAudioSRCOutputBlocking(vol int32, buf unsafe.Pointer) int32

//go:linkname SceAudioInputInit sceAudioInputInit
func SceAudioInputInit(unknown1 int32, gain int32, unknown2 int32) int32

//go:linkname SceAudioInputInitEx sceAudioInputInitEx
func SceAudioInputInitEx(params unsafe.Pointer) int32

//go:linkname SceAudioInputBlocking sceAudioInputBlocking
func SceAudioInputBlocking(samplecount int32, freq int32, buf unsafe.Pointer) int32

//go:linkname SceAudioInput sceAudioInput
func SceAudioInput(samplecount int32, freq int32, buf unsafe.Pointer) int32

//go:linkname SceAudioGetInputLength sceAudioGetInputLength
func SceAudioGetInputLength() int32

//go:linkname SceAudioWaitInputEnd sceAudioWaitInputEnd
func SceAudioWaitInputEnd() int32

//go:linkname SceAudioPollInputEnd sceAudioPollInputEnd
func SceAudioPollInputEnd() int32
