// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspmscm.h

// Package mscm provides direct TinyGo bindings for pspmscm.h.
package mscm

import "unsafe"

var _ unsafe.Pointer

//go:linkname MScmIsMediumInserted MScmIsMediumInserted
func MScmIsMediumInserted() int32

//go:linkname MScmRegisterMSInsertEjectCallback MScmRegisterMSInsertEjectCallback
func MScmRegisterMSInsertEjectCallback(cbid int32) int32

//go:linkname MScmUnregisterMSInsertEjectCallback MScmUnregisterMSInsertEjectCallback
func MScmUnregisterMSInsertEjectCallback(cbid int32) int32
