// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspssl.h

// Package ssl provides direct TinyGo bindings for pspssl.h.
package ssl

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSslInit sceSslInit
func SceSslInit(unknown1 int32) int32

//go:linkname SceSslEnd sceSslEnd
func SceSslEnd() int32

//go:linkname SceSslGetUsedMemoryMax sceSslGetUsedMemoryMax
func SceSslGetUsedMemoryMax(memory unsafe.Pointer) int32

//go:linkname SceSslGetUsedMemoryCurrent sceSslGetUsedMemoryCurrent
func SceSslGetUsedMemoryCurrent(memory unsafe.Pointer) int32
