// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_msgdialog.h

// Package utility_msgdialog provides direct TinyGo bindings for psputility_msgdialog.h.
package utility_msgdialog

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_UTILITY_MSGDIALOG_MODE_ERROR           = 0
	PSP_UTILITY_MSGDIALOG_OPTION_ERROR         = 0
	PSP_UTILITY_MSGDIALOG_OPTION_TEXT          = 1
	PSP_UTILITY_MSGDIALOG_OPTION_YESNO_BUTTONS = 16
	PSP_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO    = 256
	PSP_UTILITY_MSGDIALOG_RESULT_UNKNOWN1      = 0
)

//go:linkname SceUtilityMsgDialogInitStart sceUtilityMsgDialogInitStart
func SceUtilityMsgDialogInitStart(params unsafe.Pointer) int32

//go:linkname SceUtilityMsgDialogShutdownStart sceUtilityMsgDialogShutdownStart
func SceUtilityMsgDialogShutdownStart()

//go:linkname SceUtilityMsgDialogGetStatus sceUtilityMsgDialogGetStatus
func SceUtilityMsgDialogGetStatus() int32

//go:linkname SceUtilityMsgDialogUpdate sceUtilityMsgDialogUpdate
func SceUtilityMsgDialogUpdate(n int32)

//go:linkname SceUtilityMsgDialogAbort sceUtilityMsgDialogAbort
func SceUtilityMsgDialogAbort() int32
