// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psptypes.h

// Package types provides direct TinyGo bindings for psptypes.h.
package types

import "unsafe"

var _ unsafe.Pointer

//go:linkname _lb _lb
func _lb(addr uint32) int32

//go:linkname _lh _lh
func _lh(addr uint32) int32

//go:linkname _lw _lw
func _lw(addr uint32) int32

//go:linkname _ld _ld
func _ld(addr uint32) uint64

//go:linkname _sb _sb
func _sb(val uint8, addr uint32)

//go:linkname _sh _sh
func _sh(val uint16, addr uint32)

//go:linkname _sw _sw
func _sw(val uint32, addr uint32)

//go:linkname _sd _sd
func _sd(val uint64, addr uint32)
