// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspnet_resolver.h

// Package net_resolver provides direct TinyGo bindings for pspnet_resolver.h.
package net_resolver

import "unsafe"

var _ unsafe.Pointer

const (
	SCHED_OTHER               = 0
	SCHED_MIN                 = 0
	SCHED_MAX                 = 2
	PTHREAD_MUTEX_TIMED_NP    = 0
	PTHREAD_MUTEX_ADAPTIVE_NP = 0
	PTHREAD_MUTEX_NORMAL      = 0
	PTHREAD_MUTEX_RECURSIVE   = 1
	PTHREAD_MUTEX_ERRORCHECK  = 2
	PTHREAD_MUTEX_DEFAULT     = 0
)

//go:linkname SceNetResolverInit sceNetResolverInit
func SceNetResolverInit() int32

//go:linkname SceNetResolverCreate sceNetResolverCreate
func SceNetResolverCreate(rid unsafe.Pointer, buf unsafe.Pointer, buflen uint32) int32

//go:linkname SceNetResolverDelete sceNetResolverDelete
func SceNetResolverDelete(rid int32) int32

//go:linkname SceNetResolverStartNtoA sceNetResolverStartNtoA
func SceNetResolverStartNtoA(rid int32, hostname unsafe.Pointer, addr unsafe.Pointer, timeout uint32, retry int32) int32

//go:linkname SceNetResolverStartAtoN sceNetResolverStartAtoN
func SceNetResolverStartAtoN(rid int32, addr unsafe.Pointer, hostname unsafe.Pointer, hostname_len uint32, timeout uint32, retry int32) int32

//go:linkname SceNetResolverStop sceNetResolverStop
func SceNetResolverStop(rid int32) int32

//go:linkname SceNetResolverTerm sceNetResolverTerm
func SceNetResolverTerm() int32
