// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: colordebugger.h

// Package colordebugger provides direct TinyGo bindings for colordebugger.h.
package colordebugger

import "unsafe"

var _ unsafe.Pointer

func init() { requireColordebugger() }

//go:linkname requireColordebugger pspsdk_go_require_colordebugger
func requireColordebugger()

//go:linkname ColorDebug colorDebug
func ColorDebug(color uint32)

//go:linkname SetScreenHandler setScreenHandler
func SetScreenHandler(handler unsafe.Pointer)

//go:linkname DoBreakpoint doBreakpoint
func DoBreakpoint()

//go:linkname SetBreakpoint setBreakpoint
func SetBreakpoint(addr uint32)
