// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: netdb.h

// Package netdb provides direct TinyGo bindings for netdb.h.
package netdb

import "unsafe"

var _ unsafe.Pointer

func init() { requireCglue() }

//go:linkname requireCglue pspsdk_go_require_cglue
func requireCglue()

//go:linkname Gethostbyaddr gethostbyaddr
func Gethostbyaddr(addr unsafe.Pointer, len int32, typeValue int32) unsafe.Pointer

//go:linkname Gethostbyname gethostbyname
func Gethostbyname(name unsafe.Pointer) unsafe.Pointer
