// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspchnnlsv.h

// Package chnnlsv provides direct TinyGo bindings for pspchnnlsv.h.
package chnnlsv

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSdSetIndex sceSdSetIndex
func SceSdSetIndex(ctx unsafe.Pointer, mode int32) int32

//go:linkname SceSdRemoveValue sceSdRemoveValue
func SceSdRemoveValue(ctx unsafe.Pointer, data unsafe.Pointer, len int32) int32

//go:linkname SceSdGetLastIndex sceSdGetLastIndex
func SceSdGetLastIndex(ctx unsafe.Pointer, hash unsafe.Pointer, cryptkey unsafe.Pointer) int32

//go:linkname SceSdCreateList sceSdCreateList
func SceSdCreateList(ctx unsafe.Pointer, mode1 int32, mode2 int32, hashkey unsafe.Pointer, cipherkey unsafe.Pointer) int32

//go:linkname SceSdSetMember sceSdSetMember
func SceSdSetMember(ctx unsafe.Pointer, data unsafe.Pointer, len int32) int32

//go:linkname SceSdCleanList sceSdCleanList
func SceSdCleanList(ctx unsafe.Pointer) int32
