// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspiofilemgr_devctl.h

// Package iofilemgr_devctl provides direct TinyGo bindings for pspiofilemgr_devctl.h.
package iofilemgr_devctl

import "unsafe"

var _ unsafe.Pointer
