// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psploadexec_kernel.h

// Package loadexec_kernel provides direct TinyGo bindings for psploadexec_kernel.h.
package loadexec_kernel

import "unsafe"

var _ unsafe.Pointer

func init() { requirePspkernel() }

//go:linkname requirePspkernel pspsdk_go_require_pspkernel
func requirePspkernel()

//go:linkname SceKernelExitVSHVSH sceKernelExitVSHVSH
func SceKernelExitVSHVSH(param unsafe.Pointer) int32

//go:linkname SceKernelLoadExecVSHDisc sceKernelLoadExecVSHDisc
func SceKernelLoadExecVSHDisc(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SceKernelLoadExecVSHDiscUpdater sceKernelLoadExecVSHDiscUpdater
func SceKernelLoadExecVSHDiscUpdater(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SceKernelLoadExecVSHMs1 sceKernelLoadExecVSHMs1
func SceKernelLoadExecVSHMs1(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SceKernelLoadExecVSHMs2 sceKernelLoadExecVSHMs2
func SceKernelLoadExecVSHMs2(file unsafe.Pointer, param unsafe.Pointer) int32

//go:linkname SceKernelLoadExecVSHMs3 sceKernelLoadExecVSHMs3
func SceKernelLoadExecVSHMs3(file unsafe.Pointer, param unsafe.Pointer) int32
