// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspopenpsid.h

// Package openpsid provides direct TinyGo bindings for pspopenpsid.h.
package openpsid

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceOpenPSIDGetOpenPSID sceOpenPSIDGetOpenPSID
func SceOpenPSIDGetOpenPSID(openpsid unsafe.Pointer) int32
