// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspatrac3.h

// Package atrac3 provides direct TinyGo bindings for pspatrac3.h.
package atrac3

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceAtracGetAtracID sceAtracGetAtracID
func SceAtracGetAtracID(uiCodecType uint32) int32

//go:linkname SceAtracSetDataAndGetID sceAtracSetDataAndGetID
func SceAtracSetDataAndGetID(buf unsafe.Pointer, bufsize uint32) int32

//go:linkname SceAtracDecodeData sceAtracDecodeData
func SceAtracDecodeData(atracID int32, outSamples unsafe.Pointer, outN unsafe.Pointer, outEnd unsafe.Pointer, outRemainFrame unsafe.Pointer) int32

//go:linkname SceAtracGetRemainFrame sceAtracGetRemainFrame
func SceAtracGetRemainFrame(atracID int32, outRemainFrame unsafe.Pointer) int32

//go:linkname SceAtracGetStreamDataInfo sceAtracGetStreamDataInfo
func SceAtracGetStreamDataInfo(atracID int32, writePointer unsafe.Pointer, availableBytes unsafe.Pointer, readOffset unsafe.Pointer) int32

//go:linkname SceAtracAddStreamData sceAtracAddStreamData
func SceAtracAddStreamData(atracID int32, bytesToAdd uint32) int32

//go:linkname SceAtracGetBitrate sceAtracGetBitrate
func SceAtracGetBitrate(atracID int32, outBitrate unsafe.Pointer) int32

//go:linkname SceAtracSetLoopNum sceAtracSetLoopNum
func SceAtracSetLoopNum(atracID int32, nloops int32) int32

//go:linkname SceAtracReleaseAtracID sceAtracReleaseAtracID
func SceAtracReleaseAtracID(atracID int32) int32

//go:linkname SceAtracGetNextSample sceAtracGetNextSample
func SceAtracGetNextSample(atracID int32, outN unsafe.Pointer) int32

//go:linkname SceAtracGetMaxSample sceAtracGetMaxSample
func SceAtracGetMaxSample(atracID int32, outMax unsafe.Pointer) int32

//go:linkname SceAtracGetBufferInfoForReseting sceAtracGetBufferInfoForReseting
func SceAtracGetBufferInfoForReseting(atracID int32, uiSample uint32, pBufferInfo unsafe.Pointer) int32

//go:linkname SceAtracGetChannel sceAtracGetChannel
func SceAtracGetChannel(atracID int32, puiChannel unsafe.Pointer) int32

//go:linkname SceAtracGetInternalErrorInfo sceAtracGetInternalErrorInfo
func SceAtracGetInternalErrorInfo(atracID int32, piResult unsafe.Pointer) int32

//go:linkname SceAtracGetLoopStatus sceAtracGetLoopStatus
func SceAtracGetLoopStatus(atracID int32, piLoopNum unsafe.Pointer, puiLoopStatus unsafe.Pointer) int32

//go:linkname SceAtracGetNextDecodePosition sceAtracGetNextDecodePosition
func SceAtracGetNextDecodePosition(atracID int32, puiSamplePosition unsafe.Pointer) int32

//go:linkname SceAtracGetSecondBufferInfo sceAtracGetSecondBufferInfo
func SceAtracGetSecondBufferInfo(atracID int32, puiPosition unsafe.Pointer, puiDataByte unsafe.Pointer) int32

//go:linkname SceAtracGetSoundSample sceAtracGetSoundSample
func SceAtracGetSoundSample(atracID int32, piEndSample unsafe.Pointer, piLoopStartSample unsafe.Pointer, piLoopEndSample unsafe.Pointer) int32

//go:linkname SceAtracResetPlayPosition sceAtracResetPlayPosition
func SceAtracResetPlayPosition(atracID int32, uiSample uint32, uiWriteByteFirstBuf uint32, uiWriteByteSecondBuf uint32) int32

//go:linkname SceAtracSetData sceAtracSetData
func SceAtracSetData(atracID int32, pucBufferAddr unsafe.Pointer, uiBufferByte uint32) int32

//go:linkname SceAtracSetHalfwayBuffer sceAtracSetHalfwayBuffer
func SceAtracSetHalfwayBuffer(atracID int32, pucBufferAddr unsafe.Pointer, uiReadByte uint32, uiBufferByte uint32) int32

//go:linkname SceAtracSetHalfwayBufferAndGetID sceAtracSetHalfwayBufferAndGetID
func SceAtracSetHalfwayBufferAndGetID(pucBufferAddr unsafe.Pointer, uiReadByte uint32, uiBufferByte uint32) int32

//go:linkname SceAtracSetSecondBuffer sceAtracSetSecondBuffer
func SceAtracSetSecondBuffer(atracID int32, pucSecondBufferAddr unsafe.Pointer, uiSecondBufferByte uint32) int32
