// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsysmem.h

// Package sysmem provides direct TinyGo bindings for pspsysmem.h.
package sysmem

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_SMEM_Low = 0
)

//go:linkname SceKernelAllocPartitionMemory sceKernelAllocPartitionMemory
func SceKernelAllocPartitionMemory(partitionid int32, name unsafe.Pointer, typeValue int32, size uint32, addr unsafe.Pointer) int32

//go:linkname SceKernelFreePartitionMemory sceKernelFreePartitionMemory
func SceKernelFreePartitionMemory(blockid int32) int32

//go:linkname SceKernelGetBlockHeadAddr sceKernelGetBlockHeadAddr
func SceKernelGetBlockHeadAddr(blockid int32) unsafe.Pointer

//go:linkname SceKernelTotalFreeMemSize sceKernelTotalFreeMemSize
func SceKernelTotalFreeMemSize() int32

//go:linkname SceKernelMaxFreeMemSize sceKernelMaxFreeMemSize
func SceKernelMaxFreeMemSize() int32

//go:linkname SceKernelDevkitVersion sceKernelDevkitVersion
func SceKernelDevkitVersion() int32

//go:linkname SceKernelSetCompiledSdkVersion sceKernelSetCompiledSdkVersion
func SceKernelSetCompiledSdkVersion(version int32) int32

//go:linkname SceKernelGetCompiledSdkVersion sceKernelGetCompiledSdkVersion
func SceKernelGetCompiledSdkVersion() int32
