// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: libpsardumper.h

// Package libpsardumper provides direct TinyGo bindings for libpsardumper.h.
package libpsardumper

import "unsafe"

var _ unsafe.Pointer

func init() { requirePsppsar() }

//go:linkname requirePsppsar pspsdk_go_require_psppsar
func requirePsppsar()

//go:linkname PspPSARInit pspPSARInit
func PspPSARInit(dataPSAR unsafe.Pointer, dataOut unsafe.Pointer, dataOut2 unsafe.Pointer) int32

//go:linkname PspPSARGetNextFile pspPSARGetNextFile
func PspPSARGetNextFile(dataPSAR unsafe.Pointer, cbFile int32, dataOut unsafe.Pointer, dataOut2 unsafe.Pointer, name unsafe.Pointer, retSize unsafe.Pointer, retPos unsafe.Pointer, signcheck unsafe.Pointer) int32

//go:linkname PspPSARSetBufferPosition pspPSARSetBufferPosition
func PspPSARSetBufferPosition(position int32) int32
