// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspvideocodec.h

// Package videocodec provides direct TinyGo bindings for pspvideocodec.h.
package videocodec

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceVideocodecOpen sceVideocodecOpen
func SceVideocodecOpen(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceVideocodecGetEDRAM sceVideocodecGetEDRAM
func SceVideocodecGetEDRAM(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceVideocodecInit sceVideocodecInit
func SceVideocodecInit(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceVideocodecDecode sceVideocodecDecode
func SceVideocodecDecode(Buffer unsafe.Pointer, Type int32) int32

//go:linkname SceVideocodecReleaseEDRAM sceVideocodecReleaseEDRAM
func SceVideocodecReleaseEDRAM(Buffer unsafe.Pointer) int32
