// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: cfwmacros.h

// Package cfwmacros provides direct TinyGo bindings for cfwmacros.h.
package cfwmacros

import "unsafe"

var _ unsafe.Pointer
