// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspreg.h

// Package reg provides direct TinyGo bindings for pspreg.h.
package reg

import "unsafe"

var _ unsafe.Pointer

const (
	REG_TYPE_DIR = 1
	REG_TYPE_INT = 2
	REG_TYPE_STR = 3
	REG_TYPE_BIN = 4
)

//go:linkname SceRegOpenRegistry sceRegOpenRegistry
func SceRegOpenRegistry(reg unsafe.Pointer, mode int32, h unsafe.Pointer) int32

//go:linkname SceRegFlushRegistry sceRegFlushRegistry
func SceRegFlushRegistry(h uint32) int32

//go:linkname SceRegCloseRegistry sceRegCloseRegistry
func SceRegCloseRegistry(h uint32) int32

//go:linkname SceRegOpenCategory sceRegOpenCategory
func SceRegOpenCategory(h uint32, name unsafe.Pointer, mode int32, hd unsafe.Pointer) int32

//go:linkname SceRegRemoveCategory sceRegRemoveCategory
func SceRegRemoveCategory(h uint32, name unsafe.Pointer) int32

//go:linkname SceRegCloseCategory sceRegCloseCategory
func SceRegCloseCategory(hd uint32) int32

//go:linkname SceRegFlushCategory sceRegFlushCategory
func SceRegFlushCategory(hd uint32) int32

//go:linkname SceRegGetKeyInfo sceRegGetKeyInfo
func SceRegGetKeyInfo(hd uint32, name unsafe.Pointer, hk unsafe.Pointer, typeValue unsafe.Pointer, size unsafe.Pointer) int32

//go:linkname SceRegGetKeyInfoByName sceRegGetKeyInfoByName
func SceRegGetKeyInfoByName(hd uint32, name unsafe.Pointer, typeValue unsafe.Pointer, size unsafe.Pointer) int32

//go:linkname SceRegGetKeyValue sceRegGetKeyValue
func SceRegGetKeyValue(hd uint32, hk uint32, buf unsafe.Pointer, size uint32) int32

//go:linkname SceRegGetKeyValueByName sceRegGetKeyValueByName
func SceRegGetKeyValueByName(hd uint32, name unsafe.Pointer, buf unsafe.Pointer, size uint32) int32

//go:linkname SceRegSetKeyValue sceRegSetKeyValue
func SceRegSetKeyValue(hd uint32, name unsafe.Pointer, buf unsafe.Pointer, size uint32) int32

//go:linkname SceRegGetKeysNum sceRegGetKeysNum
func SceRegGetKeysNum(hd uint32, num unsafe.Pointer) int32

//go:linkname SceRegGetKeys sceRegGetKeys
func SceRegGetKeys(hd uint32, buf unsafe.Pointer, num int32) int32

//go:linkname SceRegCreateKey sceRegCreateKey
func SceRegCreateKey(hd uint32, name unsafe.Pointer, typeValue int32, size uint32) int32

//go:linkname SceRegRemoveRegistry sceRegRemoveRegistry
func SceRegRemoveRegistry(reg unsafe.Pointer) int32
