// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputils.h

// Package utils provides direct TinyGo bindings for psputils.h.
package utils

import "unsafe"

var _ unsafe.Pointer

const (
	SCHED_OTHER               = 0
	SCHED_MIN                 = 0
	SCHED_MAX                 = 2
	PTHREAD_MUTEX_TIMED_NP    = 0
	PTHREAD_MUTEX_ADAPTIVE_NP = 0
	PTHREAD_MUTEX_NORMAL      = 0
	PTHREAD_MUTEX_RECURSIVE   = 1
	PTHREAD_MUTEX_ERRORCHECK  = 2
	PTHREAD_MUTEX_DEFAULT     = 0
)

//go:linkname SceKernelLibcTime sceKernelLibcTime
func SceKernelLibcTime(t unsafe.Pointer) int32

//go:linkname SceKernelLibcClock sceKernelLibcClock
func SceKernelLibcClock() int32

//go:linkname SceKernelLibcGettimeofday sceKernelLibcGettimeofday
func SceKernelLibcGettimeofday(tp unsafe.Pointer, tzp unsafe.Pointer) int32

//go:linkname SceKernelDcacheWritebackAll sceKernelDcacheWritebackAll
func SceKernelDcacheWritebackAll()

//go:linkname SceKernelDcacheWritebackInvalidateAll sceKernelDcacheWritebackInvalidateAll
func SceKernelDcacheWritebackInvalidateAll()

//go:linkname SceKernelDcacheWritebackRange sceKernelDcacheWritebackRange
func SceKernelDcacheWritebackRange(p unsafe.Pointer, size uint32)

//go:linkname SceKernelDcacheWritebackInvalidateRange sceKernelDcacheWritebackInvalidateRange
func SceKernelDcacheWritebackInvalidateRange(p unsafe.Pointer, size uint32)

//go:linkname SceKernelDcacheInvalidateRange sceKernelDcacheInvalidateRange
func SceKernelDcacheInvalidateRange(p unsafe.Pointer, size uint32)

//go:linkname SceKernelIcacheInvalidateAll sceKernelIcacheInvalidateAll
func SceKernelIcacheInvalidateAll()

//go:linkname SceKernelIcacheInvalidateRange sceKernelIcacheInvalidateRange
func SceKernelIcacheInvalidateRange(p unsafe.Pointer, size uint32)

//go:linkname SceKernelUtilsMt19937Init sceKernelUtilsMt19937Init
func SceKernelUtilsMt19937Init(ctx unsafe.Pointer, seed uint32) int32

//go:linkname SceKernelUtilsMt19937UInt sceKernelUtilsMt19937UInt
func SceKernelUtilsMt19937UInt(ctx unsafe.Pointer) int32

//go:linkname SceKernelUtilsMd5Digest sceKernelUtilsMd5Digest
func SceKernelUtilsMd5Digest(data unsafe.Pointer, size uint32, digest unsafe.Pointer) int32

//go:linkname SceKernelUtilsMd5BlockInit sceKernelUtilsMd5BlockInit
func SceKernelUtilsMd5BlockInit(ctx unsafe.Pointer) int32

//go:linkname SceKernelUtilsMd5BlockUpdate sceKernelUtilsMd5BlockUpdate
func SceKernelUtilsMd5BlockUpdate(ctx unsafe.Pointer, data unsafe.Pointer, size uint32) int32

//go:linkname SceKernelUtilsMd5BlockResult sceKernelUtilsMd5BlockResult
func SceKernelUtilsMd5BlockResult(ctx unsafe.Pointer, digest unsafe.Pointer) int32

//go:linkname SceKernelUtilsSha1Digest sceKernelUtilsSha1Digest
func SceKernelUtilsSha1Digest(data unsafe.Pointer, size uint32, digest unsafe.Pointer) int32

//go:linkname SceKernelUtilsSha1BlockInit sceKernelUtilsSha1BlockInit
func SceKernelUtilsSha1BlockInit(ctx unsafe.Pointer) int32

//go:linkname SceKernelUtilsSha1BlockUpdate sceKernelUtilsSha1BlockUpdate
func SceKernelUtilsSha1BlockUpdate(ctx unsafe.Pointer, data unsafe.Pointer, size uint32) int32

//go:linkname SceKernelUtilsSha1BlockResult sceKernelUtilsSha1BlockResult
func SceKernelUtilsSha1BlockResult(ctx unsafe.Pointer, digest unsafe.Pointer) int32
