// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_netconf.h

// Package utility_netconf provides direct TinyGo bindings for psputility_netconf.h.
package utility_netconf

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityNetconfInitStart sceUtilityNetconfInitStart
func SceUtilityNetconfInitStart(data unsafe.Pointer) int32

//go:linkname SceUtilityNetconfShutdownStart sceUtilityNetconfShutdownStart
func SceUtilityNetconfShutdownStart() int32

//go:linkname SceUtilityNetconfUpdate sceUtilityNetconfUpdate
func SceUtilityNetconfUpdate(unknown int32) int32

//go:linkname SceUtilityNetconfGetStatus sceUtilityNetconfGetStatus
func SceUtilityNetconfGetStatus() int32
