// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspstdio.h

// Package stdio provides direct TinyGo bindings for pspstdio.h.
package stdio

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceKernelStdin sceKernelStdin
func SceKernelStdin() int32

//go:linkname SceKernelStdout sceKernelStdout
func SceKernelStdout() int32

//go:linkname SceKernelStderr sceKernelStderr
func SceKernelStderr() int32
