// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspsyscon.h

// Package syscon provides direct TinyGo bindings for pspsyscon.h.
package syscon

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceSysconPowerStandby sceSysconPowerStandby
func SceSysconPowerStandby()

//go:linkname SceSysconResetDevice sceSysconResetDevice
func SceSysconResetDevice(unk1 int32, unk2 int32)

//go:linkname SceSysconCtrlLED sceSysconCtrlLED
func SceSysconCtrlLED(SceLED int32, state int32) int32

//go:linkname SceSysconCtrlHRPower sceSysconCtrlHRPower
func SceSysconCtrlHRPower(power int32) int32

//go:linkname SceSysconGetHPConnect sceSysconGetHPConnect
func SceSysconGetHPConnect() int32

//go:linkname SceSysconSetHPConnectCallback sceSysconSetHPConnectCallback
func SceSysconSetHPConnectCallback(arg0 unsafe.Pointer, unk0 int32) int32

//go:linkname SceSysconSetHRPowerCallback sceSysconSetHRPowerCallback
func SceSysconSetHRPowerCallback(arg0 unsafe.Pointer, unk0 int32) int32

//go:linkname SceSysconGetPommelVersion sceSysconGetPommelVersion
func SceSysconGetPommelVersion(version unsafe.Pointer) int32

//go:linkname SceSysconGetBaryonVersion sceSysconGetBaryonVersion
func SceSysconGetBaryonVersion(version unsafe.Pointer) int32

//go:linkname SceSysconGetPolestarVersion sceSysconGetPolestarVersion
func SceSysconGetPolestarVersion(version unsafe.Pointer) int32

//go:linkname SceSysconGetTimeStamp sceSysconGetTimeStamp
func SceSysconGetTimeStamp(timeStamp unsafe.Pointer) int32

//go:linkname SceSysconReceiveSetParam sceSysconReceiveSetParam
func SceSysconReceiveSetParam(n int32, buf unsafe.Pointer) int32
