// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psppower.h

// Package power provides direct TinyGo bindings for psppower.h.
package power

import "unsafe"

var _ unsafe.Pointer

//go:linkname ScePowerRegisterCallback scePowerRegisterCallback
func ScePowerRegisterCallback(slot int32, cbid int32) int32

//go:linkname ScePowerUnregisterCallback scePowerUnregisterCallback
func ScePowerUnregisterCallback(slot int32) int32

//go:linkname ScePowerIsPowerOnline scePowerIsPowerOnline
func ScePowerIsPowerOnline() int32

//go:linkname ScePowerIsBatteryExist scePowerIsBatteryExist
func ScePowerIsBatteryExist() int32

//go:linkname ScePowerIsBatteryCharging scePowerIsBatteryCharging
func ScePowerIsBatteryCharging() int32

//go:linkname ScePowerGetBatteryChargingStatus scePowerGetBatteryChargingStatus
func ScePowerGetBatteryChargingStatus() int32

//go:linkname ScePowerIsLowBattery scePowerIsLowBattery
func ScePowerIsLowBattery() int32

//go:linkname ScePowerIsSuspendRequired scePowerIsSuspendRequired
func ScePowerIsSuspendRequired() int32

//go:linkname ScePowerGetBatteryRemainCapacity scePowerGetBatteryRemainCapacity
func ScePowerGetBatteryRemainCapacity() int32

//go:linkname ScePowerGetBatteryFullCapacity scePowerGetBatteryFullCapacity
func ScePowerGetBatteryFullCapacity() int32

//go:linkname ScePowerGetBatteryLifePercent scePowerGetBatteryLifePercent
func ScePowerGetBatteryLifePercent() int32

//go:linkname ScePowerGetBatteryLifeTime scePowerGetBatteryLifeTime
func ScePowerGetBatteryLifeTime() int32

//go:linkname ScePowerGetBatteryTemp scePowerGetBatteryTemp
func ScePowerGetBatteryTemp() int32

//go:linkname ScePowerGetBatteryElec scePowerGetBatteryElec
func ScePowerGetBatteryElec() int32

//go:linkname ScePowerGetBatteryVolt scePowerGetBatteryVolt
func ScePowerGetBatteryVolt() int32

//go:linkname ScePowerSetCpuClockFrequency scePowerSetCpuClockFrequency
func ScePowerSetCpuClockFrequency(cpufreq int32) int32

//go:linkname ScePowerSetBusClockFrequency scePowerSetBusClockFrequency
func ScePowerSetBusClockFrequency(busfreq int32) int32

//go:linkname ScePowerGetCpuClockFrequency scePowerGetCpuClockFrequency
func ScePowerGetCpuClockFrequency() int32

//go:linkname ScePowerGetCpuClockFrequencyInt scePowerGetCpuClockFrequencyInt
func ScePowerGetCpuClockFrequencyInt() int32

//go:linkname ScePowerGetCpuClockFrequencyFloat scePowerGetCpuClockFrequencyFloat
func ScePowerGetCpuClockFrequencyFloat() float32

//go:linkname ScePowerGetBusClockFrequency scePowerGetBusClockFrequency
func ScePowerGetBusClockFrequency() int32

//go:linkname ScePowerGetBusClockFrequencyInt scePowerGetBusClockFrequencyInt
func ScePowerGetBusClockFrequencyInt() int32

//go:linkname ScePowerGetBusClockFrequencyFloat scePowerGetBusClockFrequencyFloat
func ScePowerGetBusClockFrequencyFloat() float32

//go:linkname ScePowerSetClockFrequency scePowerSetClockFrequency
func ScePowerSetClockFrequency(pllfreq int32, cpufreq int32, busfreq int32) int32

//go:linkname ScePowerLock scePowerLock
func ScePowerLock(unknown int32) int32

//go:linkname ScePowerUnlock scePowerUnlock
func ScePowerUnlock(unknown int32) int32

//go:linkname ScePowerTick scePowerTick
func ScePowerTick(typeValue int32) int32

//go:linkname ScePowerGetIdleTimer scePowerGetIdleTimer
func ScePowerGetIdleTimer() int32

//go:linkname ScePowerIdleTimerEnable scePowerIdleTimerEnable
func ScePowerIdleTimerEnable(unknown int32) int32

//go:linkname ScePowerIdleTimerDisable scePowerIdleTimerDisable
func ScePowerIdleTimerDisable(unknown int32) int32

//go:linkname ScePowerRequestStandby scePowerRequestStandby
func ScePowerRequestStandby() int32

//go:linkname ScePowerRequestSuspend scePowerRequestSuspend
func ScePowerRequestSuspend() int32

//go:linkname ScePowerRequestColdReset scePowerRequestColdReset
func ScePowerRequestColdReset(exitcode int32) int32
