// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: psputility_usbmodules.h

// Package utility_usbmodules provides direct TinyGo bindings for psputility_usbmodules.h.
package utility_usbmodules

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUtilityLoadUsbModule sceUtilityLoadUsbModule
func SceUtilityLoadUsbModule(module int32) int32

//go:linkname SceUtilityUnloadUsbModule sceUtilityUnloadUsbModule
func SceUtilityUnloadUsbModule(module int32) int32
