// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspgu.h

// Package gu provides direct TinyGo bindings for pspgu.h.
package gu

import "unsafe"

var _ unsafe.Pointer

const (
	PSP_GE_MATRIX_BONE0 = 0
	PSP_GE_LIST_DONE    = 0
)

//go:linkname SceGuDepthBuffer sceGuDepthBuffer
func SceGuDepthBuffer(zbp unsafe.Pointer, zbw int32)

//go:linkname SceGuDispBuffer sceGuDispBuffer
func SceGuDispBuffer(width int32, height int32, dispbp unsafe.Pointer, dispbw int32)

//go:linkname SceGuDrawBuffer sceGuDrawBuffer
func SceGuDrawBuffer(psm int32, fbp unsafe.Pointer, fbw int32)

//go:linkname SceGuDrawBufferList sceGuDrawBufferList
func SceGuDrawBufferList(psm int32, fbp unsafe.Pointer, fbw int32)

//go:linkname SceGuDisplay sceGuDisplay
func SceGuDisplay(state int32) int32

//go:linkname SceGuDepthFunc sceGuDepthFunc
func SceGuDepthFunc(function int32)

//go:linkname SceGuDepthMask sceGuDepthMask
func SceGuDepthMask(mask int32)

//go:linkname SceGuDepthOffset sceGuDepthOffset
func SceGuDepthOffset(offset uint32)

//go:linkname SceGuDepthRange sceGuDepthRange
func SceGuDepthRange(near int32, far int32)

//go:linkname SceGuFog sceGuFog
func SceGuFog(near float32, far float32, color uint32)

//go:linkname SceGuInit sceGuInit
func SceGuInit() int32

//go:linkname SceGuTerm sceGuTerm
func SceGuTerm()

//go:linkname SceGuBreak sceGuBreak
func SceGuBreak(mode int32) int32

//go:linkname SceGuContinue sceGuContinue
func SceGuContinue() int32

//go:linkname SceGuSetCallback sceGuSetCallback
func SceGuSetCallback(signal int32, callback unsafe.Pointer) unsafe.Pointer

//go:linkname SceGuSignal sceGuSignal
func SceGuSignal(mode int32, id int32)

//go:linkname SceGuSendCommandf sceGuSendCommandf
func SceGuSendCommandf(cmd int32, argument float32)

//go:linkname SceGuSendCommandi sceGuSendCommandi
func SceGuSendCommandi(cmd int32, argument int32)

//go:linkname SceGuGetMemory sceGuGetMemory
func SceGuGetMemory(size int32) unsafe.Pointer

//go:linkname SceGuStart sceGuStart
func SceGuStart(ctype int32, list unsafe.Pointer) int32

//go:linkname SceGuFinish sceGuFinish
func SceGuFinish() int32

//go:linkname SceGuFinishId sceGuFinishId
func SceGuFinishId(id uint32) int32

//go:linkname SceGuCallList sceGuCallList
func SceGuCallList(list unsafe.Pointer) int32

//go:linkname SceGuCallMode sceGuCallMode
func SceGuCallMode(mode int32)

//go:linkname SceGuCheckList sceGuCheckList
func SceGuCheckList() int32

//go:linkname SceGuSendList sceGuSendList
func SceGuSendList(mode int32, list unsafe.Pointer, context unsafe.Pointer) int32

//go:linkname SceGuSwapBuffers sceGuSwapBuffers
func SceGuSwapBuffers() unsafe.Pointer

//go:linkname SceGuSync sceGuSync
func SceGuSync(mode int32, what int32) int32

//go:linkname SceGuDrawArray sceGuDrawArray
func SceGuDrawArray(prim int32, vtype int32, count int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGuBeginObject sceGuBeginObject
func SceGuBeginObject(vtype int32, count int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGuEndObject sceGuEndObject
func SceGuEndObject() int32

//go:linkname SceGuSetStatus sceGuSetStatus
func SceGuSetStatus(state int32, status int32)

//go:linkname SceGuGetStatus sceGuGetStatus
func SceGuGetStatus(state int32) int32

//go:linkname SceGuSetAllStatus sceGuSetAllStatus
func SceGuSetAllStatus(status int32)

//go:linkname SceGuGetAllStatus sceGuGetAllStatus
func SceGuGetAllStatus() int32

//go:linkname SceGuEnable sceGuEnable
func SceGuEnable(state int32)

//go:linkname SceGuDisable sceGuDisable
func SceGuDisable(state int32)

//go:linkname SceGuLight sceGuLight
func SceGuLight(light int32, typeValue int32, components int32, position unsafe.Pointer)

//go:linkname SceGuLightAtt sceGuLightAtt
func SceGuLightAtt(light int32, atten0 float32, atten1 float32, atten2 float32)

//go:linkname SceGuLightColor sceGuLightColor
func SceGuLightColor(light int32, component int32, color uint32)

//go:linkname SceGuLightMode sceGuLightMode
func SceGuLightMode(mode int32)

//go:linkname SceGuLightSpot sceGuLightSpot
func SceGuLightSpot(light int32, direction unsafe.Pointer, exponent float32, cutoff float32)

//go:linkname SceGuClear sceGuClear
func SceGuClear(flags int32)

//go:linkname SceGuClearColor sceGuClearColor
func SceGuClearColor(color uint32)

//go:linkname SceGuClearDepth sceGuClearDepth
func SceGuClearDepth(depth uint32)

//go:linkname SceGuClearStencil sceGuClearStencil
func SceGuClearStencil(stencil uint32)

//go:linkname SceGuPixelMask sceGuPixelMask
func SceGuPixelMask(mask uint32)

//go:linkname SceGuColor sceGuColor
func SceGuColor(color uint32)

//go:linkname SceGuColorFunc sceGuColorFunc
func SceGuColorFunc(funcValue int32, color uint32, mask uint32)

//go:linkname SceGuColorMaterial sceGuColorMaterial
func SceGuColorMaterial(components int32)

//go:linkname SceGuAlphaFunc sceGuAlphaFunc
func SceGuAlphaFunc(funcValue int32, value int32, mask int32)

//go:linkname SceGuAmbient sceGuAmbient
func SceGuAmbient(color uint32)

//go:linkname SceGuAmbientColor sceGuAmbientColor
func SceGuAmbientColor(color uint32)

//go:linkname SceGuBlendFunc sceGuBlendFunc
func SceGuBlendFunc(op int32, src int32, dest int32, srcfix uint32, destfix uint32)

//go:linkname SceGuMaterial sceGuMaterial
func SceGuMaterial(mode int32, color int32)

//go:linkname SceGuModelColor sceGuModelColor
func SceGuModelColor(emissive uint32, ambient uint32, diffuse uint32, specular uint32)

//go:linkname SceGuStencilFunc sceGuStencilFunc
func SceGuStencilFunc(funcValue int32, ref int32, mask int32)

//go:linkname SceGuStencilOp sceGuStencilOp
func SceGuStencilOp(fail int32, zfail int32, zpass int32)

//go:linkname SceGuSpecular sceGuSpecular
func SceGuSpecular(power float32)

//go:linkname SceGuFrontFace sceGuFrontFace
func SceGuFrontFace(order int32)

//go:linkname SceGuLogicalOp sceGuLogicalOp
func SceGuLogicalOp(op int32)

//go:linkname SceGuSetDither sceGuSetDither
func SceGuSetDither(matrix unsafe.Pointer)

//go:linkname SceGuShadeModel sceGuShadeModel
func SceGuShadeModel(mode int32)

//go:linkname SceGuCopyImage sceGuCopyImage
func SceGuCopyImage(psm int32, sx int32, sy int32, width int32, height int32, srcw int32, src unsafe.Pointer, dx int32, dy int32, destw int32, dest unsafe.Pointer)

//go:linkname SceGuTexEnvColor sceGuTexEnvColor
func SceGuTexEnvColor(color uint32)

//go:linkname SceGuTexFilter sceGuTexFilter
func SceGuTexFilter(min int32, mag int32)

//go:linkname SceGuTexFlush sceGuTexFlush
func SceGuTexFlush()

//go:linkname SceGuTexFunc sceGuTexFunc
func SceGuTexFunc(tfx int32, tcc int32)

//go:linkname SceGuTexImage sceGuTexImage
func SceGuTexImage(mipmap int32, width int32, height int32, tbw int32, tbp unsafe.Pointer)

//go:linkname SceGuTexLevelMode sceGuTexLevelMode
func SceGuTexLevelMode(mode uint32, bias float32)

//go:linkname SceGuTexMapMode sceGuTexMapMode
func SceGuTexMapMode(mode int32, lu uint32, lv uint32)

//go:linkname SceGuTexMode sceGuTexMode
func SceGuTexMode(tpsm int32, maxmips int32, mc int32, swizzle int32)

//go:linkname SceGuTexOffset sceGuTexOffset
func SceGuTexOffset(u float32, v float32)

//go:linkname SceGuTexProjMapMode sceGuTexProjMapMode
func SceGuTexProjMapMode(mode int32)

//go:linkname SceGuTexScale sceGuTexScale
func SceGuTexScale(u float32, v float32)

//go:linkname SceGuTexSlope sceGuTexSlope
func SceGuTexSlope(slope float32)

//go:linkname SceGuTexSync sceGuTexSync
func SceGuTexSync()

//go:linkname SceGuTexWrap sceGuTexWrap
func SceGuTexWrap(u int32, v int32)

//go:linkname SceGuClutLoad sceGuClutLoad
func SceGuClutLoad(num_blocks int32, cbp unsafe.Pointer)

//go:linkname SceGuClutMode sceGuClutMode
func SceGuClutMode(cpsm uint32, shift uint32, mask uint32, csa uint32)

//go:linkname SceGuOffset sceGuOffset
func SceGuOffset(x uint32, y uint32)

//go:linkname SceGuScissor sceGuScissor
func SceGuScissor(x int32, y int32, w int32, h int32)

//go:linkname SceGuViewport sceGuViewport
func SceGuViewport(cx int32, cy int32, width int32, height int32)

//go:linkname SceGuDrawBezier sceGuDrawBezier
func SceGuDrawBezier(vtype int32, ucount int32, vcount int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGuPatchDivide sceGuPatchDivide
func SceGuPatchDivide(ulevel uint32, vlevel uint32)

//go:linkname SceGuPatchFrontFace sceGuPatchFrontFace
func SceGuPatchFrontFace(mode uint32)

//go:linkname SceGuPatchPrim sceGuPatchPrim
func SceGuPatchPrim(prim int32)

//go:linkname SceGuDrawSpline sceGuDrawSpline
func SceGuDrawSpline(vtype int32, ucount int32, vcount int32, uedge int32, vedge int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname SceGuSetMatrix sceGuSetMatrix
func SceGuSetMatrix(typeValue int32, matrix unsafe.Pointer)

//go:linkname SceGuBoneMatrix sceGuBoneMatrix
func SceGuBoneMatrix(index uint32, matrix unsafe.Pointer)

//go:linkname SceGuMorphWeight sceGuMorphWeight
func SceGuMorphWeight(index int32, weight float32)

//go:linkname SceGuDrawArrayN sceGuDrawArrayN
func SceGuDrawArrayN(primitive_type int32, vertex_type int32, vcount int32, primcount int32, indices unsafe.Pointer, vertices unsafe.Pointer)

//go:linkname GuSwapBuffersBehaviour guSwapBuffersBehaviour
func GuSwapBuffersBehaviour(behaviour int32)

//go:linkname GuSwapBuffersCallback guSwapBuffersCallback
func GuSwapBuffersCallback(callback unsafe.Pointer)

//go:linkname GuGetStaticVramBuffer guGetStaticVramBuffer
func GuGetStaticVramBuffer(width uint32, height uint32, psm uint32) unsafe.Pointer

//go:linkname GuGetStaticVramTexture guGetStaticVramTexture
func GuGetStaticVramTexture(width uint32, height uint32, psm uint32) unsafe.Pointer

//go:linkname GuGetDisplayState guGetDisplayState
func GuGetDisplayState() int32
