// Code generated by tools/genbindings.py; DO NOT EDIT.
// Source: pspusbbus.h

// Package usbbus provides direct TinyGo bindings for pspusbbus.h.
package usbbus

import "unsafe"

var _ unsafe.Pointer

//go:linkname SceUsbbdRegister sceUsbbdRegister
func SceUsbbdRegister(drv unsafe.Pointer) int32

//go:linkname SceUsbbdUnregister sceUsbbdUnregister
func SceUsbbdUnregister(drv unsafe.Pointer) int32

//go:linkname SceUsbbdClearFIFO sceUsbbdClearFIFO
func SceUsbbdClearFIFO(endp unsafe.Pointer) int32

//go:linkname SceUsbbdReqCancelAll sceUsbbdReqCancelAll
func SceUsbbdReqCancelAll(endp unsafe.Pointer) int32

//go:linkname SceUsbbdStall sceUsbbdStall
func SceUsbbdStall(endp unsafe.Pointer) int32

//go:linkname SceUsbbdReqSend sceUsbbdReqSend
func SceUsbbdReqSend(req unsafe.Pointer) int32

//go:linkname SceUsbbdReqRecv sceUsbbdReqRecv
func SceUsbbdReqRecv(req unsafe.Pointer) int32
